#!/bin/sh
if [ -e "/var/run/${0##*/}.pid" ] ;then
	if [ -e "/proc/$(cat /var/run/${0##*/}.pid)" ];then
		echo "${0##*/} is already running"
		return 2
	fi
fi
echo "$$" > /var/run/${0##*/}.pid

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

judge_isLTE(){
	debug_echo "judge_isLTE --$1--"
	get_module_type="$(echo "$1" | awk -F ' ' '{print $1}')"
	debug_echo "get_module_type=$get_module_type"
	case $get_module_type in
		5GT_W|\
		5Ghuawei|\
		5GF03x|\
		5Grm500|\
		5Grm500u|\
		5Gfm150|\
		FG621)
			judge=0
		;;
		*)
			judge=1
		;;
	esac
	echo "$judge"
}

change_module_ttl_show()
{
	for i in $(seq 1 12)
	do
			if [ -f /tmp/mobile_module_name.txt ];then
				ret="$(cat /tmp/mobile_module_name.txt)"
				ret_isLTE="$(judge_isLTE "$ret")"
				if [ -f /etc/config/netcard_db ];then
					if [ "$ret_isLTE" == 1 ];then
						sed '/\"net_cellular2\"/c"net_cellular2": 1,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' | sed '/\"isLTE\":.*[01]$/c"isLTE": 1' | sed '/\"isLTE\":.*[01],/c"isLTE": 1,' > /www/menu_conf.json
					else
						sed '/\"net_cellular2\"/c"net_cellular2": 1,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' | sed '/\"isLTE\":.*[01]$/c"isLTE": 0' | sed '/\"isLTE\":.*[01],/c"isLTE": 0,' > /www/menu_conf.json
					fi
				else
					if [ "$ret_isLTE" == 1 ];then
						sed '/\"net_cellular1\"/c"net_cellular1": 1,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' | sed '/\"isLTE\":.*[01]$/c"isLTE": 1' | sed '/\"isLTE\":.*[01],/c"isLTE": 1,' > /www/menu_conf.json
					else
						sed '/\"net_cellular1\"/c"net_cellular1": 1,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' | sed '/\"isLTE\":.*[01]$/c"isLTE": 0' | sed '/\"isLTE\":.*[01],/c"isLTE": 0,' > /www/menu_conf.json
					fi
				fi
				debug_echo "find module vid/pid and show cellular"
				exit
			fi
			pidvid="$(lsusb | awk '{print $6}')"
			for id in $pidvid;
			do
				debug_echo "Lsusb vid:pid $id"
				ret="$(grep "$id" /usr/sbin/anywifi/modules/module_list)"
				if [ "$?" == "0" ];then
					ret_isLTE="$(judge_isLTE "$ret")"
					if [ -f /etc/config/netcard_db ];then
						if [ "$ret_isLTE" == 1 ];then
							sed '/\"net_cellular2\"/c"net_cellular2": 1,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' | sed '/\"isLTE\":.*[01]$/c"isLTE": 1' | sed '/\"isLTE\":.*[01],/c"isLTE": 1,' > /www/menu_conf.json
						else
							sed '/\"net_cellular2\"/c"net_cellular2": 1,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' | sed '/\"isLTE\":.*[01]$/c"isLTE": 0' | sed '/\"isLTE\":.*[01],/c"isLTE": 0,' > /www/menu_conf.json
						fi
					else
						if [ "$ret_isLTE" == 1 ];then
							sed '/\"net_cellular1\"/c"net_cellular1": 1,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' |  sed '/\"isLTE\":.*[01]$/c"isLTE": 1' | sed '/\"isLTE\":.*[01],/c"isLTE": 1,' > /www/menu_conf.json
						else
							sed '/\"net_cellular1\"/c"net_cellular1": 1,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' |  sed '/\"isLTE\":.*[01]$/c"isLTE": 0' | sed '/\"isLTE\":.*[01],/c"isLTE": 0,' > /www/menu_conf.json
						fi
					fi
					debug_echo "find module,then show cellular"
					exit
				fi
			done
			cellular_num="$(grep 'net_cellular' /www/menu_conf.json | grep '0' | wc -l)"
			debug_echo "cellular_num=$cellular_num"
			if [ "$cellular_num" -lt 2 ];then
				debug_echo "module and ttl not show"
				if [ -f /etc/config/netcard_db ];then
					sed '/\"net_cellular2\"/c"net_cellular2": 0,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' > /www/menu_conf.json
				else
					sed '/\"net_cellular1\"/c"net_cellular1": 0,' /rom/www/menu_conf.json | sed '/\"ttl\"/c"ttl": 1' > /www/menu_conf.json
				fi
			fi
			sleep 5
	done
}

change_module_ttl_show
if [ -z "$(cat /www/menu_conf.json)" ];then
	change_module_ttl_show
fi
