#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2
 
debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message";fi }
 
my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2                                    
        else                        
                echo -n "$(uci get "$1")"
        fi                       
}

####
dev_mac="$(ifconfig eth0 | awk '/HWaddr/{print $5}' | tr -d : | tr 'A-Z' 'a-z')"
random="$(cat /dev/urandom | head -c 10 | md5sum | head -c 6)"

ngrokid="${dev_mac}${random}"
debug_echo "Ngrokid is $ngrokid"

ngrokid_uci="$(my_uci_get anyos.cloud_weblogin.login_id)"

if [ -z "$ngrokid_uci" ];then
	debug_echo "Start to initialize weblogin"
	uci set anyos.cloud_weblogin.login_id="${ngrokid}"
	uci commit anyos
else
	debug_echo "weblogin is already initialized"
fi

killall ngrokc
