#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "$0 Already running ..." && return 2

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2                                        
        else                            
                echo -n "$(uci get "$1")"
        fi                           
}

#anyversion.device.device_model='MINI4G38M'
#anyversion.device.device_version='20.4.23'

device_module="$(my_uci_get anyversion.device.device_model)"
device_version="$(my_uci_get anyversion.device.device_version)"

control_class_should_be="${device_module}_${device_version}"
control_class_from_cfg="$(cat /etc/kworker.cfg | awk -F '=' '/class/{print $2}')"

if [ "$control_class_should_be" != "$control_class_from_cfg" ];then
	debug_echo "Kworker start to init"
	sed -i "s/class.*/class=$control_class_should_be/g" /etc/kworker.cfg
	/etc/init.d/skworker restart
else
	debug_echo "Kworker already inited"
	exit
fi
