#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "$0 Already running ..." && return 2

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2                                        
        else                            
                echo -n "$(uci get "$1")"
        fi                           
}

ssid_compare(){
	wireless_ssid="$1"
	wifi_ifname="$2"
	if [ "$wireless_ssid" == "" -o "$wifi_ifname" == "" ];then
		debug_echo "wireless_ssid "$wireless_ssid" or wifi_ifname "$wifi_ifname" is NULL"
		echo 1
		return
	fi
	ture_ssid="$(iwconfig 2>/dev/null | grep -w "$wifi_ifname" | awk -F 'ESSID:' '{print $2}' | tr -d ' "')"
	if [ "$wireless_ssid" != "$ture_ssid" ];then
		debug_echo "$wifi_ifname ssid not same --$wireless_ssid-- != --$ture_ssid--"
		echo 1
		return
	fi

	debug_echo ""$wifi_ifname" ssid same"
	echo 0
	return
}


wifi2_ssid_fix(){
	wifi_device="$(my_uci_get anyos.wifi.wifi2_device)"
	wifi_disabled="$(my_uci_get wireless.${wifi_device}.disabled)"
	wifi_disabled="$((wifi_disabled ^ 1))"
	if [ -z "$wifi_device" -o "$wifi_disabled" == 0 ];then
		echo 0
		return
	fi
	ssid_2g="$(my_uci_get wireless.default_radio0.ssid)"
	ssid_2g_guest="$(my_uci_get wireless.guest_wifi.ssid)"
	wifi2_ifname1="$(my_uci_get anyos.wifi.wifi2_ifname | awk '{print $1}')"
	wifi2_ifname2="$(my_uci_get anyos.wifi.wifi2_ifname | awk '{print $2}')"

	ret1="$(ssid_compare $ssid_2g $wifi2_ifname1)"
	ret2=0
	wifi2_guest_wifi="$(my_uci_get wireless.guest_wifi)"
	if [ -n "$wifi2_guest_wifi" ];then
		wifi2_disabled="$(my_uci_get wireless.guest_wifi.disabled)"
		wifi2_disabled="$((wifi2_disabled ^ 1))"
		if [ "$wifi5_disabled" == 1 ];then
			ret2="$(ssid_compare $ssid_2g_guest $wifi2_ifname2)"
		fi
	fi

	if [ "$ret1" != 0 -o "$ret2" != 0 ];then
			debug_echo "master $ret1 guest $ret2, $wifi_device ssid is not right, reset ${wifi_device}.dat"
			cp /rom/etc/wireless/${wifi_device}/${wifi_device}.dat /etc/wireless/${wifi_device}/${wifi_device}.dat
			echo 1
			return
	fi
	echo 0
	return
}

wifi5_ssid_fix(){
	wifi_device="$(my_uci_get anyos.wifi.wifi5_device)"
	wifi_disabled="$(my_uci_get wireless.${wifi_device}.disabled)"
	wifi_disabled="$((wifi_disabled ^ 1))"
	if [ -z "$wifi_device" -o "$wifi_disabled" == 0 ];then
			echo 0
			return
	fi
	ssid_5g="$(my_uci_get wireless.default_radio1.ssid)"
	ssid_5g_guest="$(my_uci_get wireless.guest_wifi1.ssid)"

	wifi5_ifname1="$(my_uci_get anyos.wifi.wifi5_ifname | awk '{print $1}')"
	wifi5_ifname2="$(my_uci_get anyos.wifi.wifi5_ifname | awk '{print $2}')"

	ret1="$(ssid_compare "$ssid_5g" "$wifi5_ifname1")"
	ret2=0
	wifi5_guest_wifi1="$(my_uci_get wireless.guest_wifi1)"
	if [ -n "$wifi5_guest_wifi1" ];then
		wifi5_disabled="$(my_uci_get wireless.guest_wifi1.disabled)"
		wifi5_disabled="$((wifi5_disabled ^ 1))"
		if [ "$wifi5_disabled" == 1 ];then
			ret2="$(ssid_compare "$ssid_5g_guest" "$wifi5_ifname2")"
		fi
	fi
	if [ "$ret1" != 0 -o "$ret2" != 0 ];then
			debug_echo "master $ret1 guest $ret2, $wifi_device ssid is not right, reset ${wifi_device}.dat"
			cp /rom/etc/wireless/${wifi_device}/${wifi_device}.dat /etc/wireless/${wifi_device}/${wifi_device}.dat
			echo 1
			return
	fi
	echo 0
	return
}

debug_echo "####### 0 is same, 1 is different ##########"

ret1="$(wifi2_ssid_fix)"
ret2="$(wifi5_ssid_fix)"

if [ "$ret1" != 0  -o "$ret2" != 0 ];then
       debug_echo "wifi2 $ret1 wifi5 $ret2 ,wifi ssid no right,restart wifi"
       wifi
else
       debug_echo "wifi ssid is rignt ,do nothing"
fi
