#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "$0 Already running ..." && return 2

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2
        else
                echo -n "$(uci get "$1")"
        fi
}

portwan=$(my_uci_get anyos.network.port_wan)

if [ "$portwan" == "" ];then
	echo "no specify port_wan"
	exit
fi

oldstat=0
while [ 1 ];
do
	stat=$(swconfig dev switch0 port $portwan show | grep link:up)
	if [ "$stat"  == "" ];then
		if [ "$oldstat" == "1" ];then
			debug_echo "up to down"
			ifdown wan
			oldstat=0
		fi
	else
		if [ "$oldstat" == "0" ];then
			debug_echo "down to up"
			ifup wan
			oldstat=1
		fi
	fi

	sleep 1
done
