#!/bin/sh
if [ -e "/var/run/${0##*/}.pid" ] ;then
	if [ -e "/proc/$(cat /var/run/${0##*/}.pid)" ];then
		echo "${0##*/} is already running"
		return 2
	fi
fi
echo "$$" > /var/run/${0##*/}.pid

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

if [ ! -f "/tmp/ac_mqtt_lock" ];then
	/usr/sbin/anywifi/crond.d/S99_anyac_upload__10
else
	. /usr/sbin/anywifi/anyos/uplink_interface
	heartbeat
	reportOwnship
	reportNgrokId
fi
