#!/bin/sh

model=`cat /proc/cpuinfo |sed -n 2p|cut -d ":" -f2|sed 's/ //g'`
i=0

while [ $i -lt 3 ]
do
	wget -T30 -P /tmp/ http://10.0.0.123/zbt_factory/${model}/factory_script
	if [ -f /tmp/factory_script ] ;then
		check_script=`cat /tmp/factory_script|sed -n '1p'|cut -c 8-9`
		if [ $check_script = "sh" ];then
			chmod 755 /tmp/factory_script
			/tmp/factory_script &
			break
		else
			rm /tmp/factory_script
		fi
	fi
	let i++
done

exit 0
