#!/bin/sh

chmod 777 /usr/sbin/main_lede_debug
chmod 777 /usr/sbin/setroute
chmod 777 /usr/sbin/4gtxrx

4gtxrx &

#拨号
dial()
{
	dial_dev=$1
	iccid=$2
	ip_tmp="0.0.0.0"
	ip1=$(at-cmd $dial_dev AT\$MYNETACT?|sed -n '2p'|cut -d '"' -f2)
	if [ "$ip1" = "$ip_tmp" ];then
		at-cmd $dial_dev AT\$MYNETACT=0,1
	

	fi
}

#写配置
config()
{
	section=$1
	ifname=$2
	uci set network.$section=interface  
	uci set network.$section.ifname=$ifname
	uci set network.$section.proto=dhcp
	uci set network.$section.model=$model
}




board=`awk 'BEGIN{FS="[ \t]+:[ \t]"} /machine/ {print $2}' /proc/cpuinfo`

atdev="/dev/ttyACM2"
vendor=$(at-cmd $atdev AT+CGMI | sed -n '2p' | cut -d':' -f2|sed 's/ //g'|tr -d '\r')
model=$(at-cmd $atdev AT+CGMR | sed -n '2p'|cut -d':' -f2|sed 's/ //g'|tr -d '\r')
imei=$(at-cmd $atdev AT+GSN | sed -n '2p'|cut -d':' -f2|sed 's/ //g'|sed 's/\"//g'|tr -d '\r')
if [ "$board" = "ZBT-WE2806" ];then
	atdev2="/dev/ttyACM5"
	vendor2=$(at-cmd $atdev2 AT+CGMI|sed -n '2p'|cut -d':' -f2|sed 's/ //g'|tr -d '\r')
	model2=$(at-cmd $atdev2 AT+CGMR|sed -n '2p'|cut -d':' -f2|sed 's/ //g'|tr -d '\r')
	imei2=$(at-cmd $atdev2 AT+GSN|sed -n '2p'|cut -d':' -f2|sed 's/ //g'|sed 's/\"//g'|tr -d '\r')
	imei2_len=$(echo ${imei2}|wc -L)
	if [ $imei2_len != "15" ];then
		vendor2="Not found model2"
		model2=""
		imei2="None"
	fi
fi

#重启模块
#at-cmd $atdev AT+CFUN=1,1
#if [ "$board" = "ZBT-WE2806" ];then
#	sleep 1
#	at-cmd $atdev2 AT+CFUN=1,1
#fi
#sleep 18

#判断模块配置
config_model=`uci get network.4g.model 2>/dev/null`
if [ "$config_model" != "$model" ];then
	config 4g eth1
	if [ "$board" = "ZBT-WE2806" ];then
		config 4g2 eth2
		uci set network.4g.metric=10
		uci set network.4g2.metric=11
		#4g灯
		uci set system.led_4g.dev='eth1'
		uci set system.led_4g2.dev='eth2'
		uci commit system
		/etc/init.d/led reload
	fi
	uci commit network
	/etc/init.d/network reload
fi

#默认启动eth1
#ifconfig eth1 up
#ifconfig eth2 down

while [ 1 ]
do	
	#读卡
	iccid=$(at-cmd $atdev AT+ICCID|sed -n '2p'|cut -c 9-28)
	#iccid="89860617060027589134" 
	iccid_len=$(echo ${iccid}|wc -L)
	if [ $iccid_len != "20" ];then
		iccid="NO SIM"
		cpin="None"
		isp="None"
		signal="0"
	else
		#拨号
		dial $atdev $iccid
		
		cpin=$(at-cmd $atdev AT+CPIN?|sed -n '2p'|cut -d ':' -f2|sed 's/ //g'|tr -d '\r')
		isp=$(at-cmd $atdev AT+COPS?|sed -n '2p'|cut -d '"' -f2)
		isp_dect=$(echo ${isp}|grep "COPS")
		if [ -n "${isp_dect}" ];then
			isp="No Service"
		fi
		signal=$(at-cmd $atdev AT+CSQ|sed -n '2p'|sed 's/.*:\(.*$\)/\1/'| cut -d ',' -f 1|sed 's/ //g')
		if [ "$signal" -le 31 ];then
			signal=$(printf "%d" $((signal*100/31)))
		else
			signal="0"
		fi
	fi	
	
	if [ "$board" = "ZBT-WE2806" ];then
		#读卡
		iccid2=$(at-cmd $atdev2 AT+ICCID|sed -n '2p'|cut -c 9-28)
		#iccid2="89860080191442057347"
		iccid2_len=$(echo ${iccid2}|wc -L)
		if [ $iccid2_len != "20" ];then
			iccid2="NO SIM"
			cpin2="None"
			isp2="None"
			signal2="0"
		else
			#拨号
			dial $atdev2 $iccid
			
			cpin2=$(at-cmd $atdev2 AT+CPIN?|sed -n '2p'|cut -d ':' -f2|sed 's/ //g'|tr -d '\r')
			isp2=$(at-cmd $atdev2 AT+COPS?|sed -n '2p'|cut -d '"' -f2)
			isp2_dect=$(echo ${isp2}|grep "COPS")
			if [ -n "${isp2_dect}" ];then
				isp2="No Service"
			fi
			signal2=$(at-cmd $atdev2 AT+CSQ|sed -n '2p'|sed 's/.*:\(.*$\)/\1/'| cut -d ',' -f 1|sed 's/ //g')
			if [ "$signal2" -le 31 ];then
				signal2=$(printf "%d" $((signal2*100/31)))
			else
				signal2="0"
			fi
		fi
	fi
	
#信号灯
	if [ $board = "ZBT-WE2806" ] || [ $board = "ZbtlinkZBT-WE2416" ];then
		if [ $signal -ge 75 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 1 > /sys/class/leds/rssi2/brightness
			echo 1 > /sys/class/leds/rssi3/brightness
		elif [ $signal -ge 50 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 1 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		elif [ $signal -ge 25 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 0 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		else
			echo 0 > /sys/class/leds/rssi1/brightness
			echo 0 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		fi
	fi
	if [ "$board" = "ZBT-WE2806" ];then	
		if [ $signal2 -ge 75 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 1 > /sys/class/leds/rssi22/brightness
			echo 1 > /sys/class/leds/rssi32/brightness
		elif [ $signal2 -ge 50 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 1 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		elif [ $signal2 -ge 25 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 0 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		else
			echo 0 > /sys/class/leds/rssi12/brightness
			echo 0 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		fi
	fi
	
	#switch_route $signal $signal2 &


#iccid 可改可保存
if [ ! -e /etc/vccid ] ;then
   echo  "57011908240010000001" >/etc/vccid
else
   echo "vccid已经存在"
fi

viccid=`cat /etc/vccid`

#输出json
if [ $board = "ZBT-WE2806" ];then
cat > /tmp/4ginfo <<EOF
{"device_model":"$vendor $model",
"imei":"$imei",
"iccid":"$iccid",
"pin":"$cpin",
"isp":"$isp",
"signal":"$signal",
"device_model2":"$vendor2 $model2",
"imei2":"$imei2",
"iccid2":"$iccid2",
"pin2":"$cpin2",
"isp2":"$isp2",
"signal2":"$signal2",
"viccid":"$viccid"}
EOF
else
cat > /tmp/4ginfo <<EOF
{"device_model":"$vendor $model",
"imei":"$imei",
"iccid":"$iccid",
"pin":"$cpin",
"isp":"$isp",
"signal":"$signal",
"viccid":"$viccid"}
EOF
fi


echo "读卡信息 iccid1 ---$iccid"
echo "读卡信息 iccid2 ---$iccid2"
echo "IMEI信息 imei----$imei"
echo "IMEI2信息 imei2----$imei2"

#vICCID => /tmp/viccid  一行文本
#ICCIDs => /tmp/iccids  一行文本 (多个用 | 分割，最多4个用效)
#IMEIs => /tmp/imeis    一行文本 (多个用 | 分割，最多4个用效)
#DeviceID => /tmp/devid  一行文本
#流量含义： 上行,下行|上行,下行|上行,下行|上行,下行   /tmp/4gflow  单位KiB

if [ "$iccid" = "NO SIM"  ];then
iccid=00000000000000000000
fi
if [ "$iccid2" = "NO SIM"  ];then
iccid2=00000000000000000000
fi

echo "$viccid" >/tmp/viccid
echo "$iccid|$iccid2" >/tmp/iccids
echo "$imei|$imei2" > /tmp/imeis
echo "10000000000000000001" >/tmp/devid




#读取当前配置信息
conf1=`cat /tmp/viccid` 
conf2=`cat /tmp/iccids`
conf3=`cat /tmp/imeis`
conf4=`cat /tmp/devid`
conf5=`cat /tmp/4gflow`

echo "vICCID /tmp/viccid  $conf1"
echo "ICCIDs  /tmp/iccids $conf2"
echo "IMEIs /tmp/imeis    $conf3"
echo "DeviceID  /tmp/devid  $conf4"
echo "流量 /tmp/4gflow  $conf5 "	

mainpid=`ps|grep main_lede_debug|wc -l `	
if [ $mainpid = "1" ];then
        echo "main_lede_debug start......"
	main_lede_debug  >/dev/null 2>&1 &
else
        echo "main_lede_debug runing......"	
fi	
setrouteid=`ps|grep setroute|wc -l `
if [ $setrouteid = "1" ];then
        echo "setroute start......"
	     setroute  >/dev/null 2>&1 &
else
        echo "setroute runing......"	
fi


	      


				
				


echo "##########系统看门狗最后5行#############"
tail -n 5 /tmp/watchdog.log
#启用外网检测
#ping -c 1 114.114.114.114 -I eth1|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >>/tmp/ping &
#ping -c 1 8.8.8.8 -I eth2|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >>/tmp/ping &
#ping -c 1 114.114.114.114 -I eth1|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >>/tmp/ping &
#ping -c 1 8.8.8.8 -I eth2|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >>/tmp/ping &
	






   
        


uptime=`cat /proc/uptime`
date=`date`
echo "$date || $uptime" >/tmp/n720_v5	 


sleep 15


done






#at-cmd /dev/ttyACM2 AT\$MYNETACT=0,1
#at-cmd /dev/ttyACM5 AT\$MYNETACT=0,1
# at-cmd /dev/ttyACM5 AT\$MYNETACT?
