#!/bin/sh

#拨号
dial()
{
	dial_dev=$1
	ip_tmp="0.0.0.0"
	ip1=$(at-cmd $dial_dev AT\$MYNETACT?|sed -n '2p'|cut -d '"' -f2)
	if [ "$ip1" = "$ip_tmp" ];then
		at-cmd $dial_dev AT\$MYNETACT=0,1
	fi
}

#写配置
config()
{
	section=$1
	ifname=$2
	uci set network.$section=interface  
	uci set network.$section.ifname=$ifname
	uci set network.$section.proto=dhcp
	uci set network.$section.model=$model
}

board=`awk 'BEGIN{FS="[ \t]+:[ \t]"} /machine/ {print $2}' /proc/cpuinfo`

atdev="/dev/ttyACM2"
vendor=$(at-cmd $atdev AT+CGMI|sed -n '2p'|cut -d':' -f2|sed 's/ //g'|tr -d '\r')
model=$(at-cmd $atdev AT+CGMR|sed -n '2p'|cut -d':' -f2|sed 's/ //g'|tr -d '\r')
imei=$(at-cmd $atdev AT+GSN|sed -n '2p'|cut -d':' -f2|sed 's/ //g'|sed 's/\"//g'|tr -d '\r')
if [ "$board" = "ZBT-WE2806" ];then
	atdev2="/dev/ttyACM5"
	vendor2=$(at-cmd $atdev2 AT+CGMI|sed -n '2p'|cut -d':' -f2|sed 's/ //g'|tr -d '\r')
	model2=$(at-cmd $atdev2 AT+CGMR|sed -n '2p'|cut -d':' -f2|sed 's/ //g'|tr -d '\r')
	imei2=$(at-cmd $atdev2 AT+GSN|sed -n '2p'|cut -d':' -f2|sed 's/ //g'|sed 's/\"//g'|tr -d '\r')
	imei2_len=$(echo ${imei2}|wc -L)
	if [ $imei2_len != "15" ];then
		vendor2="Not found model2"
		model2=""
		imei2="None"
	fi
fi

#重启模块
at-cmd $atdev AT+CFUN=1,1
if [ "$board" = "ZBT-WE2806" ];then
	sleep 1
	at-cmd $atdev2 AT+CFUN=1,1
fi
sleep 17

#判断模块配置
config_model=`uci get network.4g.model 2>/dev/null`
if [ "$config_model" != "$model" ];then
	config 4g eth1
	if [ "$board" = "ZBT-WE2806" ];then
		config 4g2 eth2
		uci set network.4g.metric=10
		uci set network.4g2.metric=11
		#4g灯
		uci set system.led_4g.dev='eth1'
		uci set system.led_4g2.dev='eth2'
		uci commit system
		/etc/init.d/led reload
	fi
	uci commit network
	/etc/init.d/network reload
fi

while [ 1 ]
do	
	#读卡
	iccid=$(at-cmd $atdev AT+ICCID|sed -n '2p'|cut -c 9-28)
	iccid_len=$(echo ${iccid}|wc -L)
	if [ $iccid_len != "20" ];then
		iccid="NO SIM"
		cpin="None"
		isp="None"
		signal="0"
	else
		#拨号
		dial $atdev
		
		cpin=$(at-cmd $atdev AT+CPIN?|sed -n '2p'|cut -d ':' -f2|sed 's/ //g'|tr -d '\r')
		isp=$(at-cmd $atdev AT+COPS?|sed -n '2p'|cut -d '"' -f2)
		isp_dect=$(echo ${isp}|grep "COPS")
		if [ -n "${isp_dect}" ];then
			isp="No Service"
		fi
		signal=$(at-cmd $atdev AT+CSQ|sed -n '2p'|sed 's/.*:\(.*$\)/\1/'| cut -d ',' -f 1|sed 's/ //g')
		if [ "$signal" -le 31 ];then
			signal=$(printf "%d" $((signal*100/31)))
		else
			signal="0"
		fi
	fi	
	
	if [ "$board" = "ZBT-WE2806" ];then
		#读卡
		iccid2=$(at-cmd $atdev2 AT+ICCID|sed -n '2p'|cut -c 9-28)
		iccid2_len=$(echo ${iccid2}|wc -L)
		if [ $iccid2_len != "20" ];then
			iccid2="NO SIM"
			cpin2="None"
			isp2="None"
			signal2="0"
		else
			#拨号
			dial $atdev2
			
			cpin2=$(at-cmd $atdev2 AT+CPIN?|sed -n '2p'|cut -d ':' -f2|sed 's/ //g'|tr -d '\r')
			isp2=$(at-cmd $atdev2 AT+COPS?|sed -n '2p'|cut -d '"' -f2)
			isp2_dect=$(echo ${isp2}|grep "COPS")
			if [ -n "${isp2_dect}" ];then
				isp2="No Service"
			fi
			signal2=$(at-cmd $atdev2 AT+CSQ|sed -n '2p'|sed 's/.*:\(.*$\)/\1/'| cut -d ',' -f 1|sed 's/ //g')
			if [ "$signal2" -le 31 ];then
				signal2=$(printf "%d" $((signal2*100/31)))
			else
				signal2="0"
			fi
		fi
	fi
	
#信号灯
	if [ $board = "ZBT-WE2806" ] || [ $board = "ZbtlinkZBT-WE2416" ];then
		if [ $signal -ge 75 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 1 > /sys/class/leds/rssi2/brightness
			echo 1 > /sys/class/leds/rssi3/brightness
		elif [ $signal -ge 50 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 1 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		elif [ $signal -ge 25 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 0 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		else
			echo 0 > /sys/class/leds/rssi1/brightness
			echo 0 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		fi
	fi
	if [ "$board" = "ZBT-WE2806" ];then	
		if [ $signal2 -ge 75 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 1 > /sys/class/leds/rssi22/brightness
			echo 1 > /sys/class/leds/rssi32/brightness
		elif [ $signal2 -ge 50 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 1 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		elif [ $signal2 -ge 25 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 0 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		else
			echo 0 > /sys/class/leds/rssi12/brightness
			echo 0 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		fi
	fi


if [ ! -e /etc/vccid ] ;then
mac=`cat /sys/class/net/br-lan/address |sed 's/://g'`
echo  "whmq2018$mac" >/etc/vccid
fi
viccid=`cat /etc/vccid`

#输出json
if [ $board = "ZBT-WE2806" ];then
cat > /tmp/4ginfo <<EOF
{"device_model":"$vendor $model",
"imei":"$imei",
"iccid":"$iccid",
"pin":"$cpin",
"isp":"$isp",
"signal":"$signal",
"device_model2":"$vendor2 $model2",
"imei2":"$imei2",
"iccid2":"$iccid2",
"pin2":"$cpin2",
"isp2":"$isp2",
"signal2":"$signal2",
"viccid":"$viccid"}
EOF
else
cat > /tmp/4ginfo <<EOF
{"device_model":"$vendor $model",
"imei":"$imei",
"iccid":"$iccid",
"pin":"$cpin",
"isp":"$isp",
"signal":"$signal",
"viccid":"$viccid"}
EOF
fi
	sleep 10
done

