#!/bin/sh

#拨号
dial()
{
	dial_dev=$1
	section=$2
	ifname=$3
	#apn
	apn_dect=`uci get network.$section.apn_status 2>/dev/null`
	if [ "${apn_dect}" = "1" ];then
		config_apn=`uci get network.$section.apn 2>/dev/null`
		apn=$(at-cmd $dial_dev AT+CGDCONT? | grep "+CGDCONT: 1,\"IP\""|cut -d '"' -f4)
		if [ "$config_apn" != "" ] && [ "$config_apn" != "$apn" ];then
			at-cmd $dial_dev AT+CGDCONT=1,\"IP\",\"${apn}\"
		fi
	fi
	ip1=$(ifconfig $ifname | grep Bcast | cut -d: -f2 | cut -d' ' -f1)
	if [ "$ip1" = "" ];then
		at-cmd $dial_dev AT\$QCRMCALL=1,1
	fi
}

#写配置
config()
{
	section=$1
	ifname=$2
	uci set network.$section=interface  
	uci set network.$section.ifname=$ifname
	uci set network.$section.proto=dhcp
	uci set network.$section.model=$model
}

board=`awk 'BEGIN{FS="[ \t]+:[ \t]"} /machine/ {print $2}' /proc/cpuinfo`

#读取模块信息 read module information 
atdev="/dev/ttyUSB2"
vendor=$(at-cmd $atdev AT+CGMI | sed -n '2p' | tr -d '\r')
model=$(at-cmd $atdev AT+GMM | sed -n '2p' | tr -d '\r')
imei=$(at-cmd $atdev AT+GSN | sed -n '2p' | tr -d '\r')
if [ "$board" = "ZBT-WE2806" ];then
	atdev2="/dev/ttyUSB7"
	vendor2=$(at-cmd $atdev2 AT+CGMI | sed -n '2p' | tr -d '\r')
	model2=$(at-cmd $atdev2 AT+GMM | sed -n '2p' | tr -d '\r')
	imei2=$(at-cmd $atdev2 AT+GSN | sed -n '2p' | tr -d '\r')
fi 

#判断模块配置 just module config
config_model=`uci get network.4g.model 2>/dev/null`
if [ "$config_model" != "$model" ];then
	config 4g wwan0
	if [ "$board" = "ZBT-WE2806" ];then
		config 4g2 wwan1
		uci set network.4g.metric=10
		uci set network.4g2.metric=11
	fi
	uci commit network
	/etc/init.d/network reload
fi

while [ 1 ]
do
	imei=$(at-cmd $atdev AT+GSN | sed -n '2p' | tr -d '\r')
	#读卡
	iccid=$(at-cmd $atdev AT+ICCID | sed -n '2p' | cut -c 9-28)
	iccid_len=$(echo ${iccid} | wc -L)
	if [ $iccid_len != "20" ];then
		iccid="NO SIM"
		cpin="None"
		isp="None"
		signal="0"
	else
		#拨号
		dial $atdev 4g wwan0
		
		cpin=$(at-cmd $atdev AT+CPIN? | sed -n '2p' | cut -d ':' -f2 | sed 's/ //g' | tr -d '\r')
		isp=$(at-cmd $atdev AT+COPS? | sed -n '2p' | cut -d '"' -f2)
		isp_dect=$(echo ${isp} | grep "COPS")
		if [ -n "${isp_dect}" ];then
			isp="No Service"
		fi
		signal=$(at-cmd $atdev AT+CSQ|sed -n '2p'|sed 's/.*:\(.*$\)/\1/'| cut -d ',' -f 1|sed 's/ //g')
		if [ "$signal" -le 31 ];then
			signal=$(printf "%d" $((signal*100/31)))
		else
			signal="0"
		fi
		
		###for tina liu we826-t2 20191101 by dinotse###
		nwscanmode=`at-cmd /dev/ttyUSB3 AT+QCFG=\"nwscanmode\"|sed -n 2p|cut -d ',' -f2|tr -d '\r'`
		band=`at-cmd /dev/ttyUSB3 AT+QCFG=\"band\"|sed -n 2p|tr -d '\r'`
		bandval=`echo $band|cut -d ',' -f2`
		ltebandval=`echo $band|cut -d ',' -f3`
		###############################################
	fi
	if [ "$board" = "ZBT-WE2806" ];then
		imei2=$(at-cmd $atdev2 AT+GSN |sed -n '2p'|tr -d '\r')
		#读卡
		iccid2=$(at-cmd $atdev2 AT+ICCID|sed -n '2p'|cut -c 9-28)
		iccid2_len=$(echo ${iccid2}|wc -L)
		if [ $iccid2_len != "20" ];then
			iccid2="NO SIM"
			cpin2="None"
			isp2="None"
			signal2="0"
		else
			#拨号
			dial $atdev2 4g2 wwan1
			
			cpin2=$(at-cmd $atdev2 AT+CPIN?|sed -n '2p'|cut -d ':' -f2|sed 's/ //g'|tr -d '\r')
			isp2=$(at-cmd $atdev2 AT+COPS?|sed -n '2p'|cut -d '"' -f2)
			isp2_dect=$(echo ${isp2}|grep "COPS")
			if [ -n "${isp2_dect}" ];then
				isp2="No Service"
			fi
			signal2=$(at-cmd $atdev2 AT+CSQ|sed -n '2p'|sed 's/.*:\(.*$\)/\1/'| cut -d ',' -f 1|sed 's/ //g')
			if [ "$signal2" -le 31 ];then
				signal2=$(printf "%d" $((signal2*100/31)))
			else
				signal2="0"
			fi
		fi
	fi
	
	#信号灯
	if [ $board = "ZBT-WE2806" ] || [ $board = "ZbtlinkZBT-WE2416" ] || [ $board = "ZBT-WE2802D" ] || [ $board = "ZBT-WE2806-A" ];then
		if [ $signal -ge 75 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 1 > /sys/class/leds/rssi2/brightness
			echo 1 > /sys/class/leds/rssi3/brightness
		elif [ $signal -ge 50 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 1 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		elif [ $signal -ge 25 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 0 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		else
			echo 0 > /sys/class/leds/rssi1/brightness
			echo 0 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		fi
	fi
	if [ "$board" = "ZBT-WE2806" ];then	
		if [ $signal2 -ge 75 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 1 > /sys/class/leds/rssi22/brightness
			echo 1 > /sys/class/leds/rssi32/brightness
		elif [ $signal2 -ge 50 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 1 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		elif [ $signal2 -ge 25 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 0 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		else
			echo 0 > /sys/class/leds/rssi12/brightness
			echo 0 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		fi
	fi
	
	#WE2806-A sim卡指示灯
	if [ $board = "ZBT-WE2806-A" ] || [ $board = "ZBT-WE826-E" ] ;then
		sim_gpio=`cat /sys/class/gpio/sim/value`
		if [ $sim_gpio = "1" ];then
			echo 1 > /sys/class/leds/sim1/brightness
			echo 0 > /sys/class/leds/sim2/brightness
			sim="(SIM 1)"
		else
			echo 0 > /sys/class/leds/sim1/brightness
			echo 1 > /sys/class/leds/sim2/brightness
			sim="(SIM 2)"
		fi
	else
		sim=""
	fi
	
	#gps
	at-cmd $atdev AT+QGPS=1
	GPSLOC=`at-cmd $atdev AT+QGPSLOC=0 | sed -n '2p'`
	no_gps=`echo "$GPSLOC"| grep ERROR | wc -l`
	if [ $no_gps = "1" ];then
		gps="0"
		latitude=""
		longitude=""
	else
		gps="1"
		N1=`echo $GPSLOC | cut -d ',' -f2 | tr -d '.' | tr -d 'N'`
		lenN=${#N1}
		numN=`expr $lenN - 6`
		latitude=`echo ${N1:0:$numN}"."${N1:$numN}`

		E1=`echo $GPSLOC | cut -d ',' -f3 | tr -d '.' | tr -d 'E'`
		lenE=${#E1}
		numE=`expr $lenE - 6`
		longitude=`echo ${E1:0:$numE}"."${E1:$numE}`
	fi

#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor $model",
"imei":"$imei",
"iccid":"$iccid$sim",
"pin":"$cpin",
"isp":"$isp",
"signal":"$signal",
"scanmode":"$nwscanmode",
"bandval":"$bandval",
"ltebandval":"$ltebandval",
"gps":"$gps",
"latitude":"$latitude",
"longitude":"$longitude"
}
EOF

if [ $imei2 != "" ];then
cat > /tmp/4ginfo2 <<EOF
{
"device_model":"$vendor2 $model2",
"imei":"$imei2",
"iccid":"$iccid2",
"pin":"$cpin2",
"isp":"$isp2",
"signal":"$signal2"
}
EOF
fi
	sleep 8
done

