#!/bin/sh

#启用4G1
router1()
{
	uci set firewall.@zone[1].network="wan wan6 4g"
	uci set network.4g.defaultroute="1"
	uci set network.4g2.defaultroute="0"
	route add default gw 192.168.0.1 dev eth1
	route del default gw 192.168.0.1 dev eth2
	/etc/init.d/firewall restart
	killall main_lede_debug
}

#启用4G2
router2()
{
	uci set firewall.@zone[1].network="wan wan6 4g2"
	uci set network.4g.defaultroute="0"
	uci set network.4g2.defaultroute="1"
	route add default gw 192.168.0.1 dev eth2
	route del default gw 192.168.0.1 dev eth1
	/etc/init.d/firewall restart
	killall main_lede_debug
}

#停用SIM1,SIM2,使用SIM1与服务器通信
router3()
{
	uci set firewall.@zone[1].network="wan wan6"
	uci set network.4g.defaultroute="1"
	uci set network.4g2.defaultroute="0"
	route add default gw 192.168.0.1 dev eth1
	route del default gw 192.168.0.1 dev eth2
	/etc/init.d/firewall restart
	killall main_lede_debug
}

#判断SIM卡对应ETH接口

while [ 1 ]
do
	chan0=`sed -n "1,2p" /tmp/chanstat`
	if [ ! -e /tmp/chanstat ] ;then
		echo "未收到协议下发！！！"
	else
	    sim1=`cat /tmp/chanstat | sed -n 4p |cut -d "=" -f2`
	    eth1sim=`cat /tmp/4ginfo | sed -n 3p |cut -d ":" -f2 | sed 's/"//g'| sed 's/,//g'`
	
	#判断SIM1于SIM2的优先级
	if [ "$sim1" = "$eth1sim" ] ;then
		echo "SIM1 @ 4G-ETH1;SIM2 @ 4G-ETH2,use /tmp/chanstat "
		signal=`cat /tmp/4ginfo | sed -n 6p | cut -d ":" -f2 | sed 's/"//g' | sed 's/,//g'`
		signal2=`cat /tmp/4ginfo |sed -n 12p|cut -d ":" -f2 | sed 's/"//g' | sed 's/,//g'`
		chan1=`sed -n "3,8p" /tmp/chanstat`
		chan2=`sed -n "9,14p" /tmp/chanstat`
		wwan=4g
		wwan2=4g2
			
cat >/tmp/chanstat2 <<EOF
$chan0
$chan1
$chan2
EOF
	else
		echo "SIM1 @ 4G-ETH2;SIM2 @ 4G-ETH1, use use /tmp/chanstat2" 
		signal=`cat /tmp/4ginfo | sed -n 12p | cut -d ":" -f2 | sed 's/"//g' | sed 's/,//g'`
		signal2=`cat /tmp/4ginfo | sed -n 6p | cut -d ":" -f2 | sed 's/"//g' | sed 's/,//g'`   
		chan2=`sed -n "3,8p" /tmp/chanstat`
		chan1=`sed -n "9,14p" /tmp/chanstat`
		wwan=4g2
		wwan2=4g
#重新生成配置文件
cat >/tmp/chanstat2 <<EOF
$chan0
$chan2
$chan1
EOF
	fi
fi

	#通过main_lede_debug程序配置文件，进行对应的模块调用
	if [ ! -e /tmp/chanstat2 ] ;then
		     echo "未收到协议下发！！！"
	else
		echo "已收到协议下发！！！"
		echo "协议下发的内容"
		chaninfo=`cat /tmp/chanstat2`
		echo "$chaninfo"
		echo "$iccid" >/tmp/eth1
		echo "$iccid2" >/tmp/eth2
	
		sim1_on=`cat /tmp/chanstat2|sed -n 5p |cut -d "=" -f2`
		sim2_on=`cat /tmp/chanstat2|sed -n 11p |cut -d "=" -f2`
	
		ccida=`cat /tmp/eth1`
		ccidb=`cat /tmp/eth1`
		
		select1=`cat /tmp/chanstat2|sed -n 6p |cut -d "=" -f2` #sim1 信号阀
		select2=`cat /tmp/chanstat2|sed -n 12p |cut -d "=" -f2` #sim2 信号阀
	
		newsim1=`cat /tmp/chanstat2|sed -n 4p |cut -d "=" -f2`
		newsim12=`cat /tmp/chanstat2|sed -n 10p |cut -d "=" -f2`
	
		#计算上下行总流量
		#计算上下行总流量
		sim1allflow=`sed -n 1p /etc/4gflowall | awk '{for (i=1; i<= NF; i++) sum += $i;print sum;}'`
		sim2allflow=`sed -n 2p /etc/4gflowall | awk '{for (i=1; i<= NF; i++) sum += $i;print sum;}'`
		echo "SIM1总流量 -- $sim1allflow "
		echo "SIM2总流量 -- $sim2allflow "
		limitRate1=`cat /tmp/chanstat2|sed -n 8p |cut -d "=" -f2`   #sim1 峰值
		limitRate2=`cat /tmp/chanstat2|sed -n 14p |cut -d "=" -f2`  #sim2 峰值
		echo "SIM1设定流量 -- $limitRate1 "
		echo "SIM2设定流量 -- $limitRate2 "
	
		 #判断流量是否超出
		if [ "$sim1allflow" -gt "$limitRate1" ] ;then
		   echo "sim1 流量超出"
		   gonosim1=0
		else
		   echo "sim1 流量剩余"
		   gonosim1=1
		fi
		if [ "$sim2allflow" -gt "$limitRate2" ] ;then
		   echo "sim2 流量超出"
		   gonosim2=0
		else
		   echo "sim2 流量剩余"
		   gonosim2=1
		fi
		echo "signal $signal" 
		echo "signal2 $signal2"	
	
	
		echo "##########当前防火墙规则#############"
	
		fwconf=`uci get firewall.@zone[1].network`
		echo "$fwconf"
	
		echo "##########进入正则#############"
		if  [  "$sim1_on" = "1" ] &&  [ "$gonosim1" = "1" ] ;then
			echo "满足SIM1 开启条件"
			opemsim1=1
			else
			echo "SIM1 关闭或流量超出"
			opemsim1=0
		fi
		if  [  "$sim2_on" = "1" ] && [ "$gonosim2" = "1" ] ;then
		    		echo "满足SIM2 开启条件"
		    			opemsim2=1
		    			else
		    			echo "SIM2 关闭或流量超出"
		    			opemsim2=0						
		fi					
	
		##SIM1,SIM2全开------------------------------------------------------------------
		if  [  "$opemsim1" = "1" ] && [ "$opemsim2" = "1" ] ;then
			echo "SIM1,SIM2全开"
			#1.信号值全部达标
			if  [ "$signal" -ge "$select1" ] && [ "$signal2" -ge "$select2" ] ;then
				echo "信号值全部达标wan wan6 $wwan "
				fwconf2="wan wan6 $wwan"
	
				#2.信号阀值均不达标
			elif [ "$signal" -lt "$select1" ] && [ "$signal2" -lt "$select2" ] ;then
				echo "信号值全未达标wan wan6 $wwan "
				fwconf2="wan wan6 $wwan"
	
				#3.SIM1信号达标
			elif [ "$signal" -ge "$select1" ] && [ "$signal2" -lt "$select2" ] ;then
				echo "SIM1信号达标wan wan6 $wwan "
				fwconf2="wan wan6 $wwan"
	
				#4.SIM2信号达标
			elif [ "$signal" -lt "$select1" ] && [ "$signal2" -ge "$select2" ] ;then
				echo "SIM1信号达标wan wan6 $wwan2 "
				fwconf2="wan wan6 $wwan2"
	
			else 
				echo "没有匹配!!!" 
				echo "-------------------------"
				echo "sim1_on $sim1_on"
				echo "sim2_on $sim2_on"
				echo "gonosim1 $gonosim1"
				echo "gonosim2 $gonosim2"
				echo "signal  $signal"
				echo "signal2 $signal2"
				echo "-------------------------"				   
	
	
			fi					 
	
		fi
	
		##SIM1,单通模式------------------------------------------------------------------
		if  [  "$opemsim1" = "1" ] && [ "$opemsim2" = "0" ] ;then
			echo "SIM1 单通道模式 wan wan6 $wwan"
			fwconf2="wan wan6 $wwan"  
		fi
		##SIM2,单通模式------------------------------------------------------------------				
		if  [  "$opemsim1" = "0" ] && [ "$opemsim2" = "1" ] ;then
			echo "SIM1 单通道模式 wan wan6 $wwan2"
			fwconf2="wan wan6 $wwan2"  
		fi
		##停网模式----------------------------------------------------------------------			
		if  [  "$opemsim1" = "0" ] && [ "$opemsim2" = "0" ] ;then
			echo "停网模式 wan wan6"
			fwconf2="wan wan6"  
		fi					
	
	
	
	
	
		echo "##########更变后防火墙规则#############"
		echo "$fwconf2"
	
		if  [  "$fwconf2" = "$fwconf" ] ;then
			echo "防火墙规则无变化"
		else
			echo "防火墙规则有变化，重启防火墙"
			newroute=`echo "$fwconf2" |awk '{print $3}'`
			if  [  "$newroute" = "4g" ] ;then   
				echo "执行sim1 上网"
				router1
			fi
			if  [  "$newroute" = "4g2" ] ;then   
				echo "执行sim2 上网"
				router2
			fi		
			if  [  "$newroute" = "" ] ;then   
				echo "sim1,sim2 停网"
				router3
			fi
	
		fi
	
		echo "##########系统看门狗最后5行#############"
		tail -n 5 /tmp/watchdog.log
	fi
	
	echo "off-watchdog" >/tmp/ping
	
	sleep 5

done
