#!/bin/sh

model=`cat /proc/cpuinfo |sed -n 2p|cut -d ":" -f2|sed 's/ //g'`
cpu=`cat /proc/cpuinfo |sed -n 1p|cut -c 16-`
ram=`cat /proc/meminfo | grep MemTotal|cut -d ":" -f2|sed 's/ //g'`
flash=`dmesg |grep spi |grep Kbytes|cut -d ":" -f2`
flashid=`cat /proc/flashid`
snserver="https://www.ac-link.com"
#判断CPU型号精准型号，做产测差异
cpuid=`cat /proc/cpuinfo |sed -n 1p|cut -c 25-30`
ping_addr="114.114.114.114"


#######################测试项目的判断###########################################
#测试项目的判断
   echo "$1"|grep modem1 >/tmp/modem1
   echo "$1"|grep modem2 >/tmp/modem2
   echo "$1"|grep wan >/tmp/wan
   echo "$1"|grep lan1 >/tmp/lan1
   echo "$1"|grep lan2 >/tmp/lan2
   echo "$1"|grep lan3 >/tmp/lan3
   echo "$1"|grep lan4 >/tmp/lan4
   echo "$1"|grep usb >/tmp/usb
   echo "$1"|grep rs232 >/tmp/232
   echo "$1"|grep rs485 >/tmp/485

modem1=$(cat /tmp/modem1)
modem2=$(cat /tmp/modem2)
wan=$(cat /tmp/wan)
lan1=$(cat /tmp/lan1)
lan2=$(cat /tmp/lan2)
lan3=$(cat /tmp/lan3)
lan4=$(cat /tmp/lan4)
usb=$(cat /tmp/usb)
rs232=$(cat /tmp/232)
rs485=$(cat /tmp/485)

echo modem1="$modem1"
echo modem2="$modem2"
echo  wan="$wan"
echo  lan1="$lan1"
echo  lan2="$lan2"
echo  lan3="$lan3"
echo  lan4="$lan4"
echo  usb="$usb"

  
if [ -n "$modem1"  ] ;then
echo "test-modem1"
modem1=1
fi
if [ -n "$modem2" ] ;then
echo "test-modem2"
modem2=1
fi
if [ -n "$wan" ] ;then
echo "test-wan"
wan=1
fi
if [ -n "$lan1" ] ;then
echo "test-lan1"
lan1=1
fi
if [ -n "$lan2" ] ;then
echo "test-lan2"
lan2=1
fi
if [ -n "$lan3" ] ;then
echo "test-lan3"
lan3=1
fi
if [ -n "$lan4" ] ;then
echo "test-lan4"
lan4=1
fi
if [ -n "$usb" ] ;then
echo "test-usb"
usb=1
fi
if [ -n "$rs232" ] ;then
echo "test-rs232"
rs232=1
fi
if [ -n "$rs485" ] ;then
echo "test-rs485"
rs485=1
fi
##################################################################
cat > /tmp/welcome.txt <<EOF
------------------------------------------------------------
############################################################# 
##                                                         ## 
##                                                         ## 
##                                                         ## 
##                                                         ## 
##             MQWRT生产测试程序       V2.0                ## 
##                                                         ## 
##                                                         ## 
##                                                         ##
##                                                         ## 
############################################################# 
------------------------------------------------------------
EOF

welcome=`cat /tmp/welcome.txt`
#echo -e "\033[5;34m $welcome \033[0m"
echo -e "\033[36m $welcome \033[0m"


echo "可用测试项目modem1,modem2,wan,lan1,lan2,lan3,lan4,usb,rs232,rs485"
echo "已选测试项目：$1"




echo "当前生产型号：$model"
echo "CPU型号:$cpu"
echo "当前内存：$ram"
echo "Flash:$flash  ID:$flashid"
echo ""
echo -e "\033[43;34m请按复位按钮进入产品测试。。。。。。\033[0m"  

		if [ ! -f "/etc/rc.button/reset" ];then
			echo ""
		else
			rm /etc/rc.button/reset
		fi
		
		if [ ! -f "/tmp/test_log" ];then
			echo ""
		else
			rm /tmp/test_log
		fi
		
		
   
##########复位键测试##############################################
while true
do
btn=`cat /sys/kernel/debug/gpio|grep reset|cut -d ")" -f2|cut -c 6-`
btn1=lo
  # echo "$btn"
   if [ $btn = $btn1 ]
   then
 echo "按键测试完毕，进入下一步"
      break
   fi

done

##########WAN测试##############################################
if [ "$cpuid" = "MT7621" ] || [ "$cpuid" = "MT7620" ] || [ "$cpuid" = "MT7628" ] ;then
	ifport="eth0.2"
fi



if [ "$wan" = "1"  ];then
	echo "开始WAN口测试--ping IP $ping_addr"
	gw_wan=`route |grep $ifport|grep UH|cut -d " " -f1`
	route add default gw $gw_wan 2>/dev/null
	ping -c 2 $ping_addr -I $ifport |grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >/tmp/ping_wan 
    ping_wan=`cat /tmp/ping_wan`
	if [ "$ping_wan" = "" ] ;then
			  echo -e "\033[41;30m WAN1-----测试失败 \033[0m"
              echo "WAN=0" >/tmp/test_log &			  
	else    
			  echo -e "\033[32m WAN1-----测试通过 \033[0m" 
              echo "WAN=1" >/tmp/test_log &			  
	fi
	
fi

##########LAN1测试##############################################
ping_lan1="192.168.1.101"
ping_lan2="192.168.1.102"
ping_lan3="192.168.1.103"
ping_lan4="192.168.1.104"

if [ "$lan1" = "1"  ];then
	echo "开始测试LAN1口，ping  IP $ping_lan1"
	ping -c 2 $ping_lan1|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >/tmp/ping_lan1 
	ping_lan1=`cat /tmp/ping_lan1`	
	if [ "$ping_lan1" = "" ] ;then 
 			  echo -e "\033[41;30m LAN1-----测试失败 \033[0m"
              echo "LAN1=0" >>/tmp/test_log &			  

	else    
			  echo -e "\033[32m LAN1-----测试通过 \033[0m" 
              echo "LAN1=1" >>/tmp/test_log &			  
	fi	
		
		
fi
if [ "$lan2" = "1"  ];then
	echo "开始测试LAN2口，ping  IP $ping_lan2"
	ping -c 2 $ping_lan2|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >/tmp/ping_lan2 
	ping_lan2=`cat /tmp/ping_lan2`	
	if [ "$ping_lan2" = "" ] ;then 
 			  echo -e "\033[41;30m LAN1-----测试失败 \033[0m"
              echo "LAN2=0" >>/tmp/test_log &			  

	else    
			  echo -e "\033[32m LAN1-----测试通过 \033[0m" 
              echo "LAN2=1" >>/tmp/test_log &			  
	fi	
		
		
fi
if [ "$lan3" = "1"  ];then
	echo "开始测试LAN3口，ping  IP $ping_lan3"
	ping -c 2 $ping_lan3|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >/tmp/ping_lan3 
	ping_lan3=`cat /tmp/ping_lan3`	
	if [ "$ping_lan3" = "" ] ;then 
 			  echo -e "\033[41;30m LAN1-----测试失败 \033[0m"
              echo "LAN3=0" >>/tmp/test_log &			  

	else    
			  echo -e "\033[32m LAN1-----测试通过 \033[0m" 
              echo "LAN3=1" >>/tmp/test_log &			  
	fi	
		
		
fi
if [ "$lan4" = "1"  ];then
	echo "开始测试LAN3口，ping  IP $ping_lan4"
	ping -c 2 $ping_lan4|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >/tmp/ping_lan4 
	ping_lan4=`cat /tmp/ping_lan4`	
	if [ "$ping_lan4" = "" ] ;then 
 			  echo -e "\033[41;30m LAN1-----测试失败 \033[0m"
              echo "LAN4=0" >>/tmp/test_log &			  

	else    
			  echo -e "\033[32m LAN1-----测试通过 \033[0m" 
              echo "LAN4=1" >>/tmp/test_log &			  
	fi	
		
		
fi
##########4G模块测试##############################################
#1.统计SIM卡号是否为20位，判断读卡是否成功
#2.使用4G对应接口ping外网，检查是否ping通

	if [ "$modem1" = "1" ] ;then
	sim1=`cat /tmp/4ginfo|grep iccid|cut -d ':' -f2|sed 's/,//g'|sed 's/\"//g'|wc -L`

	   if [ "$sim1" = "20" ] ;then
			echo "SIM卡1座读卡正常，读到20位卡号"
			echo "sim1=1" >>/tmp/test_log &
			
			ifname1=`uci get network.4g.ifname`
			gw1=`route |grep $ifname1|grep UH|cut -d " " -f1`
			route add default gw $gw1 2>/dev/null
			ping -c 3 $ping_addr -I $ifname1|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >/tmp/ping_modem1 
			    ping_modem1=`cat /tmp/ping_modem1`
				if [ "$ping_modem1" = "" ] ;then 
						  echo -e "\033[41;30m 4G模块1-----测试失败 \033[0m"
						  echo "modem1=0" >>/tmp/test_log &			  

				else    
						  echo -e "\033[32m 4G模块1-----测试通过 \033[0m" 
						  echo "modem1=1" >>/tmp/test_log &			  
				fi			
		else
			echo "sim1=0" >>/tmp/test_log &
	   fi
	fi
	
	if [ "$modem2" = "1" ] ;then	
	sim2=`cat /tmp/4ginfo2|grep iccid|cut -d ':' -f2|sed 's/,//g'|sed 's/\"//g'|wc -L`

	   if [ "$sim2" = "20" ] ;then
			echo "SIM卡2座读卡正常，读到20位卡号"
			echo "sim2=1" >>/tmp/test_log &
			
			ifname2=`uci get network.4g2.ifname`
			gw2=`route |grep $ifname2|grep UH|cut -d " " -f1`
			route add default gw $gw2 2>/dev/null
			ping -c 3 $ping_addr -I $ifname2|grep ms|sed -n '1p'|sed 's/.*time\(.*$\)/\1/' >/tmp/ping_modem2 
			    ping_modem2=`cat /tmp/ping_modem2`
				if [ "$ping_modem2" = "" ] ;then 
						  echo -e "\033[41;30m 4G模块2-----测试失败 \033[0m"
						  echo "modem2=0" >>/tmp/test_log &			  

				else    
						  echo -e "\033[32m 4G模块1-----测试通过 \033[0m" 
						  echo "modem2=1" >>/tmp/test_log &			  
				fi
		else
			echo "sim2=0" >>/tmp/test_log &
	   fi
	fi 

####################USB接口测试#########################################
if [ "$usb" = "1" ] ;then
dfinfo=`df|grep /mnt | awk '{print $NF}'`
echo "$dfinfo"
dd if=/dev/zero of=a bs=1024k count=10 >$dfinfo/aaaa

	if [ -f "$dfinfo"/aaaa ];then
	echo -e "\033[32m USB-----测试通过 \033[0m" 
	rm $dfinfo/aaaa
	echo "USB=1" >>/tmp/test_log &
	else
	echo -e "\033[41;30m USB-----测试失败 \033[0m"
	echo "USB=0" >>/tmp/test_log &
	fi

fi

####################RS232接口测试#########################################
if [ "$rs232" = "1" ] ;then
cat > /tmp/r232 <<EOF
#!/usr/bin/lua

rserial=io.open("/dev/ttyS0","r")

while true do
    chaine=rserial:read(1)
    if chaine ~= nil then
        local file = io.open("/tmp/rs232","w")
        os.exit()
    end
end
EOF
	rm /tmp/rs232 2>/dev/null
	chmod 777 /tmp/r232                   
	/tmp/r232 &                           
	echo "test" > /dev/ttyS0              
	sleep 1                               
	/tmp/r232 &                           
	echo "test" > /dev/ttyS0              
	sleep 1                 
							
	if [ -f /tmp/rs232 ];then
		echo -e "\033[32m RS232-----测试通过 \033[0m"
		echo "RS232=1" >>/tmp/test_log &                 
	else                                             
		echo -e "\033[41;30m RS232-----测试失败 \033[0m"
		echo "RS232=0" >>/tmp/test_log &                    
	fi
fi

####################RS485接口测试#########################################
if [ "$rs485" = "1" ] ;then
	tty-cmd "RS485pass"
	echo -e "\033[32m 查看电脑串口助手，接收到 RS485pass 即为测试通过 \033[0m"
fi

cat > /tmp/pass.txt <<EOF
------------------------------------------------------------
     ########     ###     ######   ######
     ##     ##   ## ##   ##    ## ##    ##
     ##     ##  ##   ##  ##       ##
     ########  ##     ##  ######   ######
     ##        #########       ##       ##
     ##        ##     ## ##    ## ##    ##
     ##        ##     ##  ######   ######
------------------------------------------------------------
EOF
pass=`cat /tmp/pass.txt`
cat > /tmp/failed.txt <<EOF
------------------------------------------------------------
########    ###    #### ##       ######## ########
##         ## ##    ##  ##       ##       ##     ##
##        ##   ##   ##  ##       ##       ##     ##
######   ##     ##  ##  ##       ######   ##     ##
##       #########  ##  ##       ##       ##     ##
##       ##     ##  ##  ##       ##       ##     ##
##       ##     ## #### ######## ######## ########
------------------------------------------------------------
EOF

failed=`cat /tmp/failed.txt`





#########################通过日志文件分析测试的结果###############

menu=`cat /tmp/test_log |grep =0`    #结果为空表示没有失败的测试项目

if 	[ "$menu" = "" ] ;then
	result=1      #全部测试成功
else
	result=0      #有测试失败项目
fi

if 	[ "$result" = "1" ] ;then
	echo -e "\033[32m $pass\033[0m" 
else
	echo -e "\033[31m $failed\033[0m"
	echo -e "\033[43;34m 测试失败的项目 \033[0m"
	echo -e "\033[43;34m$menu \033[0m"
fi	

if 	[ "$result" = "1" ] ;then
	if [ "$cpuid" = "MT7628" ] || [ "$cpuid" = "MT7620" ] || [ "$cpuid" = "MT7621" ];then
############################### 7620/7628写MAC和SN############################
		#####写SN
		mac_old=`hexdump -C -s 0x2e /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'`
		sn=`curl -k "$snserver/api/get_mqwrt_sn?flashid=$flashid&model=$model&mac=$mac_old&token=1234567" |cut -c  14-29`

		echo "$sn"
		#写入sn

		#校验sn
		#计算SN长度判断是否合法
		snl=`echo "$sn"|wc -L`
		
		if [ "$snl" = "16" ];then
			cp /dev/mtd2 /tmp/art
			sleep 1
			sn_set $sn
			#刷入改过SN的art文件
			cat /tmp/art > /dev/mtdblock2    
		else 
			echo "SN不合法"
		fi

#######################校验SN########################################################
		newsn=`hexdump -C -s 0x88 /dev/mtd2 |sed -n "1p"|cut -c 11-33|sed 's/\ //g'`
		echo -n $newsn$newsn >/proc/authmode
		authmode=`cat /proc/authmode`

		if [ "$authmode" = "1" ] ;then
			echo -e "\033[32m SN写入成功\033[0m" 
			echo -e "\033[32m $pass\033[0m" 
		else 
			echo -e "\033[31m SN写入失败\033[0m"
			echo -e "\033[31m $failed\033[0m"
		fi
    
##########################MAC地址录入判断##########################
		while true
		do
		echo -e "\033[43;34m请用扫描枪录入设备MAC地址。。。。。。\033[0m" 
		read -p " " MAC

		MACL=`echo $MAC|wc -L`  #MAC 长度12位判断合法

		  # echo "$btn"
		   if [ $MACL = "12" ] ;then 
				echo "当前要写入的MAC是$MAC"
				break
		   else 
				echo "MAC地址录入不合法"
		   fi

		done
		
		#刷入改过MAC的art文件
		mac_set $MAC
		cat /tmp/art > /dev/mtdblock2  

#########################  7620/7628校验MAC####################################################
		#先转为10进制
		#MAC地址为0开头会出现异常
		#2.4G和lan mac为输入mac，wan 输入mac+1，5.8G 输入mac+2
		mac0=`printf %d 0x$MAC`
		mac1=`expr $mac0 + 1`
		mac2=`expr $mac0 + 2`

		maca=`printf "%x" $mac0`
		macb=`printf "%x" $mac0`
		macc=`printf "%x" $mac1`
		macd=`printf "%x" $mac2`

		echo "预期要写入的 mac"
		echo "2.4G:$maca"
		echo "LAN:$macb"
		echo "WAN:$macc"
		echo "5.8G:$macd"

		if [ "$cpuid" = "MT7628" ] || [ "$cpuid" = "MT7620" ];then
			mac11=`hexdump -C -s 0x04 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'` # 0x04-0x09 MAC FOR 2.4G
			mac22=`hexdump -C -s 0x28 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'` # 0x28-0x2d 
			mac33=`hexdump -C -s 0x2e /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'` # 0x2e-0x33
			mac44=`hexdump -C -s 0x8004 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'`  #0x8004-0x8009 MAC FOR 5G
		elif [ "$cpuid" = "MT7621" ];then
			mac11=`hexdump -C -s 0x04 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'` # 0x04-0x09 MAC FOR 2.4G
			mac22=`hexdump -C -s 0xe000 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'` # 0xe000-0xe005 
			mac33=`hexdump -C -s 0xe006 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'` # 0xe006-0xe00b
			mac44=`hexdump -C -s 0x8004 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'`  #0x8004-0x8009 MAC FOR 5G
		fi

		echo "art中读取的 mac"
		echo "2.4G:$mac11"
		echo "LAN:$mac22"
		echo "WAN:$mac33"
		echo "5.8G:$mac44"

		if [ "$maca" = "$mac11" ] ;then
			echo -e "\033[32m 2.4G MAC写入成功\033[0m" 
			echo "mac11=1" >/tmp/test_mac_log 
		else
			echo -e "\033[31m 2.4G MAC写入失败\033[0m"
			echo "mac11=0" >/tmp/test_mac_log 
		fi
		if [ "$macb" = "$mac22" ] ;then
			echo -e "\033[32m LAN MAC写入成功\033[0m" 
			echo "mac22=1" >>/tmp/test_mac_log 
		else
			echo -e "\033[31m LAN MAC写入失败\033[0m"
			echo "mac22=0" >>/tmp/test_mac_log 
		fi 
		if [ "$macc" = "$mac33" ] ;then
			echo -e "\033[32m WAN MAC写入成功\033[0m" 
			echo "mac33=1" >>/tmp/test_mac_log 	
		else
			echo -e "\033[31m WAN MAC写入失败\033[0m"
			echo "mac33=0" >>/tmp/test_mac_log 
		fi
		if [ "$macd" = "$mac44" ] ;then
			echo -e "\033[32m 5.8G MAC写入成功\033[0m" 
			echo "mac44=1" >>/tmp/test_mac_log 
		else
			echo -e "\033[31m 5.8G MAC写入失败\033[0m"
			echo "mac44=0" >>/tmp/test_mac_log 
		fi

		macauth=`cat /tmp/test_mac_log|grep =0`

		if [ "$macauth" = "" ] ;then
			echo -e "\033[32m 所有MAC地址写入成功\033[0m"
			echo -e "\033[32m $pass\033[0m" 
		else
			echo -e "\033[31m MAC地址写入校验失败\033[0m"
			echo -e "\033[31m $failed\033[0m"
		fi
	fi
fi



###############################选择菜单#########################


cat <<EOF
|--------------------------------------------------------------------------|
|                                                                          |
|                        直接按回车重启并复位                              |
|                         输入(1)重新测试                                  |
|--------------------------------------------------------------------------|

               
EOF


read -p "请输入 。。。。。。" input
case $input in
  1)
  echo "1"
  testwrt $1
  ;;
  2)
  echo "2"
  ;;
  0)
	    reboot
  ;;

  G)
#	hhhhh
  ;;
  *)
  echo "$input"

  if [ "$input" = "" ];then
    echo "设备即将复位和重启"
	echo "FACTORY RESET" > /dev/console
	jffs2reset -y && reboot &	
  fi
  
  
;;
esac



		
fi



















