#!/bin/sh


debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }
my_uci_get(){                                                                   
	if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
		debug_echo "$1 not found"  1>&2
	else 
		echo -n "$(uci get "$1")"
	fi                                                                      
} 

# get device model
model=`cat /proc/cpuinfo |sed -n 2p|cut -d ":" -f2|sed 's/ //g'`
wdmodel=$(my_uci_get anyversion.device.device_model)

date=`date`

factory &

#授权
#newsn=`hexdump -C -s 0x88 /dev/mtd2 |sed -n "1p"|cut -c 11-33|sed 's/\ //g'`
#echo -n $newsn$newsn >/proc/authmode

#不同型号的设备，声明不同的GPIO变量,定义看门狗的类型,硬件看门狗wd_mode=1 软件看门狗wd_mode=0
if [ "$model" = "ZbtlinkZBT-WE2416" ] || [ "$model" = "ZbtlinkZBT-WE826-Q" ] ;then 
	wdgpio=2
	low=1
	hig=0
	wd_mode=1
	echo "$model"
elif [ "$model" = "ZBT-WG1608" ] ;then
	wdgpio=3
	low=1
	hig=0
	wd_mode=1
elif [ "$model" = "ZBT-WE826-WD" ] || [ "$model" = "ZBT-WE1026-5G" ] ;then
	wdgpio=11
	low=1
	hig=0
	wd_mode=1
	echo "$model"
elif [ "$model" = "ZBT-WE5926" ] || [ "$model" = "ZBT-WE2802D" ] || [ "$model" = "ZBT-WE2806" ] || [ "$model" = "ZBT-WE5928" ] || [ "$model" = "ZBT-WE2806-A" ]  || [ "$model" = "ZBT-WE2808D" ];then
	wdgpio=37
	low=1
	hig=0
	wd_mode=1
	echo "$model"
	echo 777 main_lede_debug
	#main_lede_debug & #cq_iotc_test
elif [ "$model" = "ZBT-WE5926-EC" ] ;then
	wdgpio=11
	low=1
	hig=0
	wd_mode=1
	echo "$model"
elif [ "$model" = "ZBT-WG3" ] ;then
	wdgpio=27
	low=1
	hig=0
	wd_mode=1
	echo "$model"
elif [ "$model" = "ZBT-WE826-E" ] ;then
	wdgpio=""
	wd_mode=1
	echo "$model"
elif [ "$wdmodel" = "LK828Q" ];then
	wdgpio="2"
	wd_mode=0
	echo "$wdmodel"
elif [ "$wdmodel" = "LK826Q" ];then
	wdgpio="3"
	wd_mode=0
	echo "$wdmodel"
fi

wd_mode_value=`uci get luci.main.wd_mode | wc -l`
if [ "$wd_mode_value" = 0 ] ;then
	uci set luci.main.wd_mode=$wd_mode
	uci commit luci
fi
if [ "$wdgpio" != "" ] ;then
	#初始化GPIO
	echo $wdgpio > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio$wdgpio/direction
	echo $low >/sys/class/gpio/gpio$wdgpio/value
	sleep 1
	echo $hig >/sys/class/gpio/gpio$wdgpio/value
	#生成watchdog脚本
cat > /tmp/feed_dog.sh <<EOF
#!/bin/sh

echo $low >/sys/class/gpio/gpio$wdgpio/value
    sleep 1
echo $hig >/sys/class/gpio/gpio$wdgpio/value
    sleep 1
echo $low >/sys/class/gpio/gpio$wdgpio/value
    sleep 1
echo $hig >/sys/class/gpio/gpio$wdgpio/value
    sleep 1
echo $low >/sys/class/gpio/gpio$wdgpio/value
    sleep 1
echo $hig >/sys/class/gpio/gpio$wdgpio/value
    sleep 1
echo "feed_dog.sh:-------------Feed" >>/tmp/watchdog.log 
EOF

	chmod 777 /tmp/feed_dog.sh
fi

#4G
vidpid=`lsusb`
Quectel_dect=`echo $vidpid |grep "2c7c"`
Quectel_EC20_dect=`echo $vidpid |grep "9215"`
SIMCOM_7600_dect=`echo $vidpid |grep "1e0e"`
Thinkwill_dect=`echo $vidpid |grep "19d2"`
HUAWAI_MU709s_2_dect=`echo $vidpid |grep "12d1:1c25"`
SIERRA_dect=`echo $vidpid |grep "9071"`
LUAT_Air720_dect=`echo $vidpid |grep "1286"`
SR_CJ807_dect=`echo $vidpid |grep "05c6"`
N720V5_dect=`echo $vidpid |grep "8700"`
LM9248_dect=`echo $vidpid |grep "9b11"`

if [ -n "${N720V5_dect}" ];then
	neoway_n720v5 &
elif [ -n "${Quectel_dect}" ] || [ -n "${Quectel_EC20_dect}" ];then
	quectel_ec20_ec25 &
elif [ -n "${Thinkwill_dect}" ];then
	thinkwill_ml7820 &
elif [ -n "${LM9248_dect}" ];then
	tricheer_lm9248 &
elif [ -n "${LUAT_Air720_dect}" ];then
	luat_air720 &
elif [ -n "${HUAWAI_MU709s_2_dect}" ];then
	huawei_mu709s-2 &
else
	/usr/sbin/anywifi/modules/module_rec &
fi


#进入循环检测
while true
do
	date=`date`
	uptime=$(awk '{print $1}' /proc/uptime |sed 's/\..*$//')

	# declare watchdog server
	ping_addr1=`uci get my.@defaults[0].watchdog_server1`
	ping_addr2=`uci get my.@defaults[0].watchdog_server2`
	if [ "$model" = "ZBT-WE2808D" ] || [ "$model" = "ZBT-WG1608" ] ;then
		ping_addr1=127.0.0.1
		ping_addr2=127.0.0.1
	fi

	wd_mode=`uci get luci.main.wd_mode`
	if  [ "$wd_mode" = 1 ] ;then     
		ping -c 2 $ping_addr1 | grep ms | sed -n '1p' | sed 's/.*time\(.*$\)/\1/' > /tmp/ping &
		sleep 10
		ping -c 2 $ping_addr2 | grep ms | sed -n '1p' | sed 's/.*time\(.*$\)/\1/' >> /tmp/ping &
		sleep 10
		ping -c 2 $ping_addr1 | grep ms | sed -n '1p' | sed 's/.*time\(.*$\)/\1/' >> /tmp/ping &
		sleep 10
		ping -c 2 $ping_addr2 | grep ms | sed -n '1p' | sed 's/.*time\(.*$\)/\1/' >> /tmp/ping &

		ping=`cat /tmp/ping`
		if [ "$ping" = "" ] ;then
			echo "$date uptime-$uptime Watchsys:Network IS Down--NO Feed" >> /tmp/watchdog.log 
			if [  "$uptime" -lt 300 ]  ;then
				/tmp/feed_dog.sh &   #运行时间小于5分钟，持续喂狗
				echo "$date uptime-$uptime Watchsys:Network IS Down-uptime<300-Feed" >> /tmp/watchdog.log
			fi
			if [ "$model" = "ZBT-WE2806-A" ] || [ "$model" = "ZBT-WE826-E" ] ;then
				sim_gpio=`cat /sys/class/gpio/sim/value`
				if [ $sim_gpio = "1" ];then
					echo 0 > /sys/class/gpio/sim/value
					echo 0 > /sys/class/gpio/4g/value
					sleep 1
					echo 1 > /sys/class/gpio/4g/value
					echo "$date uptime-$uptime Watchsys:Switch TO SIM1" >> /tmp/watchdog.log 
				else
					echo 1 > /sys/class/gpio/sim/value
					echo 0 > /sys/class/gpio/4g/value
					sleep 1
					echo 1 > /sys/class/gpio/4g/value
					echo "$date uptime-$uptime Watchsys:Switch TO SIM2" >> /tmp/watchdog.log 
				fi
				sleep 25
			fi
		else
			/tmp/feed_dog.sh &        #通网的情况下，持续喂狗              
			echo "$date uptime-$uptime Watchsys:Network IS Ok-------Feed" >> /tmp/watchdog.log 
		 fi
	fi
	
	logl=`cat /tmp/watchdog.log | wc -l`
	if  [ "$logl" -gt 200 ] ;then
		echo "new_log" >/tmp/watchdog.log
	fi

	sleep 10
done
