#!/bin/sh
# Copyright (C) 2009 OpenWrt.org  (C) 2010 OpenWrt.org.cn

blkdev=`dirname $DEVPATH`
#echo $blkdev >> /dev/console  
#echo "ACTION $ACTION" > /dev/console
if [ `basename $blkdev` != "block" ]; then
	device=`basename $DEVPATH`
#echo "device $device" > /dev/console
	if [ -n "$(echo $device | grep "mmc")" ];then
		device_mnt=mmc
	elif [ -n "$(echo $device | grep "sd")" ];then
		device_mnt=$device
	else
		exit
	fi
    case "$ACTION" in
        add)
		mkdir -p /www/usb/$device_mnt
		# vfat & ntfs-3g check
		if [ `which fdisk` ]; then
		
				isntfs=`fdisk -l | grep $device | grep NTFS`
				isvfat=`fdisk -l | grep $device | grep FAT`
				isfuse=`lsmod | grep fuse`
				isntfs3g=`which ntfs-3g`
		else
				isntfs=""
				isvfat=""
		fi 
		
		# mount with ntfs-3g if possible, else with default mount
		if [ "$isntfs" -a "$isfuse" -a "$isntfs3g" ]; then
			ntfs-3g -o nls=utf8 /dev/$device /www/usb/$device_mnt
		elif [ "$isvfat" ]; then
			mount -t vfat -o iocharset=utf8,rw,sync,umask=0000,dmask=0000,fmask=0000 /dev/$device /www/usb/$device_mnt
		else
			mount /dev/$device /www/usb/$device
		fi
		
		if [ -f /dev/${device}/swapfile ]; then
			mkswap /dev/${device}/swapfile
			swapon /dev/${device}/swapfile
		fi
		;;
	remove)
		if [ -f /dev/${device}/swapfile ]; then
			swapoff /dev/${device}/swapfile
		fi
		if [ -n "$device_mnt" ];then
			umount /www/usb/$device_mnt
			rm "/www/usb/${device_mnt}" -r
		fi
		;;
	esac
fi
