#!/usr/bin/perl

require "/lib/core.cgi";

my $model = lc(&read1line('/proc/device-tree/model'));
$model =~ s/\x0//g;

my $rc_support = &readsimple('/etc/rc_support');

my $rc_s = [];

foreach (split(/\s+/,$rc_support->{ $model })) {
	## include other
	if (/^\@([\w\.\-]+)$/ and defined $rc_support->{ $1 }) {
		push @$rc_s,split(/\s+/,$rc_support->{ $1 });	
	}
	else {
		push @$rc_s,$_;
	}
}

push @$rc_s,'pptp' if (-e '/usr/bin/pptp');
push @$rc_s,'pptpd' if (-e '/usr/sbin/pptpd');
push @$rc_s,'l2tp' if (-e '/usr/sbin/xl2tpd');
push @$rc_s,'samba' if (-e '/usr/sbin/samba_multicall');
push @$rc_s,'tfcard' if (-e '/sys/block/mmcblk0');
push @$rc_s,'openvpn' if (-e '/usr/bin/openvpn');

&json_exit({ code => 1, rc_support => $rc_s, model => uc($model) });

