#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2
 
. /usr/sbin/anywifi/dial_common.sh

#ret="$(comgt -d $module_at_usb -s /usr/sbin/anywifi/comgt/$module_type/$module_type.chat)"

module_type=$(cat /tmp/mobile_module_name.txt | awk -F ' ' '{print $1}')
module_data_usb=$(cat /tmp/mobile_module_name.txt | awk -F ' ' '{print $3}')
module_at_usb=$(cat /tmp/mobile_module_name.txt | awk -F ' ' '{print $4}')

num=2
while [ 1 ]
do
	counter=1
	while [ $counter -le $num ]
	do
		sim="$(comgt -d /dev/$module_at_usb -s /usr/sbin/anywifi/comgt/$module_type/$module_type.chat.sim)"
		ret="$(echo "$sim" | grep -w "READY" | wc -l)"
		if [ "$ret" == "1" ];then
			sim="READY"	
			debug_echo "+CPIN: READY"
			break
		else
			sim="no sim card"
			debug_echo "no sim card"
			counter=$(($counter + 1))
			sleep 1
		fi
	done
	
	counter=1
	while [ $counter -le $num ]
	do
		csq="$(comgt -d /dev/$module_at_usb -s /usr/sbin/anywifi/comgt/$module_type/$module_type.chat.csq)"
		ret="$(echo "$csq" | grep "+CSQ:" | awk '{print $2}' | awk -F ',' '{print $1}')"
		if [ "$ret" -le "31" ];then
			csq=$(printf "%d" $((ret*100/31)))
			break
		else
			csq=""
			counter=$(($counter + 1))
			sleep 1
		fi
	done
	debug_echo "CSQ is $csq"

	counter=1
	while [ $counter -le $num ]
	do
		iccid="$(comgt -d /dev/$module_at_usb -s /usr/sbin/anywifi/comgt/$module_type/$module_type.chat.iccid)"
		ret="$(echo "$iccid" |  grep "+CCID:" | awk -F ': ' '{print $2}' | wc -L)"
		if [ "$ret" == "20" ];then
			iccid="$(echo "$iccid" |  grep "+CCID:" | awk -F ': ' '{print $2}' | tr -d '\r')"
			break
		else
			iccid=""
			counter=$(($counter + 1))
			sleep 1
		fi
	done
	debug_echo "iccid is $iccid"
	
	counter=1
	while [ $counter -le $num ]
	do
		imsi="$(comgt -d /dev/$module_at_usb -s /usr/sbin/anywifi/comgt/$module_type/$module_type.chat.imsi)"
		ret="$(echo $imsi | awk -F ' ' '{print $2}' | wc -L)"
		if [ "$ret" == "15" ];then
			imsi="$(echo $imsi | awk -F ' ' '{print $2}')"
			break
		else
			imsi=""
			counter=$(($counter + 1))
			sleep 1
		fi
	done
	debug_echo "imsi is $imsi"
	
	counter=1
	while [ $counter -le $num ]
	do
		imei="$(comgt -d /dev/$module_at_usb -s /usr/sbin/anywifi/comgt/$module_type/$module_type.chat.imei)"
		ret="$(echo $imei | awk -F ' ' '{print $2}' | wc -L)"
		if [ "$ret" == "15" ];then
			imei="$(echo $imei | awk -F ' ' '{print $2}')"
			break
		else
			imei=""
			counter=$(($counter + 1))
			sleep 1
		fi
	done
	debug_echo "imei is $imei"
	
	counter=1
	while [ $counter -le $num ]
	do
		cops="$(comgt -d /dev/$module_at_usb -s /usr/sbin/anywifi/comgt/$module_type/$module_type.chat.cops)"
		ret="$(echo $cops | awk -F '"' '{print $2}')"
		if [ "$ret" == "" -o "$(echo $ret | grep "ERRO" | wc -l)" == "1" ];then
			cops=""
			counter=$(($counter + 1))
			sleep 1
		elif [ "$(echo $ret | grep "460" | wc -l)" == "1" ];then
			cops="$(network_provider $ret)"
			break
		else
			cops="$ret"
			break
		fi
	done
	debug_echo "cops is $cops"

cat > /tmp/4ginfo <<EOF
{
	"device_model":"$module_type",
	"sim_status":"$sim",
	"signal":"$csq",
	"iccid":"$iccid",
	"imsi":"$imsi",
	"imei":"$imei",
	"cops":"${cops}",
}
EOF

	sleep 10
done
