#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2

. /usr/sbin/anywifi/dial_common.sh

get_module_type=$(cat /tmp/mobile_module_name.txt | awk -F ' ' '{print $1}')
get_module_data_usb=$(cat /tmp/mobile_module_name.txt | awk -F ' ' '{print $3}')
get_module_at_usb=$(cat /tmp/mobile_module_name.txt | awk -F ' ' '{print $4}')

network_module_type="$(my_uci_get network.4gwan.module_type)"
usb="$(my_uci_get network.4gwan.device)"
network_module_data_usb="$(echo $usb | awk -F '/' '{print $3}')"

if [ "$get_module_type" != "$network_module_type" ] || [ "$network_module_data_usb" != "$get_module_data_usb" ];then
	debug_echo "$get_module_type reconfig network.4gwan"
        case $get_module_type in                                               
		ec20)
		#uci set network.4gwan.nwscanmode="0"
		uci set network.4gwan.auth='both'
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "ec20 module"
		;;                                                                 
		ec200t)
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.auto='1'
		uci set network.4gwan.dialnumber=""
		uci set network.wan_720.auto='0'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "ec200t module"
		;;                                                                 
		mc2716)
		uci set network.4gwan.nwscanmode="8"
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "mc2716 module"
		;;
		yugecn3)
		#uci set network.4gwan.nwscanmode="38"
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "yugecn3 module"
		;;
		u8300)
		uci set network.4gwan.dialnumber="*99***1#"
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "u8300 module"
		;;
		air720)
		uci set network.4gwan.dialnumber="*99#"
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.auto='0'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "air720 module"
		;;
		KMC-L570)
		uci set network.4gwan.dialnumber="*99#"
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "KMC-L570 module"
		;;
		7600ce)                                                              
		uci set network.4gwan.auth='both'
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.dialnumber="*99#"
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "7600ce module"
		;;                                                                 
		slm790)
		uci set network.4gwan.auth='both'
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.dialnumber="*99#"
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "slm790 module"
		;;                                                                 
		nl668)
		uci set network.4gwan.auth='both'
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.dialnumber="*99#"
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "nl668 module"
		;;                                                                 
		l718)
		uci set network.4gwan.auth='both'
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.dialnumber="*99#"
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "l718 module"
		;;
		l716)
		uci set network.4gwan.auth='both'
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.dialnumber="*99#"
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "l716 module"
		;;
		m8321)                                                              
		uci set network.4gwan.auth='both'
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.dialnumber="*98*1#"
		uci set network.4gwan.auto='1'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "m8321 module"
		;;
		lm9248)                                                              
		uci set network.4gwan='interface'
		uci set network.4gwan.proto='3g'
		uci set network.4gwan.module_type="$get_module_type"
		uci set network.4gwan.device="/dev/$get_module_data_usb"
		debug_echo "lm9248 module"
		;;                                                                 
		*)
		debug_echo "not fount 4g module type"
		#Other Module,Do Nothing
		;;
	esac

	uci commit network

	logger "34G Module Type Change Detected, Reboot To Load! 30 Seconds"
fi

md5_1="$(md5sum /etc/chatscripts/3g.chat | awk '{print $1}')"
md5_2="$(md5sum /usr/sbin/anywifi/modules/$get_module_type.3g.chat | awk '{print $1}')"
if [ "$md5_1" != "$md5_2" ];then
	debug_echo "md5_1 $md5_1 md5_2 $md5_2 is different"
	cp /usr/sbin/anywifi/modules/$get_module_type.3g.chat /etc/chatscripts/3g.chat
fi

if [ "$get_module_type" != lm9248 ];then
	ifdown 4gwan
	sleep 3
	ifup 4gwan
fi
killall_process worker
/usr/sbin/anywifi/comgt/$get_module_type/worker &
debug_echo "/usr/sbin/anywifi/comgt/$get_module_type/worker &"

