#!/bin/sh /etc/rc.common

START=99
start(){
	/usr/sbin/anywifi/ddns/any_ddns_poll.sh &
}

stop(){
	pid_list="$(ps -w | grep -E "any_ddns_poll.sh\b" | grep -v "grep" | awk '{print $1}')"
        for pid_tmp in $pid_list
        do
                kill -9 $pid_tmp
        done
}

