#!/bin/sh /etc/rc.common

START=99
CRONTAB="/etc/crontabs/root"

start() {
	task="*/2 * * * * /usr/sbin/anywifi/BatchAuth&"
	task_check="$(cat "$CRONTAB" | grep "BatchAuth&")"
	if [ -z "$task_check" ];then
		echo "$task" >> $CRONTAB
		/etc/init.d/cron restart
		echo "Task should write into crontabs, and restart the service"
	else
		echo "Task already in crontabs,just quit ... " 1>&2
	fi	
}

start_service(){
	start
}
