#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

START=99
start(){
	[ -z "$(pidof kworker)" ] && kworker&
}
stop(){
	[ "$(pidof kworker)" ] && killall -9 kworker 
}

restart(){
	stop
	sleep 1
	start
}
