#!/bin/sh /etc/rc.common

START=99

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2                                        
        else                            
                echo -n "$(uci get "$1")"
        fi                           
}

server="$(my_uci_get any_mqttd.main.host)"
port="$(my_uci_get any_mqttd.main.port)"
username="$(my_uci_get any_mqttd.main.username)"
password="$(my_uci_get any_mqttd.main.password)"
topic="$(my_uci_get any_mqttd.main.topic)"
subtopic="$(my_uci_get any_mqttd.main.subtopic)"
unixsock="$(my_uci_get any_mqttd.main.unixsock)"
unixudpsock="$(my_uci_get any_mqttd.main.unixudpsock)"
script="$(my_uci_get any_mqttd.main.script)"

start(){
	/usr/sbin/anywifi/crond.d/S99_check_mqtt_server
}

stop(){
	killall -9 any_mqttd
}
