#!/bin/sh /etc/rc.common

START=99

start(){
	if ! uci -q get anyos.sd > /dev/null;then
		DEVPATH_ALL="$(fdisk -l | awk '{if(flag==1){print $1;flag=0}} {if($1=="Device"){flag=1}}')"
		for DEVPATH in $DEVPATH_ALL
		do
			DEVPATH="$DEVPATH" ACTION=add sh /etc/hotplug.d/block/30-usbmount
		done
	fi
}

