#!/usr/bin/perl

require "/lib/core.cgi";

(my $basename = $0) =~ s/^.*\///;
$ENV{'PATH'} = '/bin:/sbin:/usr/bin:/usr/sbin';

$| = 1;

my $cmdlog = '/tmp/cmd.log';
if ($basename eq 'showpid') {
	
    my $pid = shift();
    die "Usage: $basename <pid or cmdline file>\n" if (! $pid);

	if (-e $pid) {
		$_ = &read1line($pid);
        s/\x0/ /g;
        s/\s+$//;
        print $_,"\n";
		exit 0;
	}

	$pid = int($pid);
    die "ERR: PID $pid not exist\n" if (! $pid or ! -e "/proc/$pid");
    if (-e "/proc/$pid/cmdline" and open CMD,'<',"/proc/$pid/cmdline") {
        chomp ($_ = <CMD>); close CMD;
        s/\x0/ /g;
        s/\s+$//;
        print $_,"\n";
    }
    else {
        print "No cmdline found for $pid\n";
    }
	exit 0;
}
open CL,'>',$cmdlog and close CL;

my $timeout = '';
## last arg is timeout
if ($ARGV[scalar@ARGV-1] =~ /^\d+$/) {
	$timeout = pop(@ARGV);	
}

my $cmdline = join(' ',@ARGV);
&_log(&_now() . " got cmdline: X${cmdline}X\n") if (-e '/tmp/dbg.cmd');
foreach (split(/;/,$cmdline)) {
	#print "CMD: $_\n";
	#&_log(&_now() . " exec CMD: $_ ...\n");
	&cmd($_,$timeout);
}
exit 0;


sub cmd {
	my ($func,$arg) = split(/\s+/,shift(),2);
	my $timeout = shift() || 10;
	for ($func) {
		/^set_passwd$/ && do {
			$arg =~ s/"|'//g;
        	$_ = `echo -n '$arg'|busybox md5sum`;
			my $hash = $1 if (/^(\w+)/);
        	$_ = `echo -n $hash|busybox md5sum`;
			$hash = $1 if (/^(\w+)/);
			my $config = &rdconfig('/config');
			$config->{'system'} = {} if (ref $config->{'system'} ne 'HASH');
			$config->{'system'}->{'webadmin_passwd'} = $hash;
			$config->{'system'}->{'webadmin_username'} = 'admin';
			&wtconfig($config,'/config');
			opendir TMP,'/tmp';
			map { unlink "/tmp/$_" } grep { /^token\./ } readdir TMP; closedir TMP;

			&_log2file($cmdlog,"passwd changed success\n");
			last;
		};

        /^report_interval$/ && do {
			my $interval = int($arg);
			$interval = 0 if ($interval < 30 or $interval > 7200);
			if (! $interval) {
				unlink '/etc/config/cmcc_interval';
			}
			else {
				open CL,'>','/etc/config/cmcc_interval' and print CL $interval,"\n" and close CL;
			}
			unlink '/etc/config/cmcc_server';
			system ('/etc/exec/sysinfo init');
			system ('killall yunmgrd');
			&_log2file($cmdlog,"set interval to $interval OK\n");
			last;
        };

		/^(uptime_total|inet_uptime_total)$/ && do {
			my $hf_file = {
				uptime_total => '/etc/config/uptime.total',
				inet_uptime_total => '/etc/config/inet_uptime.total',
			};
			my $v = int($arg);
			if (! $v) {
				&_log2file($cmdlog,"param error\n");
			}
			else {
				my $old = &read1line($hf_file->{ $func });
				open WT,'>',$hf_file->{ $func } and print WT int($old) + $v,"\n" and close WT;
				&_log("Updating $func from $old to $old + $v ...\n");
			}
			last;
		};

		/^nvram$/ && do {
			my ($action,$param)	= split(/\s+/,$arg)	;		
			if ($action !~ /^(get|set|del)$/) {
				&_log2file($cmdlog,"nvram param error\n");
			}
			else {
				&runscript("/etc/exec/mtconfig $action $param",$cmdlog);				
			}
			last;
		};

		/^(enable|disable)/ && do {
			if ($arg !~ /^(yunlogin|hwnat|samba|qos|ssh|telnet|timer_reboot|upnp|wifidog|ntp|ntpd|ddns)$/) {
				&_log2file($cmdlog,"$func param error\n");
				last;
			}

			&runscript("/etc/exec/mtconfig set system.enable_$arg=" . ($func eq 'enable' ? 'yes' : 'no'),$cmdlog);
			#&_log("/etc/exec/mtconfig set system.enable_$arg=" . ($func eq 'enable' ? 'yes' : 'no') . "\n");
			if ($arg =~ /^(ntp|telnet|yunlogin|qos|ssh)/) {
            	open WT,'>','/run/wrtcore' and print WT "$1\n" and close WT;
			}
			elsif ($arg =~ /^(samba|wifidog|ddns)/) {
            	open WT,'>','/run/wrtcore' and print WT "/etc/exec/$1\n" and close WT;
			}
			elsif ($arg eq 'timer_reboot') {
            	open WT,'>','/run/wrtcore' and print WT "task\n" and close WT;
			}
			
			&_log2file($cmdlog,"$func $arg success\n");
			
			last;
		};

        /^alive$/ && do {
			&_log2file($cmdlog,"OK\n");
			last;
        };

        /^reboot$/ && do {
            open WT,'>','/run/wrtcore' and print WT "reboot cmd\n" and close WT;
			&_log2file($cmdlog,"submit reboot action done\n");
			last;
        };

        /^upgrade$/ && do {
            my $url=$arg;
            die "ERR: no url found\n" if (! $url);

			if (&existsPID('/tmp/ug.pid','ug')) {
				&_log2file($cmdlog,"ERR: another upgrade script is running\n");
				last;
			}

			#system ("/etc/exec/ug \"$url\" wait=3 &");
            open WT,'>','/run/wrtcore' and print WT "sleep 3;/etc/exec/ug \"$url\" timeout=300\n" and close WT;
			sleep 3;
			&_log2file($cmdlog,"submit upgrade action done\n");
			last;
		};

		# set_wifi1 <ssid> <hide_ssid> <channel> <band> <encrypt> <key> 
		# set_wifi1 test-826 0 0 0 yes 123456789
		/^set_wifi(\d+)$/ && do {

			my $dev = '';
			## 禁用2.4G 无线
			if ($1 eq 1) {
				$dev = 'wlan0';
			}
			## 禁用5G 无线
			elsif ($1 eq 2) {
				$dev = 'wlan1';
			}

			if (! $dev) {
				&_log2file($cmdlog,"param error\n"); last;
			}

			my $config = &rdconfig('/config');
			$config->{ $dev } = {} if (ref $config->{ $dev } ne 'HASH');
			$config->{ $dev }->{'enable'} = 'yes';

			my ($ssid,$hide_ssid,$channel,$band,$encrypt,$key) = split(/\s+/,$arg);
			$config->{ $dev }->{'ssid'} = $ssid;
			$config->{ $dev }->{'hide_ssid'} = $hide_ssid ? 'yes':'no';
			$config->{ $dev }->{'freq_channel'} = $channel;
			if ($dev eq 'wlan0') {
				$config->{ $dev }->{'freq_htmode'} = $band eq 0 ? 'HT20' : $band eq 1 ? 'HT20+HT40' : 'HT40';
			}
			else {
				$config->{ $dev }->{'freq_htmode'} = $band eq 0 ? 'HT20' : $band eq 1 ? 'HT20+HT40+HT80' : $band eq 2 ? 'HT40' : 'HT80';
			}
			$config->{ $dev }->{'encryption'} = $encrypt eq 'no' ? 'none' : 'psk-mixed';
			$config->{ $dev }->{'wpa_key'} = $key;
			&wtconfig($config,'/config');

            open WT,'>','/run/wrtcore' and print WT "/etc/exec/wifi $dev\n" and close WT;
			&_log2file($cmdlog,"set $dev success\n");
			last;
		};

		## 禁用无线
		/^disable_wifi$/ && do {

			my $dev = '';
			## 禁用2.4G 无线
			if ($arg eq 1) {
				$dev = 'wlan0';
			}
			## 禁用5G 无线
			elsif ($arg eq 2) {
				$dev = 'wlan1';
			}

			if (! $dev) {
				&_log2file($cmdlog,"param error\n"); last;
			}

			my $config = &rdconfig('/config');
			$config->{ $dev } = {} if (ref $config->{ $dev } ne 'HASH');
			if ($config->{ $dev }->{'enable'} ne 'no') {
				$config->{ $dev }->{'enable'} = 'no';
				&wtconfig($config,'/config');
            	open WT,'>','/run/wrtcore' and print WT "/etc/exec/wifi $dev\n" and close WT;
				&_log2file($cmdlog,"disable $dev success\n");
			}
			else {
				&_log2file($cmdlog,"$dev already disabled\n");
			}
			last;
		};

		/^proxy$/ && do {
			symlink '/etc/exec/yunlogin','/etc/exec/proxy' if (! -e '/etc/exec/proxy');
			&runscript("/etc/exec/proxy \"$arg\"",$cmdlog);
			last;
		};

		#print "exec $func $arg ...\n";
		#system ("$func $arg >> $cmdlog");
		system ("timeout -t $timeout $func $arg >> $cmdlog 2>&1");
		#print "done.\n";
		
        #die "ERR: Unknown command\n";
	}
	return;
}

