#!/bin/sh
enabled="$(uci -q get any_dmz.dmz.enabled)"
enabled="$((enabled ^ 0))"
section="$(uci show firewall | awk -F '.' '/firewall.anydmz/ {print $2}')"
if [ -z "$section" ];then
	section="$(uci add firewall include)"
	uci set firewall.${section}.path="/etc/firewall.anydmz"
fi
uci set firewall.${section}.enabled="$enabled"
uci commit firewall
