#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "$0 Already running ..." && return 2

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2
        else
                echo -n "$(uci get "$1")"
        fi
}

killall_process()
{
	local process=$1
	local pid_list=$(ps -ww | grep -w "$process" | grep -v "grep" | awk '{print $1}')
	for pid in $pid_list
	do
		kill -9 $pid
	done
}

. /usr/share/libubox/jshn.sh

server="$(my_uci_get anyos.server.server_mqtt_host)"
port="$(my_uci_get anyos.server.server_mqtt_port)"
username="$(my_uci_get anyos.server.server_mqtt_username)"
password="$(my_uci_get anyos.server.server_mqtt_password)"

flashid="$(cat /proc/flashid)"
if [ -z "$flashid" ];then
	debug_echo "Flashid is empty, fatal error, quit"
	flashid="$(ifconfig br-lan | awk '/HWaddr/{print $5}' | tr -d ':')"
	#exit
fi

lwt_topic="zbtac/${flashid}/put"
debug_echo "lwt_topic:$lwt_topic"

json_init
json_add_string op "offline"
json_add_string device_id $flashid
json_add_string cmd_id '1234'

lwt_content="$(json_dump)"
debug_echo "LWT topic is: $lwt_topic and content is: $lwt_content"

start(){
	ac_switch="$(my_uci_get anyos.cloude_manage.ac_switch)"
	[ "$ac_switch" == 0 ] && debug_echo "ac_switch = 0, Any_mqttd not run" && exit
	if [ -z "$username" ];then
		debug_echo "Start any_mqttd"
		any_mqttd --script /usr/sbin/anywifi/anyos/mqtt_callback \
			--onconnect /usr/sbin/anywifi/anyos/mqtt_event_onconnect \
			--willtopic "${lwt_topic}" --willpayload "${lwt_content}" \
			--host ${server} -p ${port} -t zbtac/${flashid}/put \
			--subtopic zbtac/${flashid}/get --unixsock /tmp/anyos_tcp \
			--unixudpsock /tmp/anyos_udp --daemon

		if [ $? = "0" ];then
			debug_echo "Start any_mqttd success"
		else
			debug_echo "Start any_mqttd failed"
		fi
	else
		debug_echo "Start any_mqttd"
		any_mqttd --username $username --password $password --script /usr/sbin/anywifi/anyos/mqtt_callback \
			--onconnect /usr/sbin/anywifi/anyos/mqtt_event_onconnect \
			--willtopic "${lwt_topic}" --willpayload "${lwt_content}" \
			--host ${server} -p ${port} -t zbtac/${flashid}/put \
			--subtopic zbtac/${flashid}/get --unixsock /tmp/anyos_tcp \
			--unixudpsock /tmp/anyos_udp --daemon

		if [ $? = "0" ];then
			debug_echo "Start any_mqttd success"
		else
			debug_echo "Start any_mqttd failed"
		fi
	fi
}

stop(){
	killall_process any_mqttd >/dev/null 2>&1
}

ac_switch="$(my_uci_get anyos.cloude_manage.ac_switch)"
[ "$ac_switch" == 0 ] && stop

pid="$(pidof any_mqttd)"

if [ -z "$pid" ];then
	debug_echo "Any_mqttd should run but not run, start it"
	start
else
	debug_echo "Any_mqttd Should run and run,do nothing"
fi
