#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2
 
debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message";fi }
 
my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2                                    
        else                        
                echo -n "$(uci get "$1")"
        fi                       
}

####

#anyos.cloud_weblogin.status
#anyos.cloud_weblogin.login_id
#anyos.cloud_weblogin.switch

switch="$(my_uci_get anyos.cloud_weblogin.switch)"
if [ "$switch" != "1" ];then
	debug_echo "cloud web login switch is off"
	if [ -n "$(pidof ngrokc)" ];then	
		debug_echo "ngrokc is running ,kill it"
		killall ngrokc
	fi
fi

login_id_uci="$(my_uci_get anyos.cloud_weblogin.login_id)"
if [ -z "$login_id_uci" ];then
	debug_echo "Start to init ngrokc id"
	macaddr="$(ifconfig eth0 | awk '/HWaddr/{print $5}' | tr  "A-Z" "a-z" | tr -d :)"
	random_id="$(cat /dev/urandom | head -c 10 | md5sum | head -c 6)"
	login_id="${macaddr}${random_id}"
	debug_echo "New ngrokc ID is: $login_id"
	uci set anyos.cloud_weblogin.login_id=${login_id}
else
	debug_echo "ngrokc ID is already initialized"
fi

if [ -z "$(pidof ngrokc)" -a "$switch" == "1" ];then
	debug_echo "Ngrokc is not start, start it"
	login_id="$(my_uci_get anyos.cloud_weblogin.login_id)"
	ngrokc_host="$(my_uci_get anyos.cloud_weblogin.ngrokc_host)"
	ngrokc_port="$(my_uci_get anyos.cloud_weblogin.ngrokc_port)"
	if [ -n "$ngrokc_host" -a -n "$ngrokc_port" ];then
		ngrokc -SER[Shost:${ngrokc_host},Sport:${ngrokc_port},Atoken:${login_id},Password:xxx] -AddTun[Type:http,Lhost:127.0.0.1,Lport:80,Sdname:${login_id}] &
		echo $(cat /proc/uptime | awk -F '.' '{print $1}') > /tmp/ngrokc_timestamp
	else
		ngrokc -SER[Shost:os.ac-link.com,Sport:4443,Atoken:${login_id},Password:xxx] -AddTun[Type:http,Lhost:127.0.0.1,Lport:80,Sdname:${login_id}] &
		echo $(cat /proc/uptime | awk -F '.' '{print $1}') > /tmp/ngrokc_timestamp
	fi
else
	debug_echo "Ngrockc is already initialized"
fi

if [ -n "$(pidof ngrokc)" ];then
	debug_echo "ngrokc is ok"
	uci set anyos.cloud_weblogin.status=1
else
	debug_echo "Ngrokc is  down"
	uci set anyos.cloud_weblogin.status=0
fi
uci commit anyos
