#!/bin/sh                                                                          
if [ -e "/var/run/${0##*/}.pid" ] ;then
	if [ -e "/proc/$(cat /var/run/${0##*/}.pid)" ];then
		echo "${0##*/} is already running"
		return 2
	fi
fi
echo "$$" > /var/run/${0##*/}.pid

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

. /usr/sbin/anywifi/anyos/uplink_interface

pid="$(pidof any_mqttd)"

if [ -z "$pid" ];then
	debug_echo "Any_mqttd should run but not run, anyac wait to next cycle"
	exit
fi
	debug_echo "Any_mqttd Should run and run,anyac begin uploading"
	[ -n "$(uci -q get anyos.rest_accept)" ] || reset_api
	status
	if [ ! -f "/tmp/ac_mqtt_lock" ];then
		online
		reportOwnship
		reportNgrokId
		[ -n "$(uci -q get anyos.rest_accept)" ] && touch /tmp/ac_mqtt_lock 
	fi
	heartbeat
	flow
#	log
