#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "$0 Already running ..." && return 2
 
debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2
        else
                echo -n "$(uci get "$1")"
        fi
}

[ -e /tmp/ngrokc_timestamp ] && ngrokc_timestamp="$(cat /tmp/ngrokc_timestamp)"
current_times="$(cat /proc/uptime | awk -F '.' '{print $1}')"

times="$((current_times - ngrokc_timestamp))"
if [ "$times" -gt 3600 ] && [ -e /tmp/ngrokc_timestamp ];then
	debug_echo "ngrokc link moro than 3600s, link ${times}s,stop it"
	uci set anyos.cloud_weblogin.status=0
	uci set anyos.cloud_weblogin.switch=0
	uci commit anyos
	if [ -e /usr/sbin/anywifi/anyos/uplink_interface ];
		. /usr/sbin/anywifi/anyos/uplink_interface
		reportNgrokId
	fi
	pid_list=$(ps -ww | grep -w "ngrokc" | grep -v "grep" | awk '{print $1}')
	for pid in $pid_list
	do
		kill -9 $pid
	done
else
	debug_echo "ngrokc link does not have 3600s,do nothing"
fi
