#!/bin/sh
if [ -e "/var/run/${0##*/}.pid" ] ;then
	if [ -e "/proc/$(cat /var/run/${0##*/}.pid)" ];then
		echo "${0##*/} is already running"
		return 2
	fi
fi
echo "$$" > /var/run/${0##*/}.pid

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2                                        
        else                            
                echo -n "$(uci get "$1")"
        fi                           
}

wifi_interface=ra0
wifi_device=mt7620

start(){
	while [ -f /tmp/site_survey_lock ];do
		sleep 6
	done
	iwpriv $wifi_interface set SiteSurvey=
	sleep 6
	if [ "$wifi_device" == mt7663 ];then
		iw_date="$(iwpriv $wifi_interface get_site_survey | sed '1,3d' | sed '$d'| awk '{$1="";print $0}')"
	else
		iw_date="$(iwpriv $wifi_interface get_site_survey | sed '1,2d' | sed '$d')"
	fi
	channel="$(my_uci_get wireless.${wifi_device}.channel)"
	if [ "$channel" == "undefined" ];then
		channel=0
	fi
	ssid="$(my_uci_get wireless.default_radio0.ApCliSsid)"
	bssid="$(my_uci_get wireless.default_radio0.ApCliBssid)"
	if [ -n "$bssid" ];then
		channel_superior="$(echo "$iw_date" | grep "$bssid" | awk '{print $1}')"
	elif [  -n "$ssid" ];then
		channel_superior="$(echo "$iw_date" | grep "$ssid" | awk '{print $1}')"
	else
		channel_superior="$channel"
	fi
	if [ -n "$channel_superior" ] && [ "$channel" != "$channel_superior" ];then
		uci -q set wireless.${wifi_device}.channel="$channel_superior"
		uci commit wireless
		(/etc/init.d/network restart) &
	fi
	debug_echo "ssid=$ssid bssid=$bssid channel_superior=$channel_superior channel=$channel"
}

if [ "$(my_uci_get wireless.default_radio0.ApCliEnable)" == 1 ];then
	start
fi
