#!/bin/sh
if [ -e "/var/run/${0##*/}.pid" ] ;then
	if [ -e "/proc/$(cat /var/run/${0##*/}.pid)" ];then
		echo "${0##*/} is already running"
		return 2
	fi
fi
echo "$$" > /var/run/${0##*/}.pid

debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

dir_name="/usr/sbin/anywifi/crond.d/"
uptime="$(cat /proc/uptime | awk -F. '{print $1}')"
debug_echo "#Any_crond: now sys uptime is: $uptime"
random_cnt="$(grep -m1 -o '[0-5][0-9]' /dev/urandom | head -n 1)"
random_cnt_judge="$(echo $random_cnt | grep -o '0[0-9]')"
[ -n $random_cnt_judge ] && random_cnt="$(echo $random_cnt | tr -d 0)"
[ -n $random_cnt ] || random_cnt=1

for filename_fullpath in $dir_name/* ;do
	filename="${filename_fullpath##*/}"
	suffix="$(echo "$filename" | grep '__')"

	if [ -z "$suffix" ];then
		debug_echo "#Any_crond : $filename has no __ treat as 1"
		itv=1
	else
		itv=${filename##*__}
		debug_echo "#Any_crond: $filename has suffix and it's $itv"
	fi

	mod=$((uptime%(itv*60)))

	if [ "$mod" -lt 60 ];then
		random_time="$((random_cnt * itv))"
		debug_echo "#Any_crond : mod is $mod, $filename hit,run it"
		debug_echo "random_time : $random_time,itv=$itv"
		(sleep $random_time;$filename_fullpath) &
	else
		debug_echo "#Any_crond : mod is $mod, $filename not hit, skip"
	fi
done
