#!/bin/sh
if [ -e "/var/run/${0##*/}.pid" ] ;then
	if [ -e "/proc/$(cat /var/run/${0##*/}.pid)" ];then
		echo "${0##*/} is already running"
		return 2
	fi
fi
echo "$$" > /var/run/${0##*/}.pid


debug=$(echo $@ | grep "\-\-debug" | wc -l)
debug_echo(){ if [[ "$debug" == "1" ]];then message="$(date +%s) $1"; echo "$message" 1>&2; logger "$message" >/dev/null 2>&1;fi }

my_uci_get(){
        if [ "$(uci get "$1" 2>&1 | grep "Entry not found" | wc -l)" == "1" ];then
                debug_echo "$1 not found"  1>&2
        else
                echo -n "$(uci get "$1")"
        fi
}

network_provider(){

	network_provider="$1"

	case $network_provider in
	46001)
		network_provider="China Unicom (46001)"
	;;
	46006)
		network_provider="China Unicom (46006)"
	;;
	46000)
		network_provider="China Mobile (46000)"
	;;
	46002)
		network_provider="China Mobile (46002)"
	;;
	46007)
		network_provider="China Mobile (46007)"
	;;
	46020)
		network_provider="China Mobile (46020)"
	;;
	46003)
		network_provider="China Telecom (46003)"
	;;
	46005)
		network_provider="China Telecom (46005)"
	;;
	46011)
		network_provider="China Telecom (46011)"
	;;
	esac
	echo -n "$network_provider"
}

. /usr/share/libubox/jshn.sh
[ ! -d /tmp/anyos ] && mkdir /tmp/anyos

trigger_count=5
while [ "$trigger_count" -ge "1" ]
do
# get_system_status
	UPTIME="$(cat /proc/uptime | awk -F '.' '{print $1}')"
	LOAD_AVG="$(uptime | awk -F 'average:' '{print $2}' | sed 's/^[ \t]*//g' | awk -F ',' '{print $1 $2 $3}')"
	CPU_USAGE="$((100 - $(top -n 1 | grep 'idle' | grep -v "grep" | awk '{print $8}' | awk -F '%' '{print $1}')))"

	MEM_TOTAL="$(cat /proc/meminfo | grep MemTotal | awk '{print $2}')" #KB
	MEM_FREE="$(cat /proc/meminfo | grep MemFree | awk '{print $2}')"   #KB
	MEMORY_USAGE="$(printf "%d" $((100-MEM_FREE*100/MEM_TOTAL)))"

	wifi_device_table="$(my_uci_get anyos.wifi.device_table)"
	online_user_num=0
	usernum1=0
	usernum2=0
	if [ "$wifi_device_table" != "0" ];then
		# MTK use
		wifi2_ifname="$(my_uci_get anyos.wifi.wifi2_ifname | awk '{print $1}')"
		wifi5_ifname="$(my_uci_get anyos.wifi.wifi5_ifname | awk '{print $1}')"
		wifi2_ifname="$(ifconfig | grep -wo "$wifi2_ifname")"
		wifi5_ifname="$(ifconfig | grep -wo "$wifi5_ifname")"
		model=$(cat /proc/cpuinfo | grep -oi Qualcomm)
		if [ "$model" == "Qualcomm" ];then
			[ "$wifi2_ifname" != "" ] && usernum1="$(iwinfo $wifi2_ifname assoclist | grep dBm | grep -v "00:00:00:00:00:00"  | grep -v "grep" | wc -l)"
			[ "$wifi5_ifname" != "" ] && usernum2="$(iwinfo $wifi5_ifname assoclist | grep dBm | grep -v "00:00:00:00:00:00"  | grep -v "grep" | wc -l)"
		else
			[ "$wifi2_ifname" != "" ] && usernum1="$(iwpriv $wifi2_ifname get_mac_table | sed '1,2d' | sed '$d' | wc -l)"
			[ "$wifi5_ifname" != "" ] && usernum2="$(iwpriv $wifi5_ifname get_mac_table | sed '1,2d' | sed '$d' | wc -l)"
		fi

		online_user_num="$((usernum1 + usernum2))"
		debug_echo "usernum1 $usernum1 usernum2 $usernum2 online_user_num $online_user_num"
	fi

# get_network_topology
	wifi2="$(my_uci_get anyos.wifi.wifi2_ifname)"
	[ ! -z "$wifi2" ] && wifi2=1
	wifi5="$(my_uci_get anyos.wifi.wifi5_ifname)"
	[ ! -z "$wifi5" ] && wifi5=1

	wan_ifname="$(my_uci_get network.wan.ifname)"

	net_status="none"
	[ -f "/tmp/netstat.txt" ] && net_status="$(cat /tmp/netstat.txt)"
	if [ "$net_status" == "none" ];then
		internet_interface=none
	elif [ "$net_status" == "$wan_ifname" -o "$net_status" == "pppoe-wan" -o "$net_status" == "pptp-pptp" -o "$net_status" == "l2tp-l2tp" ];then
		internet_interface=ether
		if [ "$net_status" == "pppoe-wan" ];then
			wan_status="pppoe"
		else
			wan_status="$(my_uci_get network.wan.proto)"
		fi
	elif [ "$net_status" == "apcli0" ];then
		internet_interface=wifi
	else
		internet_interface=4g
	fi
	debug_echo "internet_interface $internet_interface"
	port_order="$(my_uci_get anyos.network.port_order)"
	wan_type="$(my_uci_get anyos.network.wan_type)"
	port_wan="$(my_uci_get anyos.network.port_wan)"
	swconfig_info="$(swconfig dev switch0 show)"
	
	port_stat=""
	for port_cell in $port_order
	do
		if [ "$port_cell" != "w" ];then
			lan_cell="$(echo "$port_cell" | tr -d [0-9])"
                        if [ -z "$lan_cell" ];then
                                if [ -z "$(echo "$swconfig_info" | grep "link: port:${port_cell} link:up")" ];then
                                        port_stat="$port_stat 0"
                                else
                                        port_stat="$port_stat 1"
                                fi
                        else
                                if [ -z "$(ip link | grep -w "$port_cell" | grep "state UP")" ];then
                                        port_stat="$port_stat 0"
                                else
                                        port_stat="$port_stat 1"
                                fi
                        fi
		elif [ "$port_cell" == "w" ];then
			if [ "$wan_type" == "switch" ];then
				if [ -z "$(echo "$swconfig_info" | grep "link: port:${port_wan} link:up")" ];then
					port_stat="$port_stat 0"
				else
					port_stat="$port_stat 1"
				fi
			elif [ "$wan_type" == "link" ];then
				if [ -z "$(ip link | grep -w "$wan_ifname" | grep "state UP")" ];then
					port_stat="$port_stat 0"
				else
					port_stat="$port_stat 1"
				fi
			fi
		fi
	done
	debug_echo "port_order $port_order port_stat $port_stat"

# get_lan_config
	lan_proto="$(my_uci_get network.lan.proto)"
	LAN_IPADDR="$(my_uci_get network.lan.ipaddr)"
	[ -z "$LAN_IPADDR" ] && LAN_IPADDR="0.0.0.0"
	LAN_NETMASK="$(my_uci_get network.lan.netmask)"
	LAN_MACADDR="$(cat /sys/class/net/br-lan/address | tr 'a-z' 'A-Z')"
	[ -z "$LAN_MACADDR" ] && LAN_MACADDR="00:00:00:00:00:00"

	lan_ubus_data="$(ubus call network.interface.lan status)"
	json_load "$lan_ubus_data"
	json_get_var LAN_UPTIME uptime


# get_wan_config
	wan_macaddr="$(ifconfig "$wan_ifname" | awk '/HWaddr/{print $5}')"
	wan_proto="$(my_uci_get network.wan.proto)"
	[ "$wan_proto" == "pppoe" ] && wan_ifname="pppoe-wan"

	wan_ubus_data="$(ubus call network.interface.wan status)"
	json_load "$wan_ubus_data"
	json_get_var WAN_UPTIME uptime

	wan_ifconfig="$(ifconfig "$wan_ifname")"
	wan_gateway="$(route -n | grep "UG" | grep -w "$wan_ifname" | awk 'NR==1 {print $2}')"

	disable_ipv6="$(sysctl net.ipv6.conf.all.disable_ipv6 | awk '{print $3}')"
	disable_ipv6="$((disable_ipv6 ^ 0))"
	if [ "$disable_ipv6" == 0 ];then
		wan_nameserver="$(awk -v "print_sign=0" '{if(NF==3){if($3=="wan" || $3=="wan6"){print_sign=1}else{print_sign=0}} if($1=="nameserver" && print_sign==1){print $2}}' /tmp/resolv.conf.auto)"
	else
		wan_nameserver="$(awk -v "print_sign=0" '{if(NF==3){if($3=="wan"){print_sign=1}else{print_sign=0}} if($1=="nameserver" && print_sign==1){print $2}}' /tmp/resolv.conf.auto)"
	fi

	dns_primary="$(my_uci_get network.wan.dns | awk -F ' ' '{print $1}')"
	dns_secondary="$(my_uci_get network.wan.dns | awk -F ' ' '{print $2}')"

	wan_ipaddr="$(echo "$wan_ifconfig" | grep "inet addr:" | awk -F ":" '{print $2}' | awk '{print $1}')"
	wan_netmask="$(echo "$wan_ifconfig" | grep "inet addr:" | awk -F "Mask:" '{print $2}')"

	if [ "$wan_proto" == "static" ]; then
		wan_ipaddr="$(my_uci_get network.wan.ipaddr)"
		wan_netmask="$(my_uci_get network.wan.netmask)"
		wan_gateway="$(my_uci_get network.wan.gateway)"
	elif [ "$wan_proto" == "dhcp" ];then
		wan_ip="$(echo "$wan_ifconfig" | grep 'inet addr' | wc -l)"
		if [ "$wan_ip" != "1" ]; then
			wan_ipaddr="0.0.0.0"
			wan_netmask="255.255.255.0"
		fi
	elif [ "$wan_proto" == "pppoe" ]; then
		wan_username="$(my_uci_get network.wan.username)"
		wan_password="$(my_uci_get network.wan.password)"
	fi

# get_wan_traffic
	timestamp_current="$(date +%s)"
	traffic_now="$(cat /proc/net/dev)"
	wan_ifname="$(my_uci_get network.wan.ifname)"
	wan_proto="$(my_uci_get network.wan.proto)"
	[ "$wan_proto" == "pppoe" ] && wan_ifname="pppoe-wan"
	[ -z "$wan_ifname" ] && wan_ifname=NO_IFNAME
	# 参数清零
	module_rx_current=0
	module_tx_current=0
	if [ -f /etc/config/netcard_db ];then
	#多模块流量累计
		#获取模块流量数据列表数据
		module_section_traffic_list="$(cat /tmp/anyos/module_section_traffic_list)"
		#清零列表
		echo "" > /tmp/anyos/module_section_traffic_list
		module_section_list="$(uci show network | sed -n 's/network.\(4gwan[0-9]*\)\+=interface/\1/p')"
		for module_section in $module_section_list
		do
			#找出模块当前的接口模式
			module_proto="$(my_uci_get network.${module_section}.proto)"
			module_ifname="$(my_uci_get network.${module_section}.ifname)"
			[ "$module_proto" == "3g" ] && module_ifname="3g-${module_section}"
			[ "$module_ifname" == "" ] && module_ifname=NO_IFNAME
			debug_echo "module_section=$module_section module_ifname=$module_ifname"
			#根据接口名找出上下行流量，并记录
			module_section_rx_current="$(echo "$traffic_now" | grep -w "$module_ifname" | awk '{print $2}')"
			module_section_tx_current="$(echo "$traffic_now" | grep -w "$module_ifname" | awk '{print $10}')"
			echo "${module_ifname}_rx_old = $module_section_rx_current" >> /tmp/anyos/module_section_traffic_list
			echo "${module_ifname}_tx_old = $module_section_tx_current" >> /tmp/anyos/module_section_traffic_list
			#和上一次记录求差值
			module_section_rx_old="$(echo "$module_section_traffic_list" | grep -w "${module_ifname}_rx_old" | awk '{print $3}')"
			module_section_tx_old="$(echo "$module_section_traffic_list" | grep -w "${module_ifname}_tx_old" | awk '{print $3}')"
			module_section_rx_diff="$((module_section_rx_current-module_section_rx_old))"
			module_section_tx_diff="$((module_section_tx_current-module_section_tx_old))"
			if [ "$module_section_rx_diff" -lt 0 -o "$module_section_tx_diff" -lt 0 ];then
				module_rx_current="$((module_rx_current + module_section_rx_current))"
				module_tx_current="$((module_tx_current + module_section_tx_current))"
			else
				module_rx_current="$((module_rx_current + module_section_rx_diff))"
				module_tx_current="$((module_tx_current + module_section_tx_diff))"
			fi
			debug_echo "module_section_rx_diff=$module_section_rx_diff module_rx_current=$module_rx_current"
			debug_echo "module_section_tx_diff=$module_section_tx_diff module_tx_current=$module_tx_current"
		done
	else
	#单模块统计流量
		module_proto="$(my_uci_get network.4gwan.proto)"
		if [ "$module_proto" == "3g" ];then
			module_interface="3g-4gwan"
		else
			module_ifname="$(my_uci_get network.4gwan.ifname)"
			module_interface="$module_ifname"
		fi
		[ "$module_interface" == "" ] && module_interface=NO_IFNAME
		debug_echo "module_interface $module_interface"
		module_rx_current="$(echo "$traffic_now" | grep -w "$module_interface" | awk '{print $2}')"
		module_tx_current="$(echo "$traffic_now" | grep -w "$module_interface" | awk '{print $10}')"
	fi

	#wan口统计流量
	wan_rx_current="$(echo "$traffic_now" | grep -w "$wan_ifname" | awk '{print $2}')"
	wan_tx_current="$(echo "$traffic_now" | grep -w "$wan_ifname" | awk '{print $10}')"
	wifi_rx_current="$(echo "$traffic_now"| grep -w "apcli0" | awk '{print $2}')"
	wifi_tx_current="$(echo "$traffic_now"| grep -w "apcli0" | awk '{print $10}')"
	#Content in file
	if [ ! -f /tmp/anyos/get_wan_traffic ];then
		wan_rx_speed=0
		wan_tx_speed=0
		module_rx_speed=0
		module_tx_speed=0
		wifi_rx_speed=0
		wifi_tx_speed=0
	else
		#获取过去流量信息
		. /tmp/anyos/get_wan_traffic
		timestamp_diff="$((timestamp_current-timestamp_old))"
		[ "$timestamp_diff" == "0" ] && timestamp_diff=1
		#计算间隔时间
		wan_rx_diff="$((wan_rx_current-wan_rx_old))"
		wan_tx_diff="$((wan_tx_current-wan_tx_old))"

		module_rx_diff="$((module_rx_current-module_rx_old))"
		module_tx_diff="$((module_tx_current-module_tx_old))"

		wifi_rx_diff="$((wifi_rx_current-wifi_rx_old))"
		wifi_tx_diff="$((wifi_tx_current-wifi_tx_old))"
		#计算速度
		wan_rx_speed=$((wan_rx_diff/timestamp_diff))
		wan_tx_speed=$((wan_tx_diff/timestamp_diff))

		module_rx_speed=$((module_rx_diff/timestamp_diff))
		module_tx_speed=$((module_tx_diff/timestamp_diff))

		wifi_rx_speed=$((wifi_rx_diff/timestamp_diff))
		wifi_tx_speed=$((wifi_tx_diff/timestamp_diff))

		#过滤错误数值
		if [ -z "$wan_rx_speed" ] || [ "$wan_rx_speed" -lt "0" ] || [ -z "$wan_tx_speed" ] || [ "$wan_tx_speed" -lt "0" ];then
			wan_tx_speed="0"
			wan_rx_speed="0"
		fi

		if [ -z "$module_rx_speed" ] || [ "$module_rx_speed" -lt "0" ] || [ -z "$module_tx_speed" ] || [ "$module_tx_speed" -lt "0" ];then
			module_rx_speed="0"
			module_tx_speed="0"
		fi

		if [ -z "$wifi_rx_speed" ] || [ "$wifi_rx_speed" -lt "0" ] || [ -z "$wifi_tx_speed" ] || [ "$wifi_tx_speed" -lt "0" ];then
			wifi_rx_speed="0"
			wifi_tx_speed="0"
		fi
	fi

	#get_wan_traffic 接口实际显示当前默认网口流速
	if [ "$internet_interface" == "ether" ];then
		interface_rx_speed="$wan_rx_speed"
		interface_tx_speed="$wan_tx_speed"
	elif [ "$internet_interface" == "4g" ];then
		interface_rx_speed="$module_rx_speed"
		interface_tx_speed="$module_tx_speed"
	elif [ "$internet_interface" == "wifi" ];then
		interface_rx_speed="$wifi_rx_speed"
		interface_tx_speed="$wifi_tx_speed"
	else
		interface_rx_speed=0
		interface_tx_speed=0
	fi

#按格式打印时间戳和各个接口流量信息
echo -e "\
timestamp_old=${timestamp_current}\n\
wan_rx_old=${wan_rx_current}\n\
wan_tx_old=${wan_tx_current}\n\

module_rx_old=${module_rx_current}\n\
module_tx_old=${module_tx_current}\n\

wifi_rx_old=${wifi_rx_current}\n\
wifi_tx_old=${wifi_tx_current}\n\
" \
> /tmp/anyos/get_wan_traffic

# get_web_msg
	board="$(my_uci_get anyversion.device.device_model_displayname)"
	if [ -z "$board" ];then
		board="$(my_uci_get anyversion.device.device_model)"
	fi
	sysversion="$(my_uci_get anyversion.device.device_version)"

	[ -z "$board" ] && board="UNKNOWN"
	[ -z "sysversion" ] && sysversion="0.0"
	systime="$(date "+%Y-%m-%d %H:%M:%S")"
	uptime="$(cat /proc/uptime | awk -F '.' '{print $1}')"
	mode="route"

# get_module_signal
	#取默认路由模块的信息
	if [ "$internet_interface" == "4g" ];then
		debug_echo "net_status=$net_status"
		internet_interface_judge="$(echo "$net_status" | sed -n 's/3g-4gwan\([0-9]\+\).*/\1/p')"
		if [ -z "$internet_interface_judge" ];then
			#net_status 为注册接口类型名字 例:usb0
			#4gwanx对应4ginfox 取对应4ginfo 
			module_data_name="4ginfo$(uci show network | sed -n 's/network.4gwan\([0-9]*\).ifname='\'"$net_status"\''/\1/p')"
		else
			#net_status 为3g-4gwanx 类型名字
			#4gwanx对应4ginfox 取对应4ginfo 
			module_data_name="4ginfo${internet_interface_judge}"
		fi
		debug_echo "module_data_name = $module_data_name"
		if [ -f "/tmp/${module_data_name}" ];then
			model_date="$(cat /tmp/${module_data_name})"
		fi
		module_ipaddr="$(ifconfig "$net_status" | grep "inet addr:" | awk -F ":" '{print $2}' | awk '{print $1}')"
		debug_echo "model_date :$model_date"
		if [ -f /etc/config/netcard_db ];then
		#多模块获取
			if [ -n "$model_date" ];then
				json_load "$model_date"
				json_get_var operator cops
				json_get_var model device_model
				json_get_var imei imei
				json_get_var signal signal
				json_get_var iccid iccid
			fi
		else
		#单模块获取
			operator="$(echo "$model_date" | grep cops | awk -F '"' '{print $4}')"
			model="$(echo "$model_date" | grep device_model | awk -F '"' '{print $4}')"
			imei="$(echo "$model_date" | grep imei | awk -F '"' '{print $4}')"
			signal="$(echo "$model_date" | grep signal | awk -F '"' '{print $4}')"
			iccid="$(echo "$model_date" | grep iccid | awk -F '"' '{print $4}')"
		fi

		operator="$(network_provider "$operator")"
		debug_echo "operator=$operator"
		[ "$iccid" == "00000000000000000000" ] && iccid="NO SIM"
	fi

# getWiFi2
	if [ "$wifi2" == 1 ];then
		wifi2_device="$(my_uci_get anyos.wifi.wifi2_device)"
		wifi2_disabled="$(my_uci_get wireless.${wifi2_device}.disabled)"
		if [ "$wifi2_disabled" != "1" ];then
			wifi2_enabled="1"
		else
			wifi2_enabled="0"
		fi
		wifi2_iface=default_radio0
		wifi2_ifname="$(my_uci_get wireless.${wifi2_iface}.ifname)"
		[ "$wifi2_ifname" == "" ] && wifi2_ifname="$(my_uci_get anyos.wifi.wifi2_ifname | awk '{print $1}')"
		[ "$wifi2_ifname" == "" ] && wifi2_ifname="ath0"

		ssid2="$(my_uci_get wireless.${wifi2_iface}.ssid)"
		encryption2="$(my_uci_get wireless.${wifi2_iface}.encryption)"
		case $encryption2 in
			psk2+ccmp)
				encryption2="WPA2(AES)"
				;;
			psk-mixed)
				encryption2="WPA/WPA2"
				;;
			*)
				encryption2="none"
				;;
		esac
		wifi2_ifname="$(ifconfig | grep -wo "$wifi2_ifname")"
		channel2=0
		[ "$wifi2_ifname" != "" ] && channel2="$(iwinfo "$wifi2_ifname" info | grep -w "Channel:" | awk '{print $4}')"
		debug_echo "channel2 $channel2"

		bssid2="$(my_uci_get wireless.${wifi2_iface}.macaddr)"
		if [ "$bssid2" == "" ];then
			bssid2="$(cat /sys/class/net/${wifi2_ifname}/address)"
		fi

		guest_ssid2="$(my_uci_get wireless.guest_wifi.ssid)"
	fi
# getWiFi5
	if [ "$wifi5" == 1 ];then
		wifi5_device="$(my_uci_get anyos.wifi.wifi5_device)"
		wifi5_disabled="$(my_uci_get wireless.${wifi5_device}.disabled)"
		if [ "$wifi5_disabled" != "1" ];then
			wifi5_enabled="1"
		else
			wifi5_enabled="0"
		fi
		wifi5_iface=default_radio1
		wifi5_ifname="$(my_uci_get wireless.${wifi5_iface}.ifname)"
		[ "$wifi5_ifname" == "" ] && wifi5_ifname="$(my_uci_get anyos.wifi.wifi5_ifname | awk '{print $1}')"
		[ "$wifi5_ifname" == "" ] && wifi5_ifname="ath1"

		ssid5="$(my_uci_get wireless.${wifi5_iface}.ssid)"
		encryption5="$(my_uci_get wireless.${wifi5_iface}.encryption)"
		case $encryption5 in
			psk2+ccmp)
				encryption5="WPA2(AES)"
				;;
			psk-mixed)
				encryption5="WPA/WPA2"
				;;
			*)
				encryption5="none"
				;;
		esac
		wifi5_ifname="$(ifconfig | grep -wo "$wifi5_ifname")"
		channel5=0
		[ "$wifi5_ifname" != "" ] && channel5="$(iwinfo "$wifi5_ifname" info | grep -w "Channel:" | awk '{print $4}')"
		debug_echo "channel5 $channel5"

		bssid5="$(my_uci_get wireless.${wifi5_iface}.macaddr)"
		if [ "$bssid5" == "" ];then
			bssid5="$(cat /sys/class/net/${wifi5_ifname}/address)"
		fi

		guest_ssid5="$(my_uci_get wireless.guest_wifi1.ssid)"
	fi
#get_wifi_apclient_config
	wifi_enabled="$(my_uci_get wireless.default_radio0.ApCliEnable)"
	wifi_enabled="$((wifi_enabled ^ 0))"
	if [ "$wifi_enabled" == 1 ];then
	apclient_ifconfig="$(ifconfig apcli0)"
	apclient_bssid="$(echo "$apclient_ifconfig" | awk '/HWaddr/{print $5}')"
	apclient_ip="$(echo "$apclient_ifconfig" | grep "inet addr" | awk -F ':' '{print $2}' | awk '{print $1}')"
	apclient_netmask="$(echo "$apclient_ifconfig" | grep "inet addr:" | awk -F "Mask:" '{print $2}')"
	apclient_wifiname="$(iwconfig apcli0 | awk -F 'ESSID:' '/ESSID:/{print $2}' | tr -d '" ')"
	fi
	apclient_gateway="$(route -n | grep -w "UG" | grep -w "apcli0" | awk 'NR==1 {print $2}')"
	apclient_nameserver="$(cat /tmp/resolv.conf.auto | grep -A 1 -w "wwan" | awk 'NR==2 {print $2}')"


##################################################################

get_system_status(){
	json_add_string code "1"
	json_add_string reason "get system status success"
	json_add_string uptime "$UPTIME"
	json_add_string load_avg "$LOAD_AVG"
	json_add_string cpu_usage "$CPU_USAGE"
	json_add_string memory_usage "$MEMORY_USAGE"
	json_add_string online_user_num "$online_user_num"
}

get_network_topology(){
	json_add_string code "1"
	json_add_string reason "get status success"
	json_add_string internet "$internet_interface"
	json_add_string lan "1"
	json_add_string wifi2 "$wifi2"
	json_add_string wifi5 "$wifi5"
	json_add_string wan_status "$wan_status"

	json_add_array "port"
	for port_one in $port_stat
	do
		json_add_object
		json_add_string status "$port_one"
		json_close_object
	done
	json_close_array
}
	
get_wan_config(){
	json_add_object "data"
	if [ "$proto" == "pppoe" ]; then
		json_add_string username "$wan_username"
		json_add_string password "$wan_password"
	fi
	json_add_string proto "$wan_proto"
	json_add_string macaddr "$wan_macaddr"
	json_add_string dns_primary "$dns_primary"
	json_add_string dns_secondary "$dns_secondary"
	json_add_string ipaddr "$wan_ipaddr"
	json_add_string netmask "$wan_netmask"
	json_add_string gateway "$wan_gateway"
	json_add_string nameserver "$wan_nameserver"
	json_close_object
}

get_lan_config(){
	json_add_string code "1"
	json_add_string reason "get lan config success"

	json_add_object "data"
	json_add_string proto "$lan_proto"
	json_add_string ipaddr "$LAN_IPADDR"
	json_add_string netmask "$LAN_NETMASK"
	json_add_string macaddr "$LAN_MACADDR"
	json_close_object
}

get_wan_traffic(){
	json_add_string code "1"
	json_add_string reason "success"
	json_add_string rx "$interface_rx_speed"
	json_add_string tx "$interface_tx_speed"
}

get_module_signal(){
	if [ -f "/tmp/${module_data_name}" ];then
		json_add_string code "1"
		json_add_string reason "get module signal success"
		json_add_array "data"
		json_add_object
		json_add_string operator "$operator"
		json_add_string model "$model"
		json_add_string imei "$imei"
		json_add_string iccid "$iccid"
		json_add_string signal "$signal"
		json_add_string ipaddr "$module_ipaddr"
		json_close_object
		json_close_array
	else
		json_add_string code "4"
		json_add_string reason "get module signal fail"
	fi
}

getWiFi2(){
	json_add_string ssid "$ssid2"
	json_add_string encryption "$encryption2"
	json_add_string channel "$channel2"
	json_add_string bssid "$bssid2"
	json_add_string guest_ssid "$guest_ssid2"
	json_add_string wifi2_enabled "$wifi2_enabled"
}

getWiFi5(){
	json_add_string ssid "$ssid5"
	json_add_string encryption "$encryption5"
	json_add_string channel "$channel5"
	json_add_string bssid "$bssid5"
	json_add_string guest_ssid "$guest_ssid5"
	json_add_string wifi5_enabled "$wifi5_enabled"
}

get_web_msg(){
	json_add_string code "1"
	json_add_string reason "get web msg success"

	json_add_object "data"
	json_add_string board "$board"
	json_add_string sysversion "$sysversion"
	json_add_string macaddr "$LAN_MACADDR"
	json_add_string ipaddr "$LAN_IPADDR"
	json_add_string mode "$mode"
	json_add_string systime "$systime"
	json_add_string uptime "$UPTIME"
	json_add_string authcode "$(cat /proc/authmode)"
	json_close_object
}

get_wifi_apclient_config (){
	json_add_string apclient_bssid "$apclient_bssid"
	json_add_string apclient_ip "$apclient_ip"
	json_add_string apclient_netmask "$apclient_netmask"
	json_add_string apclient_gateway "$apclient_gateway"
	json_add_string apclient_nameserver "$apclient_nameserver"
	json_add_string apclient_wifiname "$apclient_wifiname"
}

json_self_add_object(){
	json_add_object $1
	$1
	json_close_object
}

json_init
json_add_object "home"
json_self_add_object get_system_status
json_self_add_object get_network_topology
json_self_add_object get_wan_config
json_self_add_object get_lan_config
json_self_add_object get_wan_traffic
json_self_add_object get_module_signal
json_self_add_object getWiFi2
json_self_add_object getWiFi5
json_self_add_object get_web_msg
json_self_add_object get_wifi_apclient_config
json_close_object

echo -n "$(json_dump)" > /tmp/anyos/home_json

sleep 2
	trigger_count="$((trigger_count - 1))"
done

