#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2

. /usr/sbin/anywifi/dial_common.sh

atdev="/dev/$(awk -F ' ' '{print $4}' /tmp/mobile_module_name.txt)"
ifname=""
section="4gwan"

#写配置
config()
{
	uci set network.${section}.metric=5
	uci set network.wan.metric=3
	uci commit network
}

restart_4g_module(){
	local atdev="$1"
	local section="$2"
	ifdown "$section"
	gpio_4g="$(my_uci_get netcard.device.module_gpio)"
	active="$(my_uci_get netcard.device.active)"
	if [ "$gpio_4g" == "" ];then
		debug_echo "use cfun restart_4g_module"
		at-cmd $atdev at+cfun=1,1
	else
		debug_echo "use gpio restart_4g_module"
		[ -z "$active" ] && active=1
		[ "$active" == "1" ] && value=0
		[ "$active" == "0" ] && value=1
		echo $value > /sys/class/gpio/gpio${gpio_4g}/value
		sleep 5
		echo $active > /sys/class/gpio/gpio${gpio_4g}/value
		sleep 15
	fi
	pid_vid="$(cat /tmp/mobile_module_name.txt | awk '{print $2}')"
	pid_vid_judge="$(lsusb | grep -o "$pid_vid")"
	while [ -z "$pid_vid_judge" ];do
		sleep 5
		pid_vid_judge="$(lsusb | grep -o "$pid_vid")"
	done
	ttyUSB="$(ls /dev/ttyUSB* | wc -l)"
	while [ "$ttyUSB" == "0" ];do
		debug_echo "There is no /dev/ttyUSB*"
		sleep 10
		ttyUSB="$(ls /dev/ttyUSB* | wc -l)"
	done
	ifup "$section"
}

#判断模块配置
set_firewall "$section"
config_judge=0
[ -n "$(uci -q get network.4gwan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ -n "$(uci -q get network.wan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ "$(uci -q get network.wan.metric)" != "$(uci -q get network.4gwan.metric)" ] || config_judge=1
if [ "$config_judge" == 1 ];then
	config
	debug_echo "reate $section network config"
	ifup wan
	ifup "$section"
fi

ping_sh_pid="$(ps -w | grep "/usr/sbin/anywifi/manual_dial/module_ping.sh" | grep -v "grep" | awk '{print $1}')"
if [ -z "$ping_sh_pid" ];then
	/usr/sbin/anywifi/manual_dial/module_ping.sh 3g-4gwan &
fi
trap "restart_4g_module $atdev $section" USR1
first_dial=1
while [ 1 ]
do
	ttyUSB="$(ls /dev/ttyUSB* | wc -l)"
	if [ "$ttyUSB" == "0" ];then
		debug_echo "lm9248 script : There is no /dev/ttyUSB*"
		sleep 10
		continue
	fi
	vendor=$(at-cmd $atdev AT+CGMI |sed -n '2p'|tr -d '\r')
	while [ "$model" == "" ];do
		model="$(at-cmd $atdev AT+GMM |sed -n '2p'|tr -d '\r')"
		debug_echo "model=$model"
	done
	imei=$(at-cmd $atdev AT+GSN |sed -n '2p'|tr -d '\r')

	cpin=$(at-cmd $atdev AT+CPIN? | sed -n '2p' | cut -d ':' -f2 | sed 's/ //g'|tr -d '\r')

	#just iccid
	iccid=$(at-cmd $atdev AT+ICCID | sed -n '2p'|cut -c 8-27)
	iccid_len=$(echo ${iccid} | wc -L)
	if [ $iccid_len != "20" ];then
		iccid="NO SIM"
		cpin="None"
		isp="None"
		signal="0"
	fi

	#get isp
	isp=$(at-cmd $atdev AT+COPS? | sed -n '2p' | cut -d '"' -f2)
	isp_dect=$(echo ${isp} | grep "COPS")
	if [ -n "${isp_dect}" ];then
		isp="No Service"
		debug_echo "lm9248 script : not get isp"
	fi

	#get signal
	signal=$(at-cmd $atdev AT+CSQ | sed -n '2p'|sed 's/.*:\(.*$\)/\1/' | cut -d ',' -f 1 | sed 's/ //g')
	if [ "$signal" -le 31 ];then
		signal=$(printf "%d" $((signal*100/31)))
	else
		signal="0"
	fi

	cgreg=$(at-cmd $atdev at+cgreg? | sed -n '2p' | sed 's/+CGREG: .,//g' | tr -d '\r')
	case $cgreg in
		1)
			cgreg="Registered OK"
			;;
		2)
			cgreg="Registering..."
			;;
		*)
			cgreg="Not registered"
			;;
	esac

	debug_echo "lm9248 script : create 4ginfo > /tmp/4ginfo"

#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor $model",
"imei":"$imei",
"iccid":"$iccid",
"pin":"$cpin",
"cops":"$isp",
"cgreg":"$cgreg",
"signal":"$signal"
}
EOF
	# get sim status ，实现热插拔sim
	if [ "$cpin" != "READY" ];then
		debug_echo "cpin:$cpin != READY "
		restart_4g_module "$atdev" "$section"
		cnt=0
		debug_echo "sleep 8"
		sleep 8
		continue
	fi
	# get 4gwan status
	ret="$(ping_test 3g-4gwan)"
	sleep 1
	stat_4g="$(ifconfig 3g-4gwan | sed -n '2p' | grep "inet addr" | wc -l)"
	if [ "$stat_4g" == "0" -o "$ret" == "1" -o "$first_dial" == 1 ];then
		first_dial=0
		cnt=$((cnt+1))
		ifup "$section"
		debug_echo "exec $section diag and ifup $section"
	else
		cnt=0
	fi
	debug_echo "sleep 8"
	sleep 8
	[ "$cnt" -ge "4" ] && cnt=0 && debug_echo "dial fial 4 times" && restart_4g_module $atdev $section
done

