#!/bin/sh

###
### 所有产品统一的标题校对脚本
### 参数依次为系统mac地址、系统sn码、系统cmei码
### 流程：输入机标mac ——> 输入盒标mac ——> 对照机标盒标 ——> 对照设备mac和贴标
### 流程：输入机标sn ——> 输入盒标sn ——> 对照机标盒标 ——> 对照设备sn和贴标 ——> 通过标贴sn获得后台绑定mac，与系统mac是否匹配
### 流程：输入机标cmei ——> 输入盒标cmei ——> 对照机标盒标 ——> 对照设备cmei和贴标
###

#服务器域名或者IP
test_server="10.0.0.82"

lan_mac="$1"
sn_sys="$2"
cmei_sys="$3"

lan_mac=`echo "$lan_mac" | tr '[a-z]' '[A-Z]'`
sn_sys=`echo "$sn_sys" | tr '[a-z]' '[A-Z]'`
cmei_sys=`echo "$cmei_sys" | tr '[a-z]' '[A-Z]'`

sn_sys_len=`echo "$sn_sys" | wc -L`

test_pack_mac="1"
test_pack_sn="1"
test_pack_cmei="1"

cat > /tmp/pass.txt <<EOF
------------------------------------------------------------
     ########     ###     ######   ######
     ##     ##   ## ##   ##    ## ##    ##
     ##     ##  ##   ##  ##       ##
     ########  ##     ##  ######   ######
     ##        #########       ##       ##
     ##        ##     ## ##    ## ##    ##
     ##        ##     ##  ######   ######
------------------------------------------------------------
EOF
pass=`cat /tmp/pass.txt`

cat > /tmp/failed.txt <<EOF
------------------------------------------------------------
    ########    ###    #### ##       ######## ########
    ##         ## ##    ##  ##       ##       ##     ##
    ##        ##   ##   ##  ##       ##       ##     ##
    ######   ##     ##  ##  ##       ######   ##     ##
    ##       #########  ##  ##       ##       ##     ##
    ##       ##     ##  ##  ##       ##       ##     ##
    ##       ##     ## #### ######## ######## ########
------------------------------------------------------------
EOF
failed=`cat /tmp/failed.txt`

###校验机标盒标mac
if [ ! -z "$lan_mac" ];then

    ###输入机标mac
    while true
    do
	echo -e "\n\033[42;34m 请用扫描枪录入机标MAC地址：\033[0m" 
	read -p " " MAC1
		
	#长度校验
	MAC1_len=`echo $MAC1 | wc -L`         
	if [ "$MAC1_len" -ne "12" ] ;then

	    echo -e "\e[41;34m 当前输入机标MAC长度错误 \e[0m"
	    continue
	fi  
	#格式校验

	MAC1=`echo "$MAC1" | tr '[a-z]' '[A-Z]'`
	MAC1_far=`echo ${MAC1} | sed -n "/^\([0-9A-F][0-9A-F]\)\{5\}[0-9A-F][0-9A-F]$/p" 2>/dev/null`
	if [ -z "$MAC1_far" ]; then 

	    echo -e "\e[41;34m 当前输入机标MAC格式错误 \e[0m"
	else
	    break
	fi  
    done

    ###输入盒标mac
    while true
    do
	echo -e "\n\033[42;34m 请用扫描枪录入盒标MAC地址：\033[0m" 
	read -p " " MAC2
		
	#长度校验
	MAC2_len=`echo $MAC2 | wc -L`     
	if [ "$MAC2_len" -ne "12" ] ;then

	    echo -e "\e[41;34m 当前输入盒标MAC长度错误 \e[0m"
	    continue
	fi  
	#格式校验
	MAC2=`echo "$MAC2" | tr '[a-z]' '[A-Z]'`
	MAC2_far=`echo ${MAC2} | sed -n "/^\([0-9A-F][0-9A-F]\)\{5\}[0-9A-F][0-9A-F]$/p" 2>/dev/null`
	if [ -z "$MAC2_far" ]; then 

	    echo -e "\e[41;34m 当前输入盒标MAC格式错误 \e[0m"
	else
	    break
	fi  
    done

    echo  " 当前输入的机标MAC为：$MAC1"
    echo  " 当前输入的盒标MAC为：$MAC2"
    echo  " 当前设备写入的MAC为：$lan_mac"

    if [ "$MAC1" != "$MAC2" ] ;then

	echo -e "\033[31m$failed\033[0m"
	echo -e "\e[31m 机标盒标MAC不匹配 \e[0m"
	exit
    else
	if [ "$MAC1" != "$lan_mac" ] || [ "$MAC2" != "$lan_mac" ] ;then

	    test_pack_mac="0"
	    echo -e "\033[31m$failed\033[0m"
	    echo -e "\033[31m 本产品标贴MAC与设备写入MAC不相同 \033[0m"
	    echo -e "\033[31m 设备写入MAC为 $lan_mac \033[0m"
	    exit 0
	fi
    fi
fi

if [ ! -z "$sn_sys" ];then

    ###输入机标sn码
    while true
    do
	echo -e "\n\033[42;34m 请用扫描枪录入机标${sn_sys_len}位的SN码：\033[0m" 
	read -p " " SN1
		
	#长度校验
	SN1_len=`echo $SN1 | wc -L`         
	if [ "$SN1_len" -ne "$sn_sys_len" ] ;then

	    echo -e "\e[41;34m 当前输入机标SN码长度错误 \e[0m"
	    continue
	else
	    break
	fi  
    done

    ###输入盒标SN码
    while true
    do
	echo -e "\n\033[42;34m 请用扫描枪录入盒标${sn_sys_len}位的SN码：\033[0m" 
	read -p " " SN2
		
	#长度校验
	SN2_len=`echo $SN2 | wc -L`     
	if [ "$SN2_len" -ne "$sn_sys_len" ] ;then

	    echo -e "\e[41;34m 当前输入盒标SN码长度错误 \e[0m"
	    continue
	else
	    break
	fi  
    done

    echo  " 当前输入的机标SN为：$SN1"
    echo  " 当前输入的盒标SN为：$SN2"
    echo  " 当前设备写入的SN为：$sn_sys"


    if [ "$SN1" != "$SN2" ] ;then

	echo -e "\033[31m$failed\033[0m"
	echo -e "\e[31m 机标盒标SN码不匹配 \e[0m"
	exit
    else
	if [ "$SN1" != "$sn_sys" ] || [ "$SN2" != "$sn_sys" ] ;then

	    test_pack_sn="0"
	    echo -e "\033[31m$failed\033[0m"
	    echo -e "\033[31m 本产品标贴SN与设备写入SN不相同 \033[0m"
	    echo -e "\033[31m 设备写入SN为 $sn_sys \033[0m"
	    exit 0
	fi

	###通过序列号获得后台绑定的mac地址
	op_code=`curl -s "http://$test_server/api/sn_to_mac?sn=$SN1"`
	sn_get_mac=`echo "$op_code" | cut -d "|" -f2`

	if [ "$sn_get_mac"  != "$sn_get_mac" ];then

	    test_pack_sn="0"
	    echo -e "\033[31m$failed\033[0m"
	    echo -e "\033[31m 本产品标贴SN与后台绑定MAC不相同 \033[0m"
	    echo -e "\033[31m 设备写入MAC为 $sn_sys \033[0m"
	    echo -e "\033[31m 该SN查询得到绑定的MAC为 $sn_get_mac \033[0m"
	    exit 0
	fi
    fi
fi

if [ ! -z "$cmei_sys" ];then

    ###输入机标cmei码
    while true
    do
	echo -e "\n\033[42;34m 请用扫描枪录入机标15位的cmei码：\033[0m" 
	read -p " " CMEI1
		
	#长度校验
	CMEI1_len=`echo $CMEI1 | wc -L`         
	if [ "$CMEI1_len" -ne "15" ] ;then

	    echo -e "\e[41;34m 当前输入机标CMEI码长度错误 \e[0m"
	    continue
	else
	    break
	fi  
    done

    ###输入盒标CMEI码
    while true
    do
	echo -e "\n\033[42;34m 请用扫描枪录入盒标15位的CMEI码：\033[0m" 
	read -p " " CMEI2
		
	#长度校验
	CMEI2_len=`echo $CMEI2 | wc -L`     
	if [ "$CMEI2_len" -ne "15" ] ;then

	    echo -e "\e[41;34m 当前输入盒标CMEI码长度错误 \e[0m"
	    continue
	else
	    break
	fi  
    done

    echo  " 当前输入的机标CMEI为：$CMEI1"
    echo  " 当前输入的盒标CMEI为：$CMEI2"
    echo  " 当前设备写入的CMEI为：$cmei_sys"

    if [ "$CMEI1" != "$CMEI2" ] ;then

	echo -e "\033[31m$failed\033[0m"
	echo -e "\e[31m 机标盒标SN码不匹配 \e[0m"
	exit
    else
	if [ "$CMEI1" != "$cmei_sys" ] || [ "$CMEI2" != "$cmei_sys" ] ;then

	    test_pack_cmei="0"
	    echo -e "\033[31m$failed\033[0m"
	    echo -e "\033[31m 本产品标贴CMEI与设备写入CMEI不相同 \033[0m"
	    echo -e "\033[31m 设备写入CMEI为 $cmei_sys \033[0m"
	    exit 0
	fi
    fi
fi

if [ "$test_pack_mac" = "1" ] && [ "$test_pack_sn" = "1" ] && [ "$test_pack_cmei" = "1" ] ;then
    echo "pass" > /tmp/pack_pass
else
    exit 
fi


