#!/bin/sh

###本地log目录
path_mes="/etc/mes_test"
path_script="${path_mes}/script"
path_curl_log="${path_mes}/curl_log"
path_temp_log="${path_mes}/tmp_log"
path_temp_mac="${path_mes}/tmp_mac"

###用于存放写入出厂mac之前的临时mac地址
if [ ! -d "${path_temp_mac}" ];then
    mkdir -p ${path_temp_mac}
fi

#服务器域名或者IP
###WE1626
test_server="10.0.0.82"
firmware="newOS"
model_wget=`uci get anyversion.device.device_model_displayname`
if [ -z "$model_wget" ];then
    model_wget="WE1626"
fi
 
###model_wget是获取的脚本的路径，而model才是真正的产品型号
var_check="$1"
var=`echo "$var_check" | grep "[A-Za-z]\{1,\}"`

if [ ! -z "$var_check" ] && [ ! -z "$var" ];then

    var=`echo "$var" | tr '[a-z]' '[A-Z]'`
    model="$var"
else
    model=`echo "$model_wget"`
fi

###系统相关参数
cpu=`cat /proc/cpuinfo |sed -n 1p|cut -d " " -f4`
ram=`cat /proc/meminfo | grep MemTotal|cut -d ":" -f2|sed 's/ //g'`
flashid=`cat /proc/flashid`
version=`uci get anyversion.device.device_version`
mes_version="v4.5.0"
version="MES_CRT-${mes_version};${firmware}-${version}"

art_mac=`hexdump -C -s 0x04 /dev/mtd2 | sed -n "1p"|cut -c 11-28|sed 's/\ //g'`
art_mac_up="$art_mac"
art_5g_mac=`hexdump -C -s 0x8004 /dev/mtd2 | sed -n "1p"|cut -c 11-28|sed 's/\ //g'`
lan_mac=`hexdump -C -s 0x28 /dev/mtd2 | sed -n "1p"|cut -c 11-28|sed 's/\ //g'`
wan_mac=`hexdump -C -s 0x2e /dev/mtd2 | sed -n "1p"|cut -c 11-28|sed 's/\ //g'`

###老化看门狗参数
wdFlag=""
wdGpio=""

###吞吐量参数
port1="ra0"
port2=""
###千兆or百兆
througvalue="bmbps"

###测试项目检测，有传参的则不测
test_project="$@"

pro_button=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -w "button_test" | wc -l`
###用于屏蔽无线后关闭询问uuid作为临时mac的参数,_n表示默认不要,_y表示默认要
pro_uumac_n=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -w "uumac_n" | wc -l`
pro_uumac_y=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -w "uumac_y" | wc -l`
pro_art=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -w "art_test" | wc -l`
pro_usb=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -w "usb" | wc -l`
pro_tf=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -w "tf" | wc -l`
pro_4g=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -w "4G" | wc -l`
pro_4g_dial=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -w "4G_dial" | wc -l`

###usb和tf卡挂载路径
path_usb="/www/usb/sda1"
path_tf=""

###4g拨号的接口
pra_4g_dial=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -o "4G_dial_[0-9a-zA-Z.]\{1,\}"`
ifcon_4g=`echo "$pra_4g_dial" | cut -d "_" -f3`
if [ ! -z "$ifcon_4g" ];then
    ifcon="$ifcon_4g"
else
    ifcon_file=""
    ifcon_4g=`uci get network.4gwan.ifname 2> /dev/null`
    if [ ! -z "$ifcon_4g" ];then
	ifcon="$ifcon_4g" 
    else
	ifcon="eth1"
    fi
fi

###备注的获取
comment=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -o "备注_.*" | cut -d "_" -f2  | cut -d " " -f1`
###订单号的获取
order=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -o "订单_.*" | cut -d "_" -f2  | cut -d " " -f1`
###版本号的获取
ver_check=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -o "ver_.*" | cut -d "_" -f2  | cut -d " " -f1`
###固件型号的获取
model_check=`echo "$test_project" | awk -F "$1" '{print $2}' | grep -o "model_.*" | cut -d "_" -f2  | cut -d " " -f1`

path_model="http://$test_server/zbt_factory/model/$model_wget/$firmware"
path_test="http://$test_server/zbt_factory/mes_test"

###文件大小，只比较库和bin文件大小
mac_set_bytes="15504"

###打包json字符串
###参数1：json_arr字符串
###参数2：测试项目
###参数3：测试结果
json_pack()                  
{          
    json_arr="$1"
    key="$2"     
    value="$3"   
		                  
    if [ -z "$json_arr" ] ;then
	                                       
	json_arr="\\{\""$key"\":\""$value"\"\\}"
    else                                        
	json_arr=`echo "$json_arr" | awk -F "}" '{print $1}'`
	json_arr="${json_arr},\""$key"\":\""$value"\"\\}"
    fi                                                     
    json_arr=`echo "$json_arr" | sed 's/\\\,/\,/g'`
    echo "$json_arr"                                         
}    

###测试结果json字符串的初始化
json_arr=""
json_arr=`json_pack "$json_arr" "art_mac" "$art_mac"` 

button_config_fun()
{
    sed -i 's/reboot/\#reboot/g' /etc/rc.button/reset
}

button_reconfig_fun()
{
    sed -i 's/\#\{1,\}reboot/reboot/g' /etc/rc.button/reset
    config_reset1="$?"

    if [ "$config_reset1" -eq "0" ] ;then
	echo -e "\033[42;37m 按键配置恢复成功 \033[0m"
    fi
}

###网络配置，只在完成自检后调用
network_config_fun()
{
    art_mac="$1"
    art_5g_mac="$2"
    tail_art=`echo "$art_mac" | cut -c 7-12`
    tail_5g_art=`echo "$art_5g_mac" | cut -c 7-12`

    ###修改ssid，mac后六位添加到配置文件中
    uci set wireless.default_radio0.ssid="WIFI-2.4G-${tail_art}"
    uci set wireless.guest_wifi.ssid="WIFI-2.4G-guest-${tail_art}"
    uci commit wireless
}

cat > /tmp/pass.txt <<EOF
------------------------------------------------------------
     ########     ###     ######   ######
     ##     ##   ## ##   ##    ## ##    ##
     ##     ##  ##   ##  ##       ##
     ########  ##     ##  ######   ######
     ##        #########       ##       ##
     ##        ##     ## ##    ## ##    ##
     ##        ##     ##  ######   ######
------------------------------------------------------------
EOF
pass=`cat /tmp/pass.txt`
cat > /tmp/failed.txt <<EOF
------------------------------------------------------------
########    ###    #### ##       ######## ########
##         ## ##    ##  ##       ##       ##     ##
##        ##   ##   ##  ##       ##       ##     ##
######   ##     ##  ##  ##       ######   ##     ##
##       #########  ##  ##       ##       ##     ##
##       ##     ##  ##  ##       ##       ##     ##
##       ##     ## #### ######## ######## ########
------------------------------------------------------------
EOF

failed=`cat /tmp/failed.txt`

#################### 自检开机画面 ################################

cat > /tmp/welcome.txt <<EOF
-------------------------------------------------------------
############################################################# 
##                                                         ## 
##                                                         ## 
##                                                         ## 
##                   ZBT_MES V4.5.0                        ##
##                    自检测试程序                         ##
##                                                         ## 
##                                                         ##
##                                                         ## 
############################################################# 
-------------------------------------------------------------
EOF

welcome=`cat /tmp/welcome.txt`
echo -e "\033[36m $welcome \033[0m"

echo " "
		
#################### 配置一些东西 ###############################

rm /tmp/test_log -rf
rm /usr/sbin/douptime -rf
rm /tmp/mac_set -rf
touch /tmp/test_log
chmod 777 /tmp/test_log

###按键的配置
button_config_fun


while true
do
    ####校验临时mac是否被注册过
    tmp_mac_check=`curl --connect-timeout 2 -m 2 --trace-ascii ${path_curl_log}/check_formal_mac.log -s "http://$test_server/api/mac_tmp_check?mac=$art_mac_up&model=$model"`
    if [ "$tmp_mac_check" = "" ];then
        echo -e "\033[31m 数据查询失败，正在尝试重新连接...\033[0m"
        continue
    fi

    ret_check=`echo "$tmp_mac_check" | grep -w -o "existence" | wc -l`
    if [ "$ret_check" != "0" ];then

	echo -e "\033[41;34m 经过校验，该mac地址 $art_mac_up 已经被其他设备注册过 \033[0m"
	while true
	do
	    ###询问是否使用uuid作为临时mac上报
	    if [ "$pro_uumac_y" -ne "0" ];then

		echo " 系统将创建虚拟MAC作为MES后台的临时MAC上报..."
		uuid_mac=`cat /proc/sys/kernel/random/uuid 2> /dev/null | sed 's/\-//g' | cut -c 1-12`
		echo "$uuid_mac" > ${path_temp_mac}/uuid_mac.txt
		art_mac_up=`cat ${path_temp_mac}/uuid_mac.txt`
		echo " 此次创建的虚拟MAC为：$art_mac_up"
		break
	    elif [ "$pro_uumac_n" -ne "0" ];then
		echo " 系统将不会创建虚拟MAC作为MES的临时MAC上报..."
		art_mac_up="$art_mac"
		break
	    else
		echo -e "\033[42;34m 是否创建虚拟mac作为MES后台的临时mac上报？\033[0m"
		echo  " 是请按任意键，否请按 n 键.."
		echo  " 添加 uumac_y 参数可关闭询问并默认创建uuid作为临时mac上报"
		echo  " 添加 uumac_n 参数可关闭询问并默认不创建uuid作为临时mac上报"

		read -p " " -n 1 any
		echo " "
		echo " 输入的按键为：$any"
		echo " "

		if [ "$any" != "n" ];then
		    pro_uumac_y="1"
		elif [ "$any" = "n" ];then
		    pro_uumac_n="1"
		fi
	    fi
	done
	break
    else
        break
    fi
done

##########复位键测试##############################################

if [ "$pro_button" -eq "0" ];then

    btn0="lo"
    echo -e "\033[42;34m请按复位按钮进入产品测试。。。。。。\033[0m" 
    while true
    do
	btn1=`cat /sys/kernel/debug/gpio | grep "gpio-1\ " | cut -d ")" -f2 | cut -c 6-7`
	if [ "$btn1" = "$btn0" ] ;then
	    echo -e "\e[32m 复位按键测试通过,请进行下一步 \e[0m"
	    break
	fi
    done
fi

##########校验是否校准无线##############################################

if [ "$pro_art" -eq "0" ];then

    echo " 正在检测是否进行了无线校验 "
    while true
    do
	###查看是否经过了无线校准
	if [ ! -z "$port1" ];then
	    while true
	    do
		wifitest=$(curl --connect-timeout 2 -m 2 --trace-ascii ${path_curl_log}/art_test_data.log -s "http://$test_server/api/device_test_data?model=$model&mac=$art_mac")
		if [ "$wifitest" = "" ];then
		    echo -e "\033[31m 数据查询失败，正在尝试重新连接...\033[0m"
		    continue
		else
		    break
		fi
	    done
	fi

	###若是双频则匹配5g的无线校准数据
	if [ ! -z "$port2" ];then
	    while true
	    do
		wifi_5g_test=$(curl --connect-timeout 2 -m 2 --trace-ascii ${path_curl_log}/art_5g_test_data.log -s "http://$test_server/api/device_test_data?model=$model&mac=$art_5g_mac")
		if [ "$wifi_5g_test" = "" ];then
		    echo -e "\033[31m 数据查询失败，正在尝试重新连接...\033[0m"
		    continue
		else
		    break
		fi
	    done
	fi

	wifitest_result=$(echo $wifitest | grep pass|wc -l)
	wifi_5g_test_result=$(echo $wifi_5g_test | grep pass|wc -l)
	if [ "$wifitest_result" = "1" ] || [ "$wifi_5g_test_result" = "1" ] ;then

	    echo -e "\033[32m 经服务器检测，本设备已通过无线校准\033[0m"
	    echo "wifitest=1" >>/tmp/test_log &
	    ###通过射频的将结果放在日志文件中
	    json_arr=`json_pack "$json_arr" "art" "pass"` 
	    break
	else
	    echo -e "\033[31m 经服务器检测，本设备没有通过无线校准\033[0m"
	    echo -e "\033[31m 请通过无线校准后再进行生产测试\033[0m"
	    json_arr=`json_pack "$json_arr" "art" "failed"` 
	    echo -e "\033[31m $failed\033[0m"
	    button_reconfig_fun
	    exit 0
	fi
    done
fi

############################ USB测试 ##########################

if [ "$pro_usb" -eq "0" ];then

    devsda=`ls /dev/ | grep "sda*" | wc -l`
    devtype1=`cat ${path_usb}/usbtest.txt 2> /dev/null`
    echo "$devtype1"  > /tmp/devusb.log
    devusb=`cat /tmp/devusb.log | grep "usb_test_pass" | wc -l`

    if [ "$devusb" -eq "0" ] || [ "$devsda" -eq "0" ];then

	echo -e "\033[31m 未检测到USB设备-----USB接口测试失败 \033[0m"
        echo  "USB=0" >>/tmp/test_log &
        json_arr=`json_pack "$json_arr" "usb" "failed"` 
    else
        echo -e "\033[32m 检测到USB设备-----USB设备测试成功 \033[0m"    
	echo  "USB=1" >>/tmp/test_log &
        json_arr=`json_pack "$json_arr" "usb" "pass"` 
    fi  
fi

############################# 老化脚本下载测试 ####################
echo ""
echo " 测试老化脚本"
###下载老化脚本    
while true
do
    if [ ! -f "${path_script}/douptime" ];then
        echo " 正在下载老化测试文件..."
        wget -T 5 -P ${path_script}/ $path_test/douptime &> /dev/null
        chmod 777 ${path_script}/douptime
    else
        echo " 下载老化测试文件成功"
        chmod 777 ${path_script}/douptime
	break
    fi  
done

chmod 777 ${path_script}/douptime
${path_script}/douptime $wdFlag $wdGpio &
	
psdouptime=`ps | grep douptime | wc -l`
if [ "$psdouptime" = "1" ] ;then
    echo -e "\033[41;37m 老化脚本运行失败 \033[0m"
    echo  "uptime_sh=0" >>/tmp/test_log &
    json_arr=`json_pack "$json_arr" "douptime_run" "failed"` 
else
    echo -e "\033[42;37m 老化脚本运行成功 \033[0m"	
    echo  "uptime_sh=1" >>/tmp/test_log &
    json_arr=`json_pack "$json_arr" "douptime_run" "pass"` 
fi

###老化脚本写入开机启动脚本
while true
do
    diag=`cat /etc/diag.sh | grep douptime|wc -l`
    if [ "$diag" = "0" ];then

	echo "${path_script}/douptime $wdFlag $wdGpio &" >> /etc/diag.sh	
	diag2=`cat /etc/diag.sh | grep douptime|wc -l`
	if [ "$diag2" = "0" ];then

	    echo -e "\033[31m 老化脚本写入启动失败 \033[0m"
	    echo  "uptime_init=0" >>/tmp/test_log &
	    json_arr=`json_pack "$json_arr" "douptime_init" "failed"` 
	fi
    else 
	echo -e "\033[32m 老化脚本写入启动成功 \033[0m"
	echo  "uptime_init=1" >>/tmp/test_log &
	json_arr=`json_pack "$json_arr" "douptime_init" "pass"` 
	break
    fi
done

######################### 通过日志文件分析测试的结果 ###############
menu=`cat /tmp/test_log | grep =0`  

if [ "$menu" = "" ] ;then
    result=1     
else
    result=0   
fi

if [ "$result" = "1" ] ;then

    echo -e "\033[42;37m 没有检测失败项目\033[0m"
    echo -e "\033[32m $pass\033[0m" 
else
    echo -e "\033[31m $failed\033[0m"
    echo -e "\033[41;37m 测试失败的项目 \033[0m"
    echo -e "\033[41;37m $menu \033[0m"
    button_reconfig_fun
    exit 0
fi	

############################### mt7628写MAC地址 ############################
###从服务器获得mac_set
while true
do
    if [ ! -f "${path_script}/mac_set" ] ;then

        echo " 正在下载mac工具..."
        wget -T 5 -P ${path_script}/ $path_model/mac_set &> /dev/null
    fi  

    mac_set_file_check=`ls -l ${path_script}/mac_set | awk -F " " '{print $5}'`
    if [ "$mac_set_file_check" != "$mac_set_bytes" ];then
	rm ${path_script}/mac_set -rf 
        continue
    else
        echo " mac工具下载完成"
        chmod 777 ${path_script}/mac_set
        break
    fi  
done

###MAC地址录入判断
###录入的mac地址是lan口的mac
while true
do
    echo -e "\033[42;34m 请用扫描枪录入设备MAC地址。。。。。。\033[0m" 
    read -p " " MAC

    ###长度校验
    MACL=`echo $MAC | wc -L`  
    if [ "$MACL" != "12" ] ;then 
	echo -e "\033[41;34m 当前输入MAC长度错误 \033[0m"
	continue
    fi

    ###格式校验
    MACF=`echo ${MAC} | sed -n "/^\([0-9A-F][0-9A-F]\)\{5\}[0-9A-F][0-9A-F]$/p"`
    if [ -z "$MACF" ]; then 
	MACF=`echo ${MAC} | sed -n "/^\([0-9a-f][0-9a-f]\)\{5\}[0-9a-f][0-9a-f]$/p"`
	if [ -z "$MACF" ]; then
	    echo -e "\033[41;34m 当前输入MAC格式错误 \033[0m"
	else
	    break
	fi
    else
	break
    fi
done

###写入mac
echo " 当前要写入的MAC是$MAC"
MAC=`echo $MAC| tr '[A-Z]' '[a-z]'`

while true
do
    ####校验mac是否被使用过
    check_mac=`curl --connect-timeout 2 -m 2 --trace-ascii ${path_curl_log}/check_formal_mac.log -s "http://$test_server/api/check_formal_mac?model=$model&mac=$MAC"`
    if [ "$check_mac" = "" ];then
	echo -e "\033[31m 数据查询失败，正在尝试重新连接...\033[0m"
	continue
    fi

    ret_check=`echo "$check_mac" | grep -w -o "existence" | wc -l`
    if [ "$ret_check" != "0" ];then
	
	echo -e "\033[41;34m 经过校验，该mac地址已经被其他设备使用过，请重新输入mac地址 \033[0m"
	button_reconfig_fun
	exit
    else
	break
    fi
done

###需要添加执行字符加减的文件
cutmac1=`echo "$MAC" | cut -c 1-2`
cutmac2=`echo "$MAC" | cut -c 3-4`
cutmac3=`echo "$MAC" | cut -c 5-6`
cutmac4=`echo "$MAC" | cut -c 7-8`
cutmac5=`echo "$MAC" | cut -c 9-10`
cutmac6=`echo "$MAC" | cut -c 11-12`

MACMAO=${cutmac1}:${cutmac2}:${cutmac3}:${cutmac4}:${cutmac5}:${cutmac6}

###2.4g的mac
mac=`${path_script}/maccalc add $MACMAO -2 | tr '[A-Z]' '[a-z]' | sed 's/\://g'`

###设置出厂mac
cp /dev/mtd2 /tmp/art
chmod 777 /tmp/art
chmod 777 ${path_script}/mac_set
${path_script}/mac_set $mac
cat /tmp/art > /dev/mtdblock2

######################### 校验MAC #######################

wifi_art=`hexdump -C -s 0x04 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'`
wifi_5g_art=`hexdump -C -s 0x8004 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'`
lan_art=`hexdump -C -s 0x28 /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'`
wan_art=`hexdump -C -s 0x2e /dev/mtd2|sed -n "1p"|cut -c 11-28|sed 's/\ //g'`

echo " 当前设备写入的MAC"
echo " 2.4G MAC: $wifi_art"
if [ ! -z "$port2" ];then

    echo " 5.8G MAC: $wifi_5g_art"
fi
echo " LAN MAC: $lan_art"
echo " WAN MAC: $wan_art"

if [ "$wifi_art" != "$mac" ] || [ "$lan_art" != "$MAC" ];then

    echo -e "\033[31m MAC写入失败\033[0m"
    echo -e "\033[31m $failed\033[0m"
    echo "wifi_mac=0" >/tmp/test_mac_log 	
    button_reconfig_fun
    exit 0
else
    echo -e "\033[32m MAC写入成功\033[0m" 
    echo "wifi_mac=1" >/tmp/test_mac_log 
fi

macauth=`cat /tmp/test_mac_log | grep =0`
if [ "$macauth" = "" ] ;then
    echo -e "\033[32m 所有MAC地址写入成功\033[0m"
    op_code=""
    while true
    do
	date=`date +%Y%m%d%t%H:%M:%S|awk '{print $1}'`
	###自检完成后注册mac上报测试数据和上报正式mac信息
	op_code=$(curl --connect-timeout 2 -m 2 --trace-ascii ${path_curl_log}/common_data.log -s "http://$test_server/api/data_report?op=common_data&sn=&model=$model&date=$date&version=$version&oldmac=$art_mac_up&newmac=$lan_art&common=$json_arr")
	op_result=`echo "$op_code" | grep -o "pass"`
	if [ "$op_result" = "pass" ];then

	    echo "$art_mac" > ${path_temp_mac}/art_mac.txt 
	    echo "$art_5g_mac" > ${path_temp_mac}/art_5g_mac.txt 
	    echo "$lan_mac" > ${path_temp_mac}/lan_mac.txt 
	    echo "$wan_mac" > ${path_temp_mac}/wan_mac.txt 
	    echo -e "\033[32m 上报mac数据成功 \033[0m"
	    break
	else
	    echo -e "\033[31m 上报mac数据中，请确保与服务器连接正常..\033[0m"
	fi
    done
else
    button_reconfig_fun
    echo -e "\033[31m MAC地址写入校验失败\033[0m"
    echo -e "\033[31m $failed\033[0m"
    exit 
fi

###添加备注
if [ ! -z "$comment" ] ;then
    while true
    do
        op_comment=$(curl --connect-timeout 2 -m 2 --trace-ascii ${path_curl_log}/comment.log -s "http://$test_server/api/device/comment_edit?mac=$lan_art&model=$model&comment=${comment}")
	op_comment_restult=`echo "$op_comment" | grep "success" | wc -l`
        if [ "$op_comment_restult" -ge "1" ];then
            echo -e "\033[32m 添加备注成功，备注内容：${comment}\033[0m"
            break
        else
	    echo -e "\033[31m 添加备注失败,尝试重新上传..\033[0m"
	    continue
	fi
    done
fi

###绑定订单号
if [ ! -z "$order" ] ;then
    while true
    do
        op_order=$(curl --connect-timeout 2 -m 2 --trace-ascii ${path_curl_log}/order.log -s "http://$test_server/api/device/assoc/order?mac=$lan_art&model=$model&order_sn=${order}")
	op_order_restult=`echo "$op_order" | grep "success" | wc -l`
        if [ "$op_order_restult" -ge "1" ];then
            echo -e "\033[32m 添加订单号成功，订单号：${order}\033[0m"
            break
        else
	    echo -e "\033[31m 添加订单号失败,尝试重新上传..\033[0m"
	    continue
	fi
    done
fi

button_reconfig_fun
network_config_fun $wifi_art $wifi_5g_art
echo -e "\033[32m $pass\033[0m"

###############################结束菜单#########################

cat <<EOF
|--------------------------------------------------------------------------|
|                                                                          |
|                        已经完成当前测试工序                              |
|                           请进入老化测试                                 |
|                                                                          |
|--------------------------------------------------------------------------|

EOF
		
