#!/bin/sh

###
### 所有产品统一的吞吐量测试脚本
### 输入网卡开始进行吞吐量测试
### $1是2.4G网卡、$2是5.8G网卡，若没有5.8G可以传参数2
###

port1="$1"
port2="$2"
value="$3"

###2.4G通过标准80mbps
pass=105000000		
###5.8G通过标准180mbps
if [ "$value" = "bmbps" ];then
    pass_5g=105000000		
else
    pass_5g=236250000
fi

tm=5
tm2=10
throughput_data=`cat /tmp/throughput_data 2>/dev/null`
throughput_data_5g=`cat /tmp/throughput_data_5g 2>/dev/null`

if [ ! -z "$port1" ];then
    echo " 当前网卡2.4G：$port1"
fi

if [ ! -z "$port2" ];then
    echo " 当前网卡5.8G：$port2"
fi

###测试2.4G吞吐量
if [ ! -z "$port1" ] ;then

    if [ -z "$throughput_data" ] ;then

	echo " 正在进行2.4G吞吐量测试.. " 
	rx_result1=0
	tx_result1=0

	while true
	do
	    rx_before=`cat /sys/class/net/$port1/statistics/rx_bytes`
	    tx_before=`cat /sys/class/net/$port1/statistics/tx_bytes`
	    sleep $tm

	    rx_after=`cat /sys/class/net/$port1/statistics/rx_bytes`
	    tx_after=`cat /sys/class/net/$port1/statistics/tx_bytes`

	    rx_result2=`expr $rx_after - $rx_before`
	    tx_result2=`expr $tx_after - $tx_before`
	    
	    ###把两个5s时间内的流量差加起来就是一个10s时间内的流量差
	    rx_result=`expr $rx_result1 + $rx_result2`
	    tx_result=`expr $tx_result1 + $tx_result2`
	    
	    result=`expr $rx_result + $tx_result`

	    echo " 2.4G: ${tm2}秒新增流量为rx=$rx_result Bytes，tx=$tx_result Bytes，total=$result Bytes "

	    if [ "$result" -ge "$pass" ];then

		rx_average=`expr $rx_result / 1310720`
		tx_average=`expr $tx_result / 1310720`
		result_mbps=`expr $result / 1310720`
		echo "$result_mbps" > /tmp/throughput_data
		break
	    else
		###前一个5s的流量差赋值给result1
		rx_result1=$rx_result2
		tx_result1=$tx_result2
	    fi
	done
    fi
    throughput_data=`cat /tmp/throughput_data`
    echo ""
    echo -e "\e[32m 2.4G 吞吐量测试已通过,吞吐量值为$throughput_data \e[0m"
fi


###测试5.8G吞吐量
if [ ! -z "$port2" ] ;then

    if [ -z "$throughput_data_5g" ];then
	
	echo " 正在进行5.8G吞吐量测试.. " 
	rx_result1=0
	tx_result1=0

	while true
	do
	    rx_before=`cat /sys/class/net/$port2/statistics/rx_bytes`
	    tx_before=`cat /sys/class/net/$port2/statistics/tx_bytes`
	    sleep $tm

	    rx_after=`cat /sys/class/net/$port2/statistics/rx_bytes`
	    tx_after=`cat /sys/class/net/$port2/statistics/tx_bytes`

	    rx_result2=`expr $rx_after - $rx_before`
	    tx_result2=`expr $tx_after - $tx_before`
	    
	    rx_result=`expr $rx_result1 + $rx_result2`
	    tx_result=`expr $tx_result1 + $tx_result2`
	    
	    result=`expr $rx_result + $tx_result`

	    echo " 5.8G: ${tm2}秒新增流量为rx=$rx_result Bytes，tx=$tx_result Bytes，total=$result Bytes "

	    if [ "$result" -ge "$pass_5g" ];then

		rx_average=`expr $rx_result / 1310720`
		tx_average=`expr $tx_result / 1310720`
		result_mbps_5g=`expr $result / 1310720`
		echo "$result_mbps_5g" > /tmp/throughput_data_5g
		break
	    else
		rx_result1=$rx_result2
		tx_result1=$tx_result2
	    fi
	done
    fi
    throughput_data_5g=`cat /tmp/throughput_data_5g`
    echo ""
    echo -e "\e[32m 5.8G 吞吐量测试已通过,吞吐量值为$throughput_data_5g \e[0m"
fi


