#!/bin/sh
#19d2:0579

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2

. /usr/sbin/anywifi/dial_common.sh

ifname="$(get_rndsi_cdc_netcard_name)"
atdev="/dev/ttyUSB1"
section="4gwan"
interfacename="4gwan"

code=0

#拨号
dial()
{
	echo Y > /sys/class/net/wwan0/qmi/raw_ip
	apn="$(my_uci_get network.$section.apn)"
	if [ ! -z "$apn" ];then
		code="$(qmicli --device=/dev/cdc-wdm0 --wds-start-network="ip-type=4,apn=${apn}" --client-no-release-cid)"
	else
		code="$(qmicli --device=/dev/cdc-wdm0 --wds-start-network="ip-type=4" --client-no-release-cid)"
	fi

	ip link set dev wwan0 up
	sleep 3
	udhcpc -q -f -n -i wwan0
}

down_and_delete_config()
{
	 ip link set dev wwan0 down
}

while [ 1 ]
do
	while [ ! -f /tmp/module_ifname ]
	do
		/usr/sbin/anywifi/rclocal.d/S99_module_ifname &
		sleep 2
	done
	ifname="$(cat /tmp/module_ifname)"
	while [ "$ifname" == none ]
	do
		ifname="$(cat /tmp/module_ifname)"
		sleep 5
	done
	ttyUSB="$(ls /dev/ttyUSB* | wc -l)"
	if [ "$ttyUSB" == "0" ];then
		sleep 10
		debug_echo "There is no /dev/ttyUSB*"
		continue
	fi

	ppp_mode="$(my_uci_get network.4gwan.proto)"
	if [ "$ppp_mode" == "3g" ];then
		debug_echo "ppp dial mode, close current mode and break"
		down_and_delete_config
		break
	fi

	at-cmd $atdev AT

	vendor=$(at-cmd $atdev AT+CGMI | sed -n '2p' | tr -d '\r')
	imei=$(at-cmd $atdev AT+CGSN | sed -n '2p' | tr -d '\r')
	iccid=$(at-cmd $atdev AT+ICCID | sed -n '2p' | awk -F ' ' '{print $2}' | tr -d '\r')
	iccid_len=$(echo ${iccid} | wc -L)
	if [ $iccid_len != "20" ];then
		iccid="NO SIM"
		cpin="None"
		cops="None"
		signal="0"
	fi

	cops=$(at-cmd $atdev AT+COPS? | sed -n '2p' | cut -d '"' -f2)
	if [ "$(echo $cops| grep "460" | wc -l)" == "1" ];then
		cops="$(network_provider $cops)"	
	fi

	#get signal
	signal=$(at-cmd $atdev AT+CSQ | sed -n '2p' | awk -F ': ' '{print $2}'| awk -F ',' '{print $1}')
	if [ "$signal" -ge 100 ];then
		signal=$((signal - 100))
		signal=$(printf "%d" $((signal*100/91)))
	elif [ "$signal" -le 31 ];then
		signal=$(printf "%d" $((signal*100/31)))
	else
		signal="0"
	fi

	imsi="$(at-cmd /dev/ttyUSB1 at+cimi | sed -n '2p' | tr -d '\r')"
	if [ "$(echo $imsi | wc -L)" != "15" ];then
		imsi=""
	fi

	#get 4gwan status 
	cpin=$(at-cmd $atdev AT+CPIN? | sed -n '2p' | awk -F ': ' '{print $2}' | tr -d '\r')
	stat_4g="$(ifconfig $ifname | sed -n '2p' | grep "inet addr" | wc -l)"
	ping_addr="114.114.114.114" # TO DO : need define a addr in a config file
	stat_4gwan_ping="$(ping -I $ifname -c 2 114.114.114.114)"
	ret=`echo $?`
	if [ "$stat_4g" == "0" -o "$ret" == "1" ];then
		dial
		ifup wan
		debug_echo "exec $section diag and ifup $interfacename"
	fi

	debug_echo "update 4ginfo > /tmp/4ginfo"
	
#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor $model",
"sim_status":"${cpin}",
"signal":"$signal",
"iccid":"$iccid",
"imei":"$imei",
"cops":"${cops}",
}
EOF
	sleep 8
done

