#!/bin/sh
#12d1:15c3

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2

. /usr/sbin/anywifi/dial_common.sh

atdev="/dev/$(awk -F ' ' '{print $4}' /tmp/mobile_module_name.txt)"
ifname=""
section="4gwan"

while [ 1 ]
do
	if [ ! -f /tmp/module_ifname ];then
		/usr/sbin/anywifi/rclocal.d/S99_module_ifname &
		sleep 5
	fi

	ifname="$(cat /tmp/module_ifname)"
	[ "$ifname" != "none" ] && break
	sleep 5
done

config()
{
	uci set network.$section=interface
	uci set network.$section.ifname="$ifname"
	uci set network.$section.proto=dhcp
	uci set network.$section.metric=5
	uci set network.wan.metric=3
	uci commit network
}

#拨号
dial()
{
	apn="$(uci get network.$section.apn)"
	at-cmd $atdev AT+CGDCONT=1,\"IP\",\"${apn}\"
	at-cmd $atdev AT^NDISDUP=1,0
	sleep 3
	at-cmd $atdev AT^NDISDUP=1,1
}

debug=0
close_module_debug()
{
	[ "$debug" == "1" ] && return

	at-cmd $atdev AT+CGREG=0
	at-cmd $atdev AT+CIREG=0
	at-cmd $atdev at+CEREG=0
	at-cmd $atdev at+CREG=2
	at-cmd $atdev at+C5GREG=0
	at-cmd $atdev AT\^CURC=0
	at-cmd $atdev at\^CERSSI=0
	at-cmd $atdev AT\^HFREQINFO=0
	at-cmd $atdev AT+COPS=0,2

	debug=1
}

set_firewall "$section"
config_judge=0
[ "$(uci -q get network.4gwan)" == "interface" ] || config_judge=1
[ "$(uci -q get network.4gwan.ifname)" == "$ifname" ] || config_judge=1
[ "$(uci -q get network.4gwan.proto)" == "dhcp" ] || config_judge=1
[ -n "$(uci -q get network.4gwan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ -n "$(uci -q get network.wan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ "$(uci -q get network.wan.metric)" != "$(uci -q get network.4gwan.metric)" ] || config_judge=1
if [ "$config_judge" == 1 ];then
	config
	debug_echo "reate $section network config"
	ifup wan
	ifup "$section"
fi

get_more_msg()
{
	mmsg=$(at-cmd $atdev AT+CREG? | grep -w "CREG" | sed 's/,/ /g' | sed 's/"/ /g' | tr -d '\r')
	lac=$(echo "${mmsg}" | awk '{print $4}')
	ci=$(echo "${mmsg}" | awk '{print $5}')
	mnc=$cops_msg
}

while [ 1 ]
do
	close_module_debug

	msg=$(at-cmd $atdev ATI)
	vendor=$(echo "${msg}" | sed -n '2p' | awk '{print $2}' | tr -d '\r')
	model=$(echo "${msg}" | sed -n '3p' | awk '{print $2}' | tr -d '\r')
	version=$(echo "${msg}" | sed -n '3p' | awk '{print $2}' | tr -d '\r')
	imei=$(echo "${msg}" | sed -n '5p' | awk '{print $2}' | tr -d '\r')

	imsi=$(at-cmd $atdev at+cimi | sed -n '2p' | tr -d '\r')
	len=$(echo "${imsi}" | wc -L)
	[ "$len" != "15" ] && imsi="NONE"

	cpin=$(at-cmd $atdev AT+CPIN? | sed -n '2p' | tr -d '\r' | grep -o "READY")
	if [ "$cpin" == "READY" ];then
		iccid=$(at-cmd $atdev AT^ICCID? | sed -n '2p' | \
			awk '{print $2}' | tr -d '\r')
		len=$(echo "${iccid}" | wc -L)
		[ "$len" != "20" ] && [ "$len" != "19" ] && iccid=="NONE"

		cgreg=$(at-cmd $atdev AT+CGREG? | sed -n '2p' | \
			cut -d ',' -f2 | tr -d '\r')

		signal=$(at-cmd $atdev AT+CSQ | sed -n '2p' | \
			sed 's/.*:\(.*$\)/\1/' | cut -d ',' -f 1 | sed 's/ //g')
		if [ "$signal" -le 31 ];then
			signal=$(printf "%d" $((signal*100/31)))
		else
			signal="0"
		fi

		cops_msg=$(at-cmd $atdev AT+COPS? | grep -w "COPS" | cut -d '"' -f2 | tr -d '\r')
		cops=$(network_provider $cops_msg)
		if [ -n "${cops}" ];then
			net_type_msg="$(at-cmd $atdev at^hcsq? | sed -n '2p')"
			net_type="$(echo "$net_type_msg" | awk -F '"' '{print $2}')"
			case $net_type in
				LTE |\
				WCDMA |\
				TD-SCDMA)
					net_type="2G/3G/4G"
					;;
				NR)
					net_type="5G NR"
					;;
				*)
					net_type="NONE"
			esac

			#get 4gwan status
			ret="$(ping_test $ifname)"
			sleep 1
			stat_4g="$(ifconfig $ifname | sed -n '2p' | grep "inet addr" | wc -l)"
			if [ "$stat_4g" == "0" -o "$ret" == "1" ];then
				dial
				ifup "$section"
				debug_echo "exec $section diag and ifup $section"
			fi

			get_more_msg
		else
			cops="No_Service"
			net_type="NONE"
		fi
	else
		imei="NONE"
		iccid="NONE"
		signal="0"
		net_type="NONE"
		cops="No_Service"
	fi

	
	debug_echo "create 4ginfo > /tmp/4ginfo file"

#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor $model",
"version":"$version",
"cpin":"$cpin",
"signal":"$signal",
"iccid":"$iccid",
"imsi":"$imsi",
"imei":"${imei}",
"cops":"$cops",
"cgreg":"$cgreg",
"net_type":"$net_type",
"lac":"$lac",
"ci":"$ci",
"mnc":"$mnc",
"ifname":"$ifname",
}
EOF
	sleep 8
done

