#!/bin/sh
#12d1:15c1
[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2

. /usr/sbin/anywifi/dial_common.sh

atdev="/dev/ttyUSB0"
ifname="$(get_rndsi_cdc_netcard_name)"
section="4gwan"
interfacename="4gwan"

#拨号
dial()
{
	section=$1
	apn=`uci get network.$section.apn 2>/dev/null`
	username=`uci get network.$section.username 2>/dev/null`
	password=`uci get network.$section.password 2>/dev/null`

	status=$(at-cmd $atdev AT^NDISSTATQRY? | sed -n '2p'| cut -d: -f2 | sed 's/ //g' | cut -d, -f1)
	if [ "$status" != "1" ];then
		at-cmd $atdev AT^NDISDUP=1,1,\"${apn}\",\"${username}\",\"${password}\"
		sleep 3
		ifup 4gwan
	fi
}

#写配置
config()
{
	uci set network.$section=interface
	uci set network.$section.ifname="$ifname"
	uci set network.$section.proto=dhcp
	uci set network.$section.metric="5"
}

at-cmd $atdev AT^CURC=0

#读取模块信息
vendor=$(at-cmd $atdev AT+CGMI | sed -n '2p' | tr -d '\r')
model=$(at-cmd $atdev AT+GMM | sed -n '2p' | tr -d '\r')
imei=$(at-cmd $atdev AT+GSN | sed -n '2p' | tr -d '\r')

while [ 1 ]
do
	while [ ! -f /tmp/module_ifname ]
	do
		/usr/sbin/anywifi/rclocal.d/S99_module_ifname &
		sleep 2
	done
	ifname="$(cat /tmp/module_ifname)"
	while [ "$ifname" == none ]
	do
		ifname="$(cat /tmp/module_ifname)"
		sleep 5
	done
	at-cmd $atdev AT^CURC=0
	imsi=$(at-cmd $atdev AT+CIMI | sed -n '2p' | tr -d '\r')
	#读卡
	iccid=$(at-cmd $atdev AT^ICCID? | sed -n '2p' | cut -c 9-28)
	iccid_len=$(echo ${iccid} | wc -L)
	if [ $iccid_len != "20" ]  && [ $iccid_len != "19" ];then
		iccid="NO SIM"
		cpin="None"
		isp="None"
		signal="0"
	else
		cpin=$(at-cmd $atdev AT+CPIN? | sed -n '2p' | cut -d ':' -f2 | sed 's/ //g' | tr -d '\r')
		isp=$(at-cmd $atdev AT+COPS? | sed -n '2p' | cut -d '"' -f2)
		isp_dect=$(echo ${isp} | grep "COPS")
		if [ -n "${isp_dect}" ];then
			isp="No Service"
		else
			net_type=$(at-cmd $atdev AT+COPS? | sed -n '2p' | cut -d ',' -f4 | tr -d '\r')
			#拨号
			dial $section
		fi
		
		signal=$(at-cmd $atdev AT+CSQ | sed -n '2p' | sed 's/.*:\(.*$\)/\1/' | cut -d ',' -f 1 | sed 's/ //g')
		if [ "$signal" -le 31 ];then
			signal=$(printf "%d" $((signal*100/31)))
		else
			signal="0"
		fi
		cgreg=$(at-cmd $atdev AT+CGREG? | sed -n '2p' | cut -d ',' -f2|tr -d '\r')
	fi

#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor $model",
"sim_status":"$cpin",
"signal":"$signal",
"iccid":"$iccid",
"imsi":"$imsi",
"imei":"$imei",
"cops":"$isp"
}
EOF
	sleep 8
done

