#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2

. /usr/sbin/anywifi/dial_common.sh

atdev="/dev/$(awk -F ' ' '{print $4}' /tmp/mobile_module_name.txt)"
ifname=""
section="4gwan"

#拨号
dial()
{
	apn=`my_uci_get network.$section.apn 2>/dev/null`
	at-cmd $atdev AT+CGDCONT=1,\"IP\",\"${apn}\"
	at-cmd $atdev AT+QNETDEVCTL=0,1,0
	sleep 3
	at-cmd $atdev AT+QNETDEVCTL=1,1
}

#写配置
config()
{
	uci set network.${section}=interface
	uci set network.${section}.ifname=${ifname}
	uci set network.${section}.proto=dhcp
	uci set network.${section}.metric=5
	uci set network.wan.metric=3
	uci commit network
}

restart_4g_module(){
	local atdev="$1"
	local section="$2"
	ifdown "$section"
	gpio_4g="$(my_uci_get netcard.device.module_gpio)"
	active="$(my_uci_get netcard.device.active)"
	if [ "$gpio_4g" == "" ];then
		debug_echo "use cfun restart_4g_module"
		at-cmd $atdev at+cfun=1,1
	else
		debug_echo "use gpio restart_4g_module"
		[ -z "$active" ] && active=1
		[ "$active" == "1" ] && value=0
		[ "$active" == "0" ] && value=1
		echo $value > /sys/class/gpio/gpio${gpio_4g}/value
		sleep 5
		echo $active > /sys/class/gpio/gpio${gpio_4g}/value
		sleep 15
	fi
	pid_vid="$(cat /tmp/mobile_module_name.txt | awk '{print $2}')"
	pid_vid_judge="$(lsusb | grep -o "$pid_vid")"
	while [ -z "$pid_vid_judge" ];do
		sleep 5
		pid_vid_judge="$(lsusb | grep -o "$pid_vid")"
	done
	ttyUSB="$(ls /dev/ttyUSB* | wc -l)"
	while [ "$ttyUSB" == "0" ];do
		debug_echo "There is no /dev/ttyUSB*"
		sleep 10
		ttyUSB="$(ls /dev/ttyUSB* | wc -l)"
	done
	ifup "$section"
}

ppp_mode="$(my_uci_get network.${section}.proto)"
if [ "$ppp_mode" == "3g" ];then
	debug_echo "ppp dial mode, close current mode and break"
	exit
fi

while [ ! -f /tmp/module_ifname ]
do
	/usr/sbin/anywifi/rclocal.d/S99_module_ifname &
	sleep 2
done
ifname="$(cat /tmp/module_ifname)"
while [ "$ifname" == none ]
do
	ifname="$(cat /tmp/module_ifname)"
	sleep 5
done
#判断模块配置
set_firewall "$section"
config_judge=0
[ "$(uci -q get network.4gwan)" == "interface" ] || config_judge=1
[ "$(uci -q get network.4gwan.ifname)" == "$ifname" ] || config_judge=1
[ "$(uci -q get network.4gwan.proto)" == "dhcp" ] || config_judge=1
[ -n "$(uci -q get network.4gwan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ -n "$(uci -q get network.wan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ "$(uci -q get network.wan.metric)" != "$(uci -q get network.4gwan.metric)" ] || config_judge=1
if [ "$config_judge" == 1 ];then
	config
	debug_echo "reate $section network config"
	ifup wan
	ifup "$section"
fi

ping_sh_pid="$(ps -w | grep "/usr/sbin/anywifi/manual_dial/module_ping.sh" | grep -v "grep" | awk '{print $1}')"
if [ -z "$ping_sh_pid" ];then
	/usr/sbin/anywifi/manual_dial/module_ping.sh $ifname &
fi
trap "restart_4g_module $atdev $section" USR1
first_dial=1
while [ 1 ]
do
	ttyUSB="$(ls /dev/ttyUSB* | wc -l)"
	if [ "$ttyUSB" == "0" ];then
		debug_echo "Ec200t script : There is no /dev/ttyUSB*"
		sleep 10
		continue
	fi
	ppp_mode="$(my_uci_get network.${section}.proto)"
	if [ "$ppp_mode" == "3g" ];then
		debug_echo "ppp dial mode, close current mode and break"
		break
	fi
	at_judge="$(at-cmd $atdev at | grep 'OK')"
	if [ -z "$at_judge" ];then
		sleep 2
		debug_echo "NOT AT OK"
		continue
	fi
	ret="$(at-cmd $atdev ati)"
	vendor=$(echo "${ret}" | sed -n '2p' | tr -d '\r')
	model=$(echo "${ret}" | sed -n '3p' | tr -d '\r')
	version=$(echo "${ret}" | sed -n '4p' | awk '{print $2}' | tr -d '\r')

	imei="$(at-cmd $atdev AT+GSN | sed -n '2p'|tr -d '\r')"
	cpin="$(at-cmd $atdev AT+CPIN? | sed -n '2p' | cut -d ':' -f2 | sed 's/ //g'|tr -d '\r')"

	#just iccid
	iccid="$(at-cmd $atdev AT+ICCID | sed -n '2p'|cut -c 9-28)"
	iccid_len=$(echo ${iccid} | wc -L)
	if [ $iccid_len != "20" ] && [ $iccid_len != "19" ];then
		iccid="NO SIM"
		cpin="None"
		isp="None"
		signal="0"
	fi
	
	#get isp
	isp="$(at-cmd $atdev AT+COPS? | sed -n '2p' | cut -d '"' -f2)"
	isp_dect=$(echo ${isp} | grep "COPS")
	if [ -n "${isp_dect}" ];then
		isp="No Service"
		debug_echo "quectel_ec200t_cn script : not get isp"
	fi

	#get signal
	rsrp=$(at-cmd $atdev AT+CSQ | sed -n '2p'|sed 's/.*:\(.*$\)/\1/' | cut -d ',' -f 1 | sed 's/ //g')
	if [ "$rsrp" == 99 ]; then
		signal=
	elif [ "$rsrp" -ge 14 ] && [ "$rsrp" -ne 99 ] ;then
		csq_temp=80
		csq_rsrp=$(printf "%d" $((($rsrp-14)*20/17)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rsrp" -ge 9 ];then
		csq_temp=60
		csq_rsrp=$(printf "%d" $((($rsrp-9)*20/5)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rsrp" -ge 4 ];then
		csq_temp=40
		csq_rsrp=$(printf "%d" $((($rsrp-4)*20/5)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rsrp" -ge 1 ];then
		csq_temp=20
		csq_rsrp=$(printf "%d" $((($rsrp-16)*20/3)))
		signal=$(expr $csq_temp + $csq_rsrp)
	else
		signal=
	fi

	net_type="$(at-cmd $atdev at+qnwinfo | sed -n '2p' | awk -F '"' '{print $2}' | tr -d '\r')"

	cgreg=$(at-cmd $atdev at+cgreg? | sed -n '2p' | sed 's/+CGREG: .,//g' | tr -d '\r')
	case $cgreg in
		1)
			cgreg="Registered OK"
			;;
		2)
			cgreg="Registering..."
			;;
		*)
			cgreg="Not registered"
			;;
	esac
	qnwinfo=$(at-cmd $atdev at+qnwinfo | sed -n '2p' | awk -F ':' '{print $2}')

	debug_echo "quectel_ec200t_cn script : create 4ginfo > /tmp/4ginfo"

#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor $model $version",
"imei":"$imei",
"iccid":"$iccid",
"pin":"$cpin",
"cops":"$isp",
"cgreg":"$cgreg",
"signal":"$signal",
"net_type":"$net_type",
"qnwinfo":"${qnwinfo}"
}
EOF
	# get sim status ，实现热插拔sim
	if [ "$cpin" != "READY" ];then
		debug_echo "cpin:$cpin != READY "
		restart_4g_module "$atdev" "$section"
		cnt=0
		debug_echo "sleep 8"
		sleep 8
		continue
	fi
	# get 4gwan status
	ret="$(ping_test $ifname)"
	sleep 1
	stat_4g="$(ifconfig $ifname | sed -n '2p' | grep "inet addr" | wc -l)"
	if [ "$stat_4g" == "0" -o "$ret" == "1" -o "$first_dial" == 1 ];then
		first_dial=0
		cnt=$((cnt+1))
		dial
		ifup "$section"
		debug_echo "exec $section diag and ifup $section"
	else
		cnt=0
	fi
	debug_echo "sleep 8"
	sleep 8
	[ "$cnt" -ge "4" ] && cnt=0 && debug_echo "dial fial 4 times" && restart_4g_module $atdev $section
done

