#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2

. /usr/sbin/anywifi/dial_common.sh

atdev="/dev/ttyUSB2"
ifname="$(get_rndsi_cdc_netcard_name)"
section="4gwan"
interfacename="4gwan"

#拨号
dial()
{
	debug_echo "Ec20 script : set apn and active PDP"
	apn="$(my_uci_get network.$section.apn)"
	username="$(my_uci_get network.$section.username)"
	password="$(my_uci_get network.$section.password)"
	pin="$(my_uci_get network.$section.pin)"
	(quectel-CM -4 -s "$apn" ${username} ${password} ${pin:+\-p $pin} 1>/dev/null 2>&1) &
}

#写配置
config()
{
	uci set network.$section=interface  
	uci set network.$section.ifname=$ifname
	uci set network.$section.proto=dhcp
	uci set network.$section.metric=5
	uci set network.wan.metric=3
	uci commit network
}

while [ 1 ]
do
	while [ ! -f /tmp/module_ifname ]
	do
		/usr/sbin/anywifi/rclocal.d/S99_module_ifname &
		sleep 2
	done
	ifname="$(cat /tmp/module_ifname)"
	while [ "$ifname" == none ]
	do
		ifname="$(cat /tmp/module_ifname)"
		sleep 5
	done
	ttyUSB="$(ls /dev/ttyUSB* | wc -l)"
	if [ "$ttyUSB" == "0" ];then
		debug_echo "There is no /dev/ttyUSB*"
		sleep 10
		continue
	fi

	set_firewall "$section"

	ret=$(at-cmd $atdev ATI)
	vendor=$(echo "${ret}" | sed -n '2p' | tr -d '\r')
	model=$(echo "${ret}" | sed -n '3p' | tr -d '\r')
	version=$(echo "${ret}" | sed -n '4p' | awk '{print $2}' | tr -d '\r')

	cpin=$(at-cmd $atdev at+cpin? | sed -n '2p' | awk -F ': ' '{print $2}' | tr -d '\r')
	imei=$(at-cmd $atdev AT+GSN | sed -n '2p'| tr -d '\r')

	#just iccid
	iccid=$(at-cmd $atdev AT+ICCID | sed -n '2p'| cut -c 9-28)
	iccid_len=$(echo ${iccid} | wc -L)
	if [ $iccid_len != "20" ];then
		iccid="NO_SIM_CARD"
		cpin="None"
		cops="None"
		signal="0"
	fi
	
	COPS=$(at-cmd $atdev AT+COPS? | sed -n '2p' | tr -d '\r')
	cops=$(echo "${COPS}" | cut -d '"' -f2)
	qnwinfo=$(at-cmd $atdev AT+QNWINFO | sed -n '2p' | tr -d '\r')

	#get signal
	rsrp=$(at-cmd $atdev AT+CSQ | sed -n '2p'|sed 's/.*:\(.*$\)/\1/' | cut -d ',' -f 1 | sed 's/ //g')
	if [ "$rsrp" == 99 ]; then
		signal=
	elif [ "$rsrp" -ge 14 ] && [ "$rsrp" -ne 99 ] ;then
		signal=80
		csq_rsrp=$(printf "%d" $((($rsrp-14)*20/17)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rsrp" -ge 9 ];then
		csq_temp=60
		csq_rsrp=$(printf "%d" $((($rsrp-9)*20/5)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rsrp" -ge 4 ];then
		csq_temp=40
		csq_rsrp=$(printf "%d" $((($rsrp-4)*20/5)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rsrp" -ge 1 ];then
		csq_temp=20
		csq_rsrp=$(printf "%d" $((($rsrp-16)*20/3)))
		signal=$(expr $csq_temp + $csq_rsrp)
	else
		signal=
	fi

	#just 4gwan interface is or not
	iface="$(uci show network | grep "4gwan" | wc -l)"
	if [ "$iface" == "0" ];then
		config
		debug_echo "create $section network config"
	fi

	imsi="$(at-cmd $atdev at+cimi | sed -n '2p' | tr -d '\r')"
	if [ "$(echo $imsi | wc -L)" != "15" ];then
		imsi=""
	fi
#	disabled_sa="$(at-cmd $atdev AT+QNWPREFCFG=\"nr5g_disable_mode\" | awk -F ',' '/\+QNWPREFCFG:/{print $2}' | tr -d '\r')"
#	[ $disabled_sa != 1 ] && mode_tmp=$(at-cmd $atdev AT+QNWPREFCFG=\"nr5g_disable_mode\",1)

	debug_echo "update 4ginfo > /tmp/4ginfo"

#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor $model",
"version":"$version",
"sim_status":"$cpin",
"signal":"$signal",
"iccid":"$iccid",
"imsi":"$imsi",
"imei":"$imei",
"cops":"$cops",
"COPS":"$COPS",
"qnwinfo":"$qnwinfo"
}
EOF
	if [ "$cpin" != "READY" ];then
		killall quectel-CM
		at-cmd $atdev AT+CFUN=0
		sleep 3
		at-cmd $atdev AT+CFUN=1
		sleep 2
		dial
		continue
	fi

	ret="$(ping_test $ifname)"
	stat_4g="$(ifconfig $ifname | sed -n '2p' | grep "inet addr" | wc -l)"
	if [ "$stat_4g" == "0" -o "$ret" == "1" ];then
			dial
			ifup $interfacename
			debug_echo "exec $section diag and ifup $interfacename"
	fi

	sleep 8
done

