#!/bin/sh

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2

. /usr/sbin/anywifi/dial_common.sh

atdev="/dev/ttyUSB1"
ifname="usb0" # dmesg too larger, can not get right ifname, so default is usb0
section="4gwan"
interfacename="4gwan"

#拨号
dial()
{
	apn="$(uci get network.$section.apn)"
	username="$(uci get network.$section.username)"
	password="$(uci get network.$section.password)"

	if [ "$apn" != "" -a "$username" != "" -a "$password" != "" ];then
		connect_manager -s $apn $username $password &
	elif [ "$apn" != "" ];then
		connect_manager -s $apn &
	else
		connect_manager &
	fi

}

#写配置
config()
{
	uci set network.$section=interface
	uci set network.$section.ifname="$ifname"
	uci set network.$section.proto=dhcp
	uci set network.$section.metric=5
}

