#!/bin/sh

if [ -e "/var/run/${0##*/}.pid" ] ;then
	if [ -e "/proc/$(cat /var/run/${0##*/}.pid)" ];then
		echo "${0##*/} is already running"
		return 2
	fi
fi
echo "$$" > /var/run/${0##*/}.pid

. /usr/sbin/anywifi/dial_common.sh

ifname="$(get_rndsi_cdc_netcard_name)"
section="4gwan"
interfacename="4gwan"

timeout()
{
    local time cmd pid

    if echo "$1" | grep -Eq '^[0-9]+'; then
        time=$1
        shift && cmd="$@"
    else
        time=5
        cmd="$@"
    fi

    $cmd  &
	debug_echo "timeout cmd=$cmd"
    pid=$!

    while kill -0 $pid &>/dev/null; do
        sleep 1
        let time-=1

        if [ "$time" = "0" ]; then
            kill -9 $pid &>/dev/null
            wait $pid &>/dev/null
        fi
    done
}

nc_cmd(){
	local cmd="$@"
	local ret
	cmd="U2FsdGVkX19t0MJSpA7C9SCv7yDwigWm/{\"phoneId\":0,\"command\":\"$cmd\"}"
	debug_echo "cmd=$cmd"
	echo -n $cmd | nc 192.168.42.129 51848
}

nc_cmd_extra(){
	local cmd="$@"
	local ret
	cmd="U2FsdGVkX19t0MJSpA7C9SCv7yDwigWm/{\"custom\":1,\"command\":\"$cmd\"}"
	debug_echo "cmd=$cmd"
	echo -n $cmd | nc 192.168.42.129 51848
}

#拨号
dial()
{
	apn="$(my_uci_get network.$section.apn)"
	# nc_cmd AT+CGDCONT=1,\"IP\",\"${apn}\"
	nc_cmd_extra openNetwork
	sleep 5
}

#写配置
config()
{
	uci set network.${section}=interface
	uci set network.${section}.ifname=${ifname}
	uci set network.${section}.proto=dhcp
	uci set network.${section}.metric=5
	uci set network.wan.metric=3
	uci commit network
}

restart_4g_module(){
	local section="$"
	gpio_4g="$(my_uci_get netcard.device.module_gpio)"
	active="$(my_uci_get netcard.device.active)"
	if [ "$gpio_4g" == "" ];then
		debug_echo "use cfun restart_4g_module"
		nc_cmd_extra reboot
	else
		debug_echo "use gpio restart_4g_module"
		[ -z "$active" ] && active=1
		[ "$active" == "1" ] && value=0
		[ "$active" == "0" ] && value=1
		echo $value > /sys/class/gpio/gpio${gpio_4g}/value
		sleep 5
		echo $active > /sys/class/gpio/gpio${gpio_4g}/value
		sleep 15
	fi
	ifup "$section"
}

ppp_mode="$(my_uci_get network.${section}.proto)"
if [ "$ppp_mode" == "3g" ];then
	debug_echo "ppp dial mode, close current mode and break"
	exit
fi

while [ ! -f /tmp/module_ifname ]
do
	/usr/sbin/anywifi/rclocal.d/S99_module_ifname &
	sleep 2
done
ifname="$(cat /tmp/module_ifname)"
while [ "$ifname" == none ]
do
	ifname="$(cat /tmp/module_ifname)"
	sleep 5
done
#判断模块配置
set_firewall "$section"
config_judge=0
[ "$(uci -q get network.4gwan)" == "interface" ] || config_judge=1
[ "$(uci -q get network.4gwan.ifname)" == "$ifname" ] || config_judge=1
[ "$(uci -q get network.4gwan.proto)" == "dhcp" ] || config_judge=1
[ -n "$(uci -q get network.4gwan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ -n "$(uci -q get network.wan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ "$(uci -q get network.wan.metric)" != "$(uci -q get network.4gwan.metric)" ] || config_judge=1
if [ "$config_judge" == 1 ];then
	config
	debug_echo "reate $section network config"
	ifup wan
	ifup "$section"
fi

ping_sh_pid="$(ps -w | grep "/usr/sbin/anywifi/manual_dial/module_ping.sh" | grep -v "grep" | awk '{print $1}')"
if [ -z "$ping_sh_pid" ];then
	/usr/sbin/anywifi/manual_dial/module_ping.sh $ifname &
fi

first_dial=1
while [ 1 ]
do
	ip_set="$(ifconfig $ifname | sed -n '2p' | grep "inet addr" | wc -l)"
	if [ "$ip_set" == "0" ];then
		debug_echo "TM21C script : There is no $ifname"
		ifup "$section"
		sleep 10
		ip_set="$(ifconfig $ifname | sed -n '2p' | grep "inet addr" | wc -l)"
		continue
	fi
	ppp_mode="$(my_uci_get network.${section}.proto)"
	if [ "$ppp_mode" == "3g" ];then
		debug_echo "ppp dial mode, close current mode and break"
		break
	fi
	ping_addr1=$(my_uci_get anyos_netwatchdog.device.detect_host1)
	[ "$ping_addr1" == "" ] && ping_addr1="114.114.114.114"

	ping_addr2=$(my_uci_get anyos_netwatchdog.device.detect_host2)
	[ "$ping_addr2" == "" ] && ping_addr2="223.5.5.5"

	ping -I $ifname -c 1 -w 3 -W 3 -s 0 $ping_addr1 > /dev/null 2>&1
	ret1=$?

	ping -I $ifname -c 1 -w 3 -W 3 -s 0 $ping_addr2 > /dev/null 2>&1
	ret2=$?
	if [ "$ret1" != "0" -a "$ret2" != "0" ];then
		sleep 10
		continue
	fi
	#读取模块信息
	ATE="$(nc_cmd ATE1)"
	ATE_judge="$(echo "$ATE" | grep ATE)"
	while [ -z "$ATE_judge" ]
	do
		ATE="$(nc_cmd ATE1)"
		ATE_judge="$(echo "$ATE" | grep ATE)"
		sleep 1
	done
	vendor="$(nc_cmd AT+CGMR | awk '/BASE/{print $3}')"
	sleep 1
	cpin="$(nc_cmd AT+CPIN? | sed -n '2p' | awk -F ': ' '{print $2}' | tr -d '\r')"
	sleep 1
	imei="$(nc_cmd AT+GSN | sed -n '2p'| tr -d '\r')"
	sleep 1
	#get isp
	isp="$(nc_cmd AT+COPS? | sed -n '2p' | cut -d '"' -f2)"
	isp_dect="$(echo ${isp} | grep "COPS")"
	if [ -n "${isp_dect}" ];then
		cops="No Service"
		debug_echo "TM21C script : not get isp"
	else
		cops="$isp"
	fi
	sleep 1
	is_LTE=0
	rssi="$(nc_cmd AT+CSQ | sed -n '1p' | sed 's/.*:\(.*$\)/\1/' | cut -d ',' -f 1 | sed 's/ //g')"
	if [ "$rssi" == 99 ]; then
		signal=
		is_LTE=1
	elif [ "$rssi" == "199" ];then
		signal=
	elif [ "$rssi" == "31" ];then
		signal=100
	elif [ "$rssi" -ge 14 ] && [ "$rssi" -lt 31 ] ;then
		csq_temp=80
		csq_rsrp=$(printf "%d" $((($rssi-14)*20/17)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rssi" -ge 9 ];then
		csq_temp=60
		csq_rsrp=$(printf "%d" $((($rssi-9)*20/5)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rssi" -ge 4 ];then
		csq_temp=40
		csq_rsrp=$(printf "%d" $((($rssi-4)*20/5)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rssi" -ge 1 ];then
		csq_temp=20
		csq_rsrp=$(printf "%d" $((($rssi-16)*20/3)))
		signal=$(expr $csq_temp + $csq_rsrp)
	else
		signal=
	fi

	if [ "$is_LTE" == 1 ];then
		sleep 1
		rsrp_report="$(nc_cmd AT+CESQ | sed -n '1p' | sed 's/.*:\(.*$\)/\1/' | cut -d ',' -f 6 | sed 's/ //g')"
		[ "$rsrp_report" == 255 ] && signal=
		rsrp="$((rsrp_report - 140))"
		if [ "$rsrp" -ge "-44" ];then
			signal=100
		elif [ "$rsrp" -ge "-85" ];then
			csq_temp=80
			csq_rsrp=$(printf "%d" $((($rsrp-(-85))*20/41)))
			signal=$(expr $csq_temp + $csq_rsrp)
		elif [ "$rsrp" -ge "-95" ];then
			csq_temp=60
			csq_rsrp=$(printf "%d" $((($rsrp-(-95))*20/10)))
			signal=$(expr $csq_temp + $csq_rsrp)
		elif [ "$rsrp" -ge "-105" ];then
			csq_temp=40
			csq_rsrp=$(printf "%d" $((($rsrp-(-105))*20/10)))
			signal=$(expr $csq_temp + $csq_rsrp)
		elif [ "$rsrp" -ge "-115" ];then
			csq_temp=20
			csq_rsrp=$(printf "%d" $((($rsrp-(-115))*20/10)))
			signal=$(expr $csq_temp + $csq_rsrp)
		elif [ "$rsrp" -lt "-115" ];then
			csq_temp=0
			csq_rsrp=$(printf "%d" $((($rsrp-(-140))*20/25)))
			signal=$(expr $csq_temp + $csq_rsrp)
		else
			signal=
		fi
	fi
	sleep 1
	SelfTest="$(nc_cmd_extra SelfTest)"
	sleep 1
	imsi="$(nc_cmd at+cimi | sed -n '2p' | tr -d '\r')"
	sleep 1
	cpin="$(nc_cmd at+cpin? | sed -n '2p' | awk -F ': ' '{print $2}' | tr -d '\r')"
	debug_echo "TM21C script : update 4ginfo > /tmp/4ginfo"
#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor TM21C",
"signal":"$signal",
"imei":"$imei",
"imsi":"$imsi",
"cpin":"$cpin",
"SelfTest":"$SelfTest",
"cops":"$cops"
}
EOF
	if [ "$first_dial" == 1 ];then
		first_dial=0
		dial
		debug_echo "exec $section diag and ifup $section"
	fi
	debug_echo "sleep 8"
	sleep 8

done


