#!/bin/sh

#写配置
config()
{
	section=$1
	config_dev=$2
	uci set network.$section=interface  
	uci set network.$section.proto=3g
	uci set network.$section.device=$config_dev
	uci set network.$section.model=$model
}

board=`awk 'BEGIN{FS="[ \t]+:[ \t]"} /machine/ {print $2}' /proc/cpuinfo`

#读取模块信息
atdev="/dev/ttyUSB2"
dial_dev="/dev/ttyUSB3"
vendor=$(at-cmd $atdev AT+CGMI |sed -n '2p'|tr -d '\r')
model=$(at-cmd $atdev AT+GMM |sed -n '2p'|tr -d '\r')
imei=$(at-cmd $atdev AT+GSN |sed -n '2p'|tr -d '\r')
if [ "$board" = "ZBT-WE2806" ];then
	atdev2="/dev/ttyUSB7"
	dial_dev2="/dev/ttyUSB8"
	vendor2=$(at-cmd $atdev2 AT+CGMI |sed -n '2p'|tr -d '\r')
	model2=$(at-cmd $atdev2 AT+GMM |sed -n '2p'|tr -d '\r')
	imei2=$(at-cmd $atdev2 AT+GSN |sed -n '2p'|tr -d '\r')
fi 

#判断模块配置
config_model=`uci get network.4g.model 2>/dev/null`
if [ "$config_model" != "$model" ];then
	config 4g $dial_dev
	if [ "$board" = "ZBT-WE2806" ];then
		config 4g2 $dial_dev2
		uci set network.4g.metric=10
		uci set network.4g2.metric=11
	fi
	uci commit network
	/etc/init.d/network reload
fi

while [ 1 ]
do
	while [ ! -f /tmp/module_ifname ]
	do
		/usr/sbin/anywifi/rclocal.d/S99_module_ifname &
		sleep 2
	done
	ifname="$(cat /tmp/module_ifname)"
	while [ "$ifname" == none ]
	do
		ifname="$(cat /tmp/module_ifname)"
		sleep 5
	done
	#读卡
	iccid=$(at-cmd $atdev AT+ICCID|sed -n '2p'|cut -c 8-27)
	iccid_len=$(echo ${iccid}|wc -L)
	if [ $iccid_len != "20" ];then
		iccid="NO SIM"
		cpin="None"
		isp="None"
		signal="0"
	else	
		cpin=$(at-cmd $atdev AT+CPIN?|sed -n '2p'|cut -d ':' -f2|sed 's/ //g'|tr -d '\r')
		isp=$(at-cmd $atdev AT+COPS?|sed -n '2p'|cut -d '"' -f2)
		isp_dect=$(echo ${isp}|grep "COPS")
		if [ -n "${isp_dect}" ];then
			isp="No Service"
		fi
		signal=$(at-cmd $atdev AT+CSQ|sed -n '2p'|sed 's/.*:\(.*$\)/\1/'| cut -d ',' -f 1|sed 's/ //g')
		if [ "$signal" -le 31 ];then
			signal=$(printf "%d" $((signal*100/31)))
		else
			signal="0"
		fi
	fi
	if [ "$board" = "ZBT-WE2806" ];then
		#读卡
		iccid2=$(at-cmd $atdev2 AT+ICCID|sed -n '2p'|cut -c 8-27)
		iccid2_len=$(echo ${iccid2}|wc -L)
		if [ $iccid2_len != "20" ];then
			iccid2="NO SIM"
			cpin2="None"
			isp2="None"
			signal2="0"
		else
			cpin2=$(at-cmd $atdev2 AT+CPIN?|sed -n '2p'|cut -d ':' -f2|sed 's/ //g'|tr -d '\r')
			isp2=$(at-cmd $atdev2 AT+COPS?|sed -n '2p'|cut -d '"' -f2)
			isp2_dect=$(echo ${isp2}|grep "COPS")
			if [ -n "${isp2_dect}" ];then
				isp2="No Service"
			fi
			signal2=$(at-cmd $atdev2 AT+CSQ|sed -n '2p'|sed 's/.*:\(.*$\)/\1/'| cut -d ',' -f 1|sed 's/ //g')
			if [ "$signal2" -le 31 ];then
				signal2=$(printf "%d" $((signal2*100/31)))
			else
				signal2="0"
			fi
		fi
	fi
	
	#信号灯
	if [ $board = "ZBT-WE2806" ] || [ $board = "ZbtlinkZBT-WE2416" ] || [ $board = "ZBT-WE2806-A" ];then
		if [ $signal -ge 75 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 1 > /sys/class/leds/rssi2/brightness
			echo 1 > /sys/class/leds/rssi3/brightness
		elif [ $signal -ge 50 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 1 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		elif [ $signal -ge 25 ];then
			echo 1 > /sys/class/leds/rssi1/brightness
			echo 0 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		else
			echo 0 > /sys/class/leds/rssi1/brightness
			echo 0 > /sys/class/leds/rssi2/brightness
			echo 0 > /sys/class/leds/rssi3/brightness
		fi
	fi
	if [ "$board" = "ZBT-WE2806" ];then	
		if [ $signal2 -ge 75 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 1 > /sys/class/leds/rssi22/brightness
			echo 1 > /sys/class/leds/rssi32/brightness
		elif [ $signal2 -ge 50 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 1 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		elif [ $signal2 -ge 25 ];then
			echo 1 > /sys/class/leds/rssi12/brightness
			echo 0 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		else
			echo 0 > /sys/class/leds/rssi12/brightness
			echo 0 > /sys/class/leds/rssi22/brightness
			echo 0 > /sys/class/leds/rssi32/brightness
		fi
	fi
	
	#WE2806-A sim卡指示灯
	if [ $board = "ZBT-WE2806-A" ] || [ $board = "ZBT-WE826-E" ] ;then
		sim_gpio=`cat /sys/class/gpio/sim/value`
		if [ $sim_gpio = "1" ];then
			echo 1 > /sys/class/leds/sim1/brightness
			echo 0 > /sys/class/leds/sim2/brightness
			sim="(SIM 1)"
		else
			echo 0 > /sys/class/leds/sim1/brightness
			echo 1 > /sys/class/leds/sim2/brightness
			sim="(SIM 2)"
		fi
	else
		sim=""
	fi
		

#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor $model",
"imei":"$imei",
"iccid":"$iccid$sim",
"pin":"$cpin",
"isp":"$isp",
"signal":"$signal"
}
EOF

if [ $imei2 != "" ];then
cat > /tmp/4ginfo2 <<EOF
{
"device_model":"$vendor2 $model2",
"imei":"$imei2",
"iccid":"$iccid2",
"pin":"$cpin2",
"isp":"$isp2",
"signal":"$signal2"
}
EOF
fi
	sleep 10
done

