#!/bin/sh

#1c9e:9b05 

[[ "$(pidof ${0##*/} | wc -w)" -gt "2" ]] && echo "Already running ..." && return 2

. /usr/sbin/anywifi/dial_common.sh

atdev="/dev/$(awk -F ' ' '{print $4}' /tmp/mobile_module_name.txt)"
ifname=""
section="4gwan"

#拨号
dial()
{
	apn=`my_uci_get network.$section.apn 2>/dev/null`
	at-cmd $atdev AT+CGDCONT=1,\"IP\",\"${apn}\"
	at-cmd $atdev AT\$QCRMCALL=0,1
	sleep 3
	at-cmd $atdev AT\$QCRMCALL=1,1
}

#写配置
config()
{
	uci set network.${section}=interface
	uci set network.${section}.ifname=${ifname}
	uci set network.${section}.proto=dhcp
	uci set network.${section}.metric=5
	uci set network.wan.metric=3
	uci commit network
}

ppp_mode="$(my_uci_get network.${section}.proto)"
if [ "$ppp_mode" == "3g" ];then
	debug_echo "ppp dial mode, close current mode and break"
	exit
fi

while [ ! -f /tmp/module_ifname ]
do
	/usr/sbin/anywifi/rclocal.d/S99_module_ifname &
	sleep 2
done
ifname="$(cat /tmp/module_ifname)"
while [ "$ifname" == none ]
do
	ifname="$(cat /tmp/module_ifname)"
	sleep 5
done
#判断模块配置
set_firewall "$section"
config_judge=0
[ "$(uci -q get network.4gwan)" == "interface" ] || config_judge=1
[ "$(uci -q get network.4gwan.ifname)" == "$ifname" ] || config_judge=1
[ "$(uci -q get network.4gwan.proto)" == "dhcp" ] || config_judge=1
[ -n "$(uci -q get network.4gwan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ -n "$(uci -q get network.wan.metric | grep -w "[0-9]\+")" ] || config_judge=1
[ "$(uci -q get network.wan.metric)" != "$(uci -q get network.4gwan.metric)" ] || config_judge=1
if [ "$config_judge" == 1 ];then
	config
	debug_echo "reate $section network config"
	ifup wan
	ifup "$section"
fi

ping_sh_pid="$(ps -w | grep "/usr/sbin/anywifi/manual_dial/module_ping.sh" | grep -v "grep" | awk '{print $1}')"
if [ -z "$ping_sh_pid" ];then
	/usr/sbin/anywifi/manual_dial/module_ping.sh $ifname &
fi
trap "restart_4g_module $atdev $section" USR1
first_dial=1
while [ 1 ]
do
	ttyUSB="$(ls /dev/ttyUSB* | wc -l)"
	if [ "$ttyUSB" == "0" ];then
		debug_echo "u8300w script : There is no /dev/ttyUSB*"
		sleep 10
		continue
	fi
	ppp_mode="$(my_uci_get network.${section}.proto)"
	if [ "$ppp_mode" == "3g" ];then
		debug_echo "ppp dial mode, close current mode and break"
		break
	fi

	ret=$(at-cmd $atdev ati)
	vendor="LONGSUNG"
	model=$(echo "${ret}" | sed -n '3p' | awk '{print $2}' | tr -d '\r')
	version=$(echo "${ret}" | sed -n '4p' | awk '{print $2}' | tr -d '\r')
	imei=$(echo "${ret}" | sed -n '5p' | awk '{print $2}' | tr -d '\r')

	cpin=$(at-cmd $atdev AT+CPIN? | sed -n '2p' | cut -d ':' -f2 | sed 's/ //g'|tr -d '\r')

	#just iccid
	iccid=$(at-cmd $atdev AT+ICCID | sed -n '2p'| awk '{print $2}' | tr -d '\r')
	iccid_len=$(echo ${iccid} | wc -L)
	if [ $iccid_len != "20" ] && [ $iccid_len != "19" ];then
		iccid="NO SIM"
		cpin="None"
		cops="None"
		signal="0"
	fi
	
	#get cops
	cops=$(at-cmd $atdev AT+COPS? | sed -n '2p' | cut -d '"' -f2)
	cops_dect=$(echo ${cops} | grep "COPS")
	if [ -n "${cops_dect}" ];then
		cops="No Service"
		debug_echo "u8300w script : not get cops"
	fi

	#get signal
	rsrp=$(at-cmd $atdev at+csq | sed -n '2p' | cut -b 7-8)
	if [ "$rsrp" == 99 ]; then
		signal=
	elif [ "$rsrp" -ge 14 ] && [ "$rsrp" -ne 99 ] ;then
		csq_temp=80
		csq_rsrp=$(printf "%d" $((($rsrp-14)*20/17)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rsrp" -ge 9 ];then
		csq_temp=60
		csq_rsrp=$(printf "%d" $((($rsrp-9)*20/5)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rsrp" -ge 4 ];then
		csq_temp=40
		csq_rsrp=$(printf "%d" $((($rsrp-4)*20/5)))
		signal=$(expr $csq_temp + $csq_rsrp)
	elif [ "$rsrp" -ge 1 ];then
		csq_temp=20
		csq_rsrp=$(printf "%d" $((($rsrp-16)*20/3)))
		signal=$(expr $csq_temp + $csq_rsrp)
	else
		signal=
	fi

	net_type="$(at-cmd $atdev at+psrat | sed -n '2p' | awk -F ':' '{print $2}' | tr -d '\r')"

	cgreg=$(at-cmd $atdev at+cgreg? | sed -n '2p' | sed 's/+CGREG: .,//g' | tr -d '\r')
	case $cgreg in
		1)
			cgreg="Registered OK"
			;;
		2)
			cgreg="Registering..."
			;;
		*)
			cgreg="Not registered"
			;;
	esac

	debug_echo "u8300w script : create 4ginfo > /tmp/4ginfo"

#输出json
cat > /tmp/4ginfo <<EOF
{
"device_model":"$vendor $model",
"version":"$version",
"imei":"$imei",
"iccid":"$iccid",
"pin":"$cpin",
"cops":"$cops",
"cgreg":"$cgreg",
"signal":"$signal",
"net_type":"$net_type"
}
EOF
	# get sim status ，实现热插拔sim
	if [ "$cpin" != "READY" ];then
		debug_echo "cpin:$cpin != READY "
		restart_4g_module "$atdev" "$section"
		cnt=0
		debug_echo "sleep 8"
		sleep 8
		continue
	fi
	# get 4gwan status
	ret="$(ping_test $ifname)"
	sleep 1
	stat_4g="$(ifconfig $ifname | sed -n '2p' | grep "inet addr" | wc -l)"
	if [ "$stat_4g" == "0" -o "$ret" == "1" -o "$first_dial" == 1 ];then
		first_dial=0
		cnt=$((cnt+1))
		dial
		ifup "$section"
		debug_echo "exec $section diag and ifup $section"
	else
		cnt=0
	fi
	debug_echo "sleep 8"
	sleep 8
	[ "$cnt" -ge "4" ] && cnt=0 && debug_echo "dial fial 4 times" && restart_4g_module $atdev $section
done

